### ISSUE TITLE
How to include the source files I want to test?

### ISSUE THREAD

**Issue by callumlocke** [yeoman/generator-webapp_DEPRECATED#101]
The `test/index.html` contains this:

``` html
    <!-- include source files here... -->

    <!-- include spec files here... -->
    <script src="spec/test.js"></script>
```

But how am I supposed to include my `app/scripts/**` source files?

Doing `<script src="../app/scripts/foo.js"></script>` doesn't work, because when I run `grunt test`, it mounts the `test` directory with connect, and serves it as `localhost:9000/index.html`. So the `../` doesn't work.

I can edit my Gruntfile to make this work, but is there some other way I'm supposed to do this?

**Comment by kjarnet** [comment]
Seems adding "mountFolder(connect, yeomanConfig.app)," to connect -> test -> options -> middelware (after  https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L78) does the trick. Then you can reference your source-files like you do in app/index.html. Now it will no longer work to open test/index.html statically though.

I'd guess app/index.html would now clash with test/index.html, but somehow it seems to work out. Renaming test/index.html to something like test/testindex.html (and changing https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L127 correspondingly) would probably be a good idea though.

I tried to make a pull-request, but I couldn't figure out how to do the renaming of the test-index file, as it's generated by a "sub-generator" (generator-mocha or -jasmine) and is sadly not configurable through these.

**Comment by hashchange** [comment]
@kjarnet I have run into the exact same problem, and your suggestion was very helpful indeed. Thanks!
