### ISSUE TITLE
Test counting is broken?

### ISSUE THREAD

**Issue by lightquake** [yeoman/generator-webapp_DEPRECATED#104]
If I make an empty director, run yo webapp, and then change test/spec/test.js to include `expect(2).to.equal(3)` in the test case, it tells me '1 of NaN tests failed', even if I add more tests. (If they pass, then the tests are counted successfully.)

**Comment by passy** [comment]
We use [grunt-mocha](https://github.com/kmiyashiro/grunt-mocha) to run the tests. Please open an issue over there. Thanks!
