### ISSUE TITLE
Make coffeescript source maps work

### ISSUE THREAD

**Issue by wmertens** [yeoman/generator-webapp_DEPRECATED#105]
http://github.com/gruntjs/grunt-contrib-coffee supports generating source maps with the `sourceMap: true` option.

However, if you just turn this on, the sourcemap will refer to the original source which is not part of the dist dir and therefore not accessible by the browser; therefore it won't work.

I don't really know how to fix it; I presume the sources need to be copied somewhere before the compilation step but there's already a copy task?.

After that, probably the minification step needs to be configured to take the source maps into account?

**Comment by addyosmani** [comment]
Enable `sourceMap: true` and you should just be able to use the copy task to copy the sources over prior to minification.

**Comment by passy** [comment]
I believe we would need some assistance from `grunt-contrib-coffee`. The sourcemap contains a hard-coded path to `../../app/scripts`, so the lookup of the original coffee file always fails.

**Comment by chrisjowen** [comment]
@passy, I couldn't find any hardcoded path to ../../app/scripts, seems relative to the source directory. Managed to get  addyosmani suggestion of copy first to .tmp/ dir and run coffee:dist against the files there. This produced correct relative path in the sourceMap files

**Comment by passy** [comment]
Thanks for the update, Chris. I'll give it another try.

**Comment by astronaute77** [comment]
@chrisjowen can you please elaborate, I'm unsure about how to proceed in order to debug .coffee files.

I have this grunt task:

```
    coffee: {
      dist: {
        options: {
          sourceMap: true
        },
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/scripts',
          src: '{,*/}*.coffee',
          dest: '.tmp/scripts',
          ext: '.js'
        }]
      }
    }
```

this generates `main.js` and `main.js.map` in `tmp/scripts/controllers/` but the "main.js.map" contains:

```
{
  "version": 3,
  "file": "main.js",
  "sourceRoot": "../../../app/scripts/controllers/",
  "sources": [
    "main.coffee"
  ],
  "names": [],
  "mappings": "..."
}
```

TIA

**Comment by chrisjowen** [comment]
@addyosmani I no longer have the grunt file available that did this, but basically because you are generating the map files from <%= yeoman.app %>/scripts which is outside of where the webapp can reach the map files will be garbage. Instead I used the copy task to copy the .coffee files to .tmp/ and then the coffee dist task runs against those files.

**Comment by mikefowler** [comment]
The solution is pretty succinctly described by @addyosmani at the top of this thread, but here's a more elaborate writeup I did for folks needing to accomplish this in the future: http://bit.ly/1avMqrG

**Comment by addyosmani** [comment]
Thanks for sharing the write-up! :) We'll make sure to reference it for others that run into this issue in the future.

**Comment by addyosmani** [comment]
For future folks interested: the post linked above by Mike is worth reading if you would like to enable this in your own setups. I wouldn't mind us landing any necessary changes to make this work well with the --coffee option for -webapp, but this would need to be done via  PR as we're currently focused on larger feature efforts. Closing for now.
