### ISSUE TITLE
Running `grunt test` with mocha or jasmine throws EACCES error

### ISSUE THREAD

**Issue by pete-otaqui** [yeoman/generator-webapp_DEPRECATED#106]
I'm using yeoman 1.0.0-rc.1.1, with npm cache cleared, system rebooted and everything freshly installed on OS X Lion.

Every time I create a new webapp and immediately run `grunt test` I get the following problem:

```
Running "clean:server" (clean) task

Running "concurrent:test" (concurrent) task

    Running "coffee:dist" (coffee) task
    File .tmp/scripts/hello.js created.

    Running "coffee:test" (coffee) task

    Done, without errors.

Running "connect:test" (connect) task
Starting connect web server on localhost:9000.

Running "jasmine:all" (jasmine) task
Testing jasmine specs via phantom
Fatal error: spawn EACCES
```

As you can see in this case I've replaced mocha with jasmine, and it's the same error in either case.

`sudo` makes no difference.

**Comment by pete-otaqui** [comment]
Seems that the file `~/webapp/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs` doesn't have +x set on it :)

**Comment by pete-otaqui** [comment]
Seems that the file `~/webapp/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs` doesn't have +x set on it :)

**Comment by passy** [comment]
Hm, I haven't heard of that bug before. If this happens again, could you report it at the [phantomjs](https://github.com/ariya/phantomjs) repository?

**Comment by vovacodes** [comment]
I had the similar problem when tried to execute grunt on my Ubuntu while the project files was on NTFS drive. So all of the [files in node_modules lacked 'x' permission](http://askubuntu.com/questions/30243/why-does-ubuntu-refuse-to-execute-files-from-an-ntfs-partition) and process failed trying to execute binary from that directory. I've fixed that by adding that permissions to files on NTFS drive by default. Hope this will help somebody

**Comment by dflynn15** [comment]
I experienced the same issue however this is specifically related to the grunt-contrib-jasmine repo not the phantomjs  repo.

**Comment by jaismichael** [comment]
Running "jasmine:src" (jasmine) task
Testing jasmine specs via PhantomJS

Fatal error: spawn EACCES

Tried by clearing cache and setting execute permission to node_modules in Ubuntu.

**Comment by renanborgez** [comment]
same issue here with jasmine
