### ISSUE TITLE
Integrate grunt-modernizr

### ISSUE THREAD

**Issue by passy** [yeoman/generator-webapp_DEPRECATED#107]
Should we integrate grunt-modernizr? Would be nice if we had a lean build based on what's actually used instead of shipping with the full-blown copy.

https://github.com/Modernizr/grunt-modernizr

**Comment by addyosmani** [comment]
I'm +1 for this. grunt-modernizr is _amazing_ and I don't feel like enough developers are aware it exists or can be particularly helpful yet.

**Comment by sindresorhus** [comment]
It's good, but our Gruntfile is already way to big and using Modernizr isn't something everyone does. I would rather see it documented.

**Comment by passy** [comment]
Prompt?

**Comment by sindresorhus** [comment]
Sure, but I would say not until we got the learning prompt so it's not asked every time.

But I don't feel strongly about this. If you feel it would be useful enough to justify its existence either by default or prompt. Go for it.

**Comment by passy** [comment]
> Sure, but I would say not until we got the learning prompt so it's not asked every time.

Yup, absolutely. I think we shouldn't go for more than the three prompts that we have at the moment without the learning extension. However, autoprefixer is getting good feedback so maybe we can drop the prompt in the future.

**Comment by addyosmani** [comment]
I haven't seen a great deal (if any) of negative feedback about autoprefixer support so it is indeed possible that it'll become a default option in the future. 

Re: no more than three prompts. I agree, but aside from grunt-modernizr we're going to have to think about how we handle giving users more choice around coffee support and compass in this generator. 

I personally favour prompts for them, but who knows - perhaps flags would better.

**Comment by sindresorhus** [comment]
> I personally favour prompts for them, but who knows - perhaps flags would better.

With the learning prompts I can't see any downside of both of them being prompts, since they'll only be asked once.
