### ISSUE TITLE
CSS gets duplicated on build

### ISSUE THREAD

**Issue by tylercraft** [yeoman/generator-webapp_DEPRECATED#108]
This can be duplicated by doing the following in an empty folder:

`yo webapp` (i selected `no` to everything except autoprefixing)
`grunt`

View that the `main.css` file in the `dist` folder, while it's been minified, has been duplicated. 

If you throw in something that will be auto prefixed, the first 'copy' of the css file has been auto prefixed while the second has not been. I played around with the grunt file for a bit, but haven't had time to figure out the exact directive that is causing the problem. I'm assuming it's an order problem.

A quick fix is to rename the file in the app folder to main.scss and then it works just fine.

**Comment by addyosmani** [comment]
Are you able to reproduce this issue when autoprefixing is turned off (i.e you've selected no to everything)? It would be useful to determine if it's specifically autoprefixer that's causing this change.

**Comment by passy** [comment]
Confirmed. I'm looking into this.

**Comment by tylercraft** [comment]
Out of the box, it is **not** happening when autoprefixing is turned off.

I've only had a couple minutes to really look into it, but while comparing Gruntfiles I noticed the `copy:styles` block was automatically added if autoprefixing was selected. I added this to the non-autoprefixing project and the duplication starts happening again. Not sure if the cause is really in the copy:styles block or due to something else, but it may be a good place to start looking.

I'm not familiar enough with the inner workings of Grunt to immediately see which exact line is causing the issue. But am more than happy to look into this deeper.

**Comment by stephenplusplus** [comment]
I was able to reproduce the issue and fix with Tyler's solution. Is the `copy:styles` task necessary in any case now?

**Comment by passy** [comment]
The copy task is needed so we can mix vanilla CSS and Sass. You could do it without that, but then you would need one task that autoprefixes in server mode and puts them into .tmp and two in dist mode that autoprefixes the compiled Sass from .tmp to dist and vanilla css from app to dist. Neither way is pretty, but I found this one easier to follow.
