### ISSUE TITLE
Build not copying over html files in subdirectories?

### ISSUE THREAD

**Issue by KingScooty** [yeoman/generator-webapp_DEPRECATED#113]
Building projects doesn't seem to copy over any HTML files in subdirectories, and i can't figure out why. All the root level files copy over to the `dist` folder just fine, but subdirectories don't get copied at all.

I'm using the latest gruntfile for the webapp generator.

**Comment by passy** [comment]
This is the default behavior. You can easily adjust your `Gruntfile.js` by changing these lines:

https://github.com/yeoman/generator-webapp/blob/2ec19f153408e931230bece89a860977bb1ed007/app/templates/Gruntfile.js#L300-303

You would need to change `*.html` to something like `{*/,}*.html` to run one level deep or `**/*.html` for as deep as it goes.

**Comment by KingScooty** [comment]
I already have done that though!

`{*/,}*.html` and `{,*/}*.html` don't copy over the subdirs when building.
`**/*.html` throws an error and the build process stops.

**Comment by oskarrough** [comment]
What error does it throw? Could you post a link to your Gruntfile.js?
