### ISSUE TITLE
Make the Compass grunt task optional

### ISSUE THREAD

**Issue by asapach** [yeoman/generator-webapp_DEPRECATED#114]
`compass` task assumes the presence of Compass and Ruby in the path, which is not an explicit prerequisite. The task runs even when the project doesn't contain any SASS files and fails as the result:

> Warning: Running "compass:dist" (compass) task
> Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

I believe Compass should be an optional component in the template.

**Comment by sindresorhus** [comment]
Yes, that's planned.

**Comment by addyosmani** [comment]
Both Compass and CoffeeScript are examples of features we're considering making optional. The piece of work we are waiting on to land before they move to prompts is https://github.com/yeoman/generator/issues/277.

**Comment by passy** [comment]
I think we should consider removing the prompt for autoprefixer before making compass optional to reduce the complexity of the Gruntfile. The CSS pipeline is already super confusing.

**Comment by sindresorhus** [comment]
I would like for us to do this soon.

I think we should also consider bringing in grunt-sass as an alternative to Compass (though with visible warning that some Sass features might not be implemented). grunt-sass is way faster than compass, and would really help speed up livereload to be instantaneous instead of taking 2s.

**Comment by addyosmani** [comment]
@sindresorhus do you have a link to a thread or somewhere where perf benchmarking was done between the two? I'm really interested in seeing whether the speed improvements are really that drastic. It would be pretty awesome.

**Comment by robwierzbowski** [comment]
Perf differences are huge between Ruby Sass and libsass. Around 3 sec to 0.3 sec IIRC. But libsass doesn't contain some basic language features (like @extends), and can't be extended with Compass or Compass plugins (which expose new Ruby based functions in Sass stylesheets). Most Sass users take features over speed in my experience, or switch to Stylus.

Nothing against adding libsass, just providing some background.

**Comment by sindresorhus** [comment]
What @robwierzbowski said.

I tried to get some comparison on it and more, but didn't get nay traction: https://github.com/h5bp/lazyweb-requests/issues/117

**Comment by eddiemonge** [comment]
This has been fixed in #238
