### ISSUE TITLE
Remove reference to Chrome Frame

### ISSUE THREAD

**Issue by theroux** [yeoman/generator-webapp_DEPRECATED#117]
Google is [retiring Chrome Frame in January 2014](http://blog.chromium.org/2013/06/retiring-chrome-frame.html)

Currently the conditional < IE7 comment links to both Browse Happy and Chrome Frame.

The Chrome Frame reference [has already been removed](https://github.com/h5bp/html5-boilerplate/blob/master/index.html) in HTML5 BP.

Also the x-ua-compatible meta tag should be changed from

``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

to

``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

This class should also be changed, although I do not believe it has any default styling.

``` html
<p class="chromeframe">
```

**Comment by passy** [comment]
:+1: We should try to stay as close to H5BP as possible.
