### ISSUE TITLE
Prompt for grunt-inline-css

### ISSUE THREAD

**Issue by passy** [yeoman/generator-webapp_DEPRECATED#119]
I would like evaluate if including [`grunt-inline-css`](https://github.com/jgallen23/grunt-inline-css) behind a prompt could be helpful. I think for mobile dev in particular this could be interesting, but we should collect some feedback first.

/cc @addyosmani

**Comment by stephenplusplus** [comment]
I just played with this for a tiny bit, and it seems pretty nice! Is there a way to target multiple files at once, as opposed to one-by-one .html paths?

One thought that came to mind is that this could allow us to create a 404.html page that is essentially just:

``` html
<html>
<head>
  (no inline styles)
</head>
<body>
    ** message **
</body>
</html>
```

With this tool, the styles could be borrowed from the actual app's CSS.

**Comment by addyosmani** [comment]
Tweeted about it earlier and the author seems up for changes if we have good recommendations. I think that the task could use a little fleshing out but otherwise up for putting it behind a prompt. 

@stephenplusplus asked your question [here](https://twitter.com/addyosmani/status/359733321665744900). We should prolly just ask him to jump on the thread :)

**Comment by stephenplusplus** [comment]
Sweet! The more I think about it, we would probably only need it to handle one file anyway, `dist/index.html`, since it would probably work best if `grunt-inline-css` were run as the last step. (I think) :)

**Comment by sindresorhus** [comment]
Can anyone argument for why it should be included (with reference to numbers and benefits)?

Keep in mind that the webapp generator is meant to be as generic as possible and inlining CSS can in many cases have the opposite effect.

**Comment by sindresorhus** [comment]
@addyosmani as for the multiple files things, that's just the normal grunt config and is the same for all tasks: http://stackoverflow.com/questions/15344584/grunt-0-4-less-task-how-to-not-concatenate-destination-files/15371443#15371443

**Comment by addyosmani** [comment]
My updated thoughts on this:

Generically inlining your CSS has questionable performs gains over relying on the cache for subsequent visits. Where it may have more quantifiable impact is inlining critical above-the-fold CSS, which (if under 14KB) should hit the user's machine with their first request.

I only thing this should be included as part of a broader effort to provide above-the-fold tooling and even then, it's probably an edge case for generator-webapp. I'd be inclined to close this issue unless someone has strong feelings against it.

**Comment by sindresorhus** [comment]
@addyosmani agreed. should probably start experimenting with above-the-fold on the mobile generator ;)
