### ISSUE TITLE
Adding test-framework attribute without equals sign returns error

### ISSUE THREAD

**Issue by jbeast** [yeoman/generator-webapp_DEPRECATED#120]
When executing `yo webapp --test-framework jasmine` the generator works until it tries to install jasmine. I receive the following from the console:

```
Error webapp --test-framework jasmine 

You don't seem to have a generator with the name true:app installed.
```

However, everything works fine if an equals sign is used i.e. `yo webapp --test-framework=jasmine`. I think the README needs to reflect this.

OSX 10.8.3

**Comment by passy** [comment]
That's definitely a bug, it should follow the general unix CLI conventions where it doesn't matter if you use an equal sign or not in between.

**Comment by kevva** [comment]
Maybe need to define it as a string? It's probably treated as a boolean now since that is the default.

**Comment by passy** [comment]
@kevva I think the problem is how we interact with `nopt`, which is responsible for the option parsing. If you don't provide `nopt` with a definition for the arguments, it treats long form arguments like `--test-framework` as flags: 

```
{ remain: [ 'jasmine' ],
     cooked: [ 'webapp', '--test-framework', 'jasmine' ],
     original: [ 'webapp', '--test-framework', 'jasmine' ] }
```

**Comment by sindresorhus** [comment]
That's weird behavior. Are you sure? It's easy to check that `webapp --test-framework jasmine` has a value.

**Comment by kevva** [comment]
@sindresorhus, it returns `true`.

> You don't seem to have a generator with the name **true:app** installed.

**Comment by sindresorhus** [comment]
Sounds like a nopt bug, I don't see why it shouldn't be able to automatically get the value. Anyone care to open a ticket over there?

**Comment by kevva** [comment]
It's not, I think, because all options are treated as booleans by [default](https://github.com/yeoman/generator/blob/master/lib/base.js#L125) if I'm not mistaken. Something like this could probably work:

``` js
this.option('test-framework', {
    type: String,
    defaults: 'mocha'
});
```

**Comment by passy** [comment]
> because all options are treated as booleans by default

Yup.

Would you snippet work within the generator? I saw this comment in `generator`:

``` js
  // Note: at some point, nopt needs to know about the generator options, the
  // one that will be triggered by the below args. Maybe the nopt parsing
  // should be done internally, from the args.
  env.run(args, opts);
```

(https://github.com/yeoman/yo/blob/d9c65b19147be7cc41b90e05deb4904eabc9b263/bin/yo#L94-L97)

**Comment by kevva** [comment]
Seems like it doesn't, same result. This would probably be a good idea yeoman/yo#56.

**Comment by eddiemonge** [comment]
snippet doesnt work. this should be closed here, the readme updated to include the equal for now and a similar ticket opened in generator or yo

**Comment by passy** [comment]
We can't fix that without rewriting the whole argument processing. Can't
look up what module we're using at the moment, but whatever it is, it
doesn't allow us to specify how arguments should be parsed at runtime.

**Comment by eddiemonge** [comment]
Readme has been updated to show the required equal sign. To make the equal sign not required is an upstream issue and should be filed as a bug in yo or generator. not sure which.
