### ISSUE TITLE
Add grunt-bower-install?

### ISSUE THREAD

**Issue by stephenplusplus** [yeoman/generator-webapp_DEPRECATED#121]
[grunt-bower-install](http://github.com/stephenplusplus/grunt-bower-install) seems to be performing well out there in the wild!

It's grown considerably, now doing deeper dependency matching and more accurate sorting. It also doesn't use `bower` internally anymore. `grunt bower-install:jquery` used to mask `bower install jquery --save`, but now, you just run `grunt bower-install` after installing/removing a Bower package, just like `grunt-bower-requirejs`.

Is it worth trying out `grunt-bower-install` if RequireJS isn't chosen by the user?

**Comment by passy** [comment]
All the pluses from me. It's incredibly useful, especially with nested
dependencies.
