### ISSUE TITLE
grunt build doesn't work when using coffeescript and require.js

### ISSUE THREAD

**Issue by gazliddon** [yeoman/generator-webapp_DEPRECATED#126]
grunt build doesn't work when using coffeescript and require.js

grunt server works fine

Versions used:

```
yo 1.0.0-rc.1.4
bower 1.1.1
npm 1.3.7
node 0.10.15
```

Steps to reproduce

```
mkdir coffeetest
cd coffeetest
yo webapp
```

Edit app/scripts/hello.coffee to be:

```
define (require) ->  
  console.log "'Allo from CoffeeScript!"
```

Alter app/scripts/main.js to include the following

```
require(['app', 'jquery', 'bootstrap', 'hello'], function (app, $, bootstrap) {
    'use strict';

// use app here

    console.log(app);
    console.log('Running jQuery %s', $().jquery);
});
```

This will work using grunt server. If you load the page @ http://localhost:9000 you will see "Allo from CoffeeScript!" appear in the console log of the browser as expected.

The issue is you can't build the app. If you grunt build then you get this error:

```
Running "requirejs:dist" (requirejs) task

Tracing dependencies for: main
Error: ENOENT, no such file or directory '/home/gaz/development/coffeetesst/app/scripts/hello.js'
In module tree:
    main

[Error: Error: ENOENT, no such file or directory '/home/gaz/development/coffeetesst/app/scripts/hello.js'
In module tree:
    main

    at Object.fs.openSync (fs.js:427:18)
]
```

Sorry in advance if this has already been reported. I saw something kind of similar but it was closed so I'm assuming this is either new or a different bug :)

**Comment by passy** [comment]
I'm afraid due to limitations in `r.js` and `grunt-contrib-requirejs` you can't CoffeeScript and `require.js` together easily. The problem here is that `.coffee` files get compiled into `.tmp/scripts/`, the `requirejs` grunt task expects a single path to look for those JavaScript files, though.

**Comment by gazliddon** [comment]
Well kind of. The issue is in the Gruntfile IMHO

It's not that bad to fix, I just did it on mine. I'm loath to submit a pull request as I'm really new to this stuff and have no idea about other ramifications it may have on the rest of the build process :)

What I'd at least suggest is that coffeescript and require.js support are at least made mutually exclusive when the generator boots up if it's not supported. I -looks- supported but took a while for me to find out.

**Comment by sindresorhus** [comment]
@gazliddon would help if you could gist your Gruntfile to show us how you worked around it ;)

**Comment by gazliddon** [comment]
Hiya

Sure. Be warned it's mucky though, I just did it to get my project building and it's pretty clear I'm a JS / Grunt naif :)

https://github.com/gazliddon/bacontest/blob/35572d6bdc8ec59e7e6bb9d499fdeddcef963b08/Gruntfile.js

Basically I made the requirejs step build from the .tmp staging dir for coffescript after all of the JS files from script to that directory

So I:
- Added a copy:bodge task
  - Copies app/*_/_.js to .tmp
  - Get's called before requirejs
- Change requirejs to run from the .tmp dir
- Added a copy:bower task
  - Copies requirejs into dist
  - Copies over a scripts I added outside of rjs (yeah I know :D)
  - Copies over png files, min renames these but I need the originals as they're name referenced in JS (yeah I know again :D )
- Removed uglify from build
  - Caused an error because of warning
  - So I took it out :D
  - Wasn't sure where the logs were, the build process doesn't report the warning

Hope that helps but at the core you need intermediate staging to do this kind of thing. If you convert the coffeescript in place in your scripts dir it means that gets polluted with JS and you don't want these in your dist dir either

**Comment by jaromero** [comment]
I would also like this to be improved, but I can see how complicated it would be.

My kludge however, mostly involved creating a new copy task ("copy:rjs") to copy the bower_components directory to .tmp, to let r.js see the scripts I'm trying to use. Then adjust the build task to make copy:rjs run _before_ requirejs (as well as making sure to run copy:dist instead of just copy near the end).

It feels like a hideous, dirty workaround, but it mostly works, and I'm able to keep the dist directory clean this way.

My Gruntfile: https://gist.github.com/jaromero/6236791

**Comment by addyosmani** [comment]
I would favor documenting the above workarounds in the mean time somewhere visible so that those running into issues with CS/Require at least have some options available until we fix this. Yeah?

**Comment by robwierzbowski** [comment]
Ran into this today. The two solutions I see mentioned are:
1. Stage `bower_components/**/*.js` to `.tmp`, run require task from `tmp`
2. Symlink `bower_components/` to `.tmp/bower_components`, run require task from `tmp`

2 seems cleaner, but possibly more fragile. Maybe a candidate for inclusion if Usemin 2.0 doesn't fix this.

**Comment by ghost** [comment]
I stumbled across an issue today. I built an app using `yo webapp --coffee` and when I run `grunt server`, I notice I don't get the "'Allo from CoffeeScript!" message, because hello.coffee is not referenced anywhere. Is this problem I've encountered related to this issue (#126)?

**Comment by robwierzbowski** [comment]
I've created an issue to address this on Usemin: https://github.com/yeoman/grunt-usemin/issues/195
