### ISSUE TITLE
generator-webapp wishlist

### ISSUE THREAD

**Issue by khalillechelt** [yeoman/generator-webapp_DEPRECATED#127]
- I would like to have the option to use Yahoo's Pure CSS instead of Bootstrap
- I'd like Grunt to automatically concatenate JS files with the main.js that sit in a new folder called js/modules. While not using Require.js.
- I'd like to use @necolas micro-clearfix mixin
- I'd like to add grunt-preprocess to the mix and an html folder in the app folder to be able to reuse html snippets for different HTML pages I am working on in the same project.
- I'd like to be able to choose to give the styles folder a SMURF/SMACSS folder structure with example files in it.
- I'd like the option to use Eric Mayer's [Susy](http://susy.oddbird.net/) with some simple pre configs.
- Option to use font-awesome would be cool

**Comment by addyosmani** [comment]
I'll comment on the first ask: we're exploring exposing options to choose Bootstrap, Pure CSS, Foundation or Topcoat for the first question as a part of `generator-mobile` (which may at some point make it's way back to -webapp).

The problem with doing this as a default is it exposes a _great_ deal of complexity to how we automatically wire up an app (none of the above solutions are consistent in structure, layout, boilerplate, performance). 

It also runs the risk of giving developers choice paralysis when all they want to do is get started with a project. One could argue that if one wants to start a new Pure CSS project, using `generator-pure` would be a better starting point.

cc'ing in @passy and @stephenplusplus for their thoughts here as I know you've spoken to Sindre already.

**Comment by passy** [comment]
> I would like to have the option to use Yahoo's Pure CSS instead of Bootstrap

Agreed with all what Addy said.

> I'd like Grunt to automatically concatenate JS files with the main.js that sit in a new folder called js/modules. While not using Require.js.

Could you elaborate? If you just want to concatenate files, you can either use `usemin` or extend the `concat` task in the Gruntfile.

> I'd like to use necolas micro-clearfix mixin

What's preventing you from doing this?

> I'd like to add grunt-preprocess to the mix and an html folder in the app folder to be able to reuse html snippets for different HTML pages I am working on in the same project.

I think this use-case is too rare to make it an default for everyone. After all, `generator-webapp` should serve as a solid base, not a kitchen sink. I'm for instance using Jade in one project of my own to include snippets and while it's certainly super useful and I like it, I still don't think it's a good fit as default.

> I'd like the option to use Eric Mayer's Susy with some simple pre configs.

`bower install susy` should be enough.

> Option to use font-awesome would be cool

Also installable via bower.

**Comment by khalillechelt** [comment]
Thanks for your responses @passy and @addyosmani.

I totally get what you guys are saying.

And @passy: of course I can add all these things myself by hand that's precisely what I am doing every time I am using generator-webapp. And that is my problem. I'd love to have a generator that just spills in my desired config or at least gives me the option.

My original question to @sindresorhus was: if I want more options in the generator do I send a PR or do I fork and write my own?

So from what you are saying I would suspect if I want my own opinionated version of generator-webapp with slight chnges I have to fork and extend I guess?

**Comment by khalillechelt** [comment]
Maybe there should be some sort of easy way to create 'flavors' of generators?

**Comment by sindresorhus** [comment]
@kahlil yeah, looks like forking is your best option. I wanted you to add it here so we could discuss if anything could be included upstream.

Making it easier to customize generators is something we want to be better at, but it's a hard problem since there are so many factors, especially with the build-system. Currently any way I think it could work just ends up as a big complicated clusterduck...

Any suggestions welcome! ;)

**Comment by khalillechelt** [comment]
Got it, thanks.

If I stumble on some genius idea to make generators extendable I'll let you know :D

**Comment by passy** [comment]
> If I stumble on some genius idea to make generators extendable I'll let you know :D

Yes, please do! :)
