### ISSUE TITLE
Installing generator-webapp globally failed

### ISSUE THREAD

**Issue by bcgov** [yeoman/generator-webapp_DEPRECATED#129]
When running npm install -g generator-webapp on Windows, I got error
npm ERR! Error: ENOENT, open 'C:\Users\xxx\AppData\Roaming\npm\package.json'
There is no file package.json in that folder.

**Comment by passy** [comment]
This is an error in your npm setup. Try installing npm from scratch following the guides you find on http://nodejs.org/.

**Comment by bcgov** [comment]
But all other npm global packages were installed successfully...

**Comment by passy** [comment]
Try running `npm cache clean`.
