### ISSUE TITLE
Better document what this generator includes in the readme

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp_DEPRECATED#130]
- Defaults (e.g Autoprefixer)
- Compass, CoffeeScript, RequireJS, other options
- Testing etc.

**Comment by passy** [comment]
- bower install

**Comment by sindresorhus** [comment]
- `grunt bower` and `grunt bower-install`

**Comment by addyosmani** [comment]
`grunt bower`?

```
$ grunt bower
Warning: Task "bower" not found. Use --force to continue.

Aborted due to warnings.

Elapsed time
Total  859ms
```

`grunt bower install` etc. had similar output. What does `grunt bower` do again?

**Comment by addyosmani** [comment]
Would this be sufficient for the latter?

Install a Bower component:

```
bower install backbone --save
```

Call the Grunt task:

```
grunt bower-install
```

You're in business!

```
<!-- bower:js -->
<script src="bower_components/backbone/backbone.js"></script>
<!-- endbower -->
```

(just for testing) all seems okay.

```
$ bower install backbone --save
bower cached        git://github.com/components/jquery.git#2.0.3
bower validate      2.0.3 against git://github.com/components/jquery.git#>=1.8.0
bower cached        git://github.com/components/jquery.git#2.0.3
bower validate      2.0.3 against git://github.com/components/jquery.git#~2.0.3
bower cached        git://github.com/documentcloud/backbone.git#1.0.0
bower validate      1.0.0 against git://github.com/documentcloud/backbone.git#*
bower install       jquery#2.0.3

jquery#2.0.3 app/bower_components/jquery
addyo at dhcp-172-16-23-146 in ~/projects/test-webapp
$ grunt bower-install

Running "bower-install:app" (bower-install) task

Done, without errors.

Elapsed time
bower-install      506ms
bower-install:app  24ms
Total              530ms
```

and it's correctly wiring up the index.

**Comment by addyosmani** [comment]
Is there a reason we opted not to document `yo webapp --skip-welcome-message` etc?

**Comment by sindresorhus** [comment]
@addyosmani `grunt bower` only works when you select RequireJS. It does the same thing as bower-install, but in the RequireJS config.

About the flags. As we discussed in hangout. I'd prefer it if we don't document them as we should rather come up with a better solution.

**Comment by addyosmani** [comment]
Readme captures this better now.
