### ISSUE TITLE
Opening <html> tag is missing in test runner index.html

### ISSUE THREAD

**Issue by hashchange** [yeoman/generator-webapp_DEPRECATED#133]
In test/index.html, the opening `<html>` tag is missing. I haven't been able to find the corresponding template, though.

**Comment by hashchange** [comment]
Ok, I have found it. It's in generator-mocha and has apparently been [fixed two months ago](https://github.com/yeoman/generator-mocha/pull/5), but has not made its way into a release.

**Comment by sindresorhus** [comment]
Release will happen very soon.

**Comment by passy** [comment]
@hashchange Just out of curiosity, why do you care? You don't need the `<html>` tag for a valid HTML5 document.

**Comment by hashchange** [comment]
@sindresorhus Good to know, thanks.
@passy Fair enough. But here, it is just the _opening_ tag which is missing. The closing `</html>` tag is there alright. Perhaps I should have made that a little clearer ;)

**Comment by passy** [comment]
@hashchange You don't need the opening tag either. I actually like leaving those off for single-purpose documents like the that one.
