### ISSUE TITLE
Upgrade to Bootstrap 3

### ISSUE THREAD

**Issue by passy** [yeoman/generator-webapp_DEPRECATED#134]
http://blog.getbootstrap.com/2013/08/19/bootstrap-3-released/
- [x] Bump revision
- [x] Update references to plugins
- [x] Update markup
- [x] Make sure Glyphicons work
- [ ] Eat popsicles :dango:

**Comment by addyosmani** [comment]
:+1: Happy for us to delay the release until this is in (depending on sass timeline).

https://github.com/components/bootstrap needs to be updated to bootstrap 3 final.

**Comment by addyosmani** [comment]
Layouts: do we opt for starter, jumbotron, narrow jumbatron or try to offer choices? http://getbootstrap.com/getting-started/#examples

**Comment by passy** [comment]
I think narrow jumbotron would fit nicely.

We will probably have to wait for an updated sass conversion, though ...

**Comment by addyosmani** [comment]
Narrow jumbotron works for me. @sindresorhus? 

It's probably worth us pinging the author of the sass port to see what their timeline is. If it's going to take a great deal longer, we may want to ship BS3 support as a 1.x feature instead.

**Comment by sindresorhus** [comment]
narrow
