### ISSUE TITLE
Public directory for static content

### ISSUE THREAD

**Issue by ErikEvenson** [yeoman/generator-webapp_DEPRECATED#143]
Right now, the generator puts index.html and all of the server files at `/app` -- assuming that the entire app will be served up as a static site.  If the generator is being used to bootstrap a web application though, it is likely that there will be some files that are not appropriate for serving.  This makes using something like `app.use(express.static(__dirname));` problematic.  Altering the generated files is possible, but is non-trivial.

Would it not be better to give an option to structure the files in `/app` to have a subdirectory, say `/public`, that would allow an easier transition to a web app that does more than just serve static content?  Then the server could just use, say, `app.use(express.static(path.join(__dirname, 'public')));`.

Thanks for the great tool and forgive me if there is a better way to do this -- I am climbing the learning curve on yeoman and all these fancy js frameworks...  ;)

**Comment by addyosmani** [comment]
My position on this is that there are going to be directory structure and filename changes that different web application frameworks may ideally desire from generator-webapp and it's not it's place par se to adapt to fit them all - it simply can't. 

Instead, I would see those frameworks (eventually) consuming generator-webapp and making naming changes after an initial scaffold. E.g `yo express` -> includes generator-webapp as part of scaffolding -> rewrites directory structure to fit the needs of an Express user.

Someone correct me if I'm looking at this wrongly.

**Comment by ErikEvenson** [comment]
That's fair.  I looked at some of the other generators and that does seem to be the approach.  I suspect I will need to ultimately fork/write a generator that makes these kind of changes if I really to depart from the "yo way of doing it."

Cheers!
