### ISSUE TITLE
Default settings mocha failure

### ISSUE THREAD

**Issue by thewalkingtoast** [yeoman/generator-webapp_DEPRECATED#146]
I am having a similar problem to #140. No images in my app yet. Fresh install of yeoman and generator-webapp. It works for about an hour, then dies. I can revert my project back to a git commit that it worked and it still dies. (May be something not committed in my local FS then?).

I added some bower components, added some style sheets including some custom fonts. I followed the path in the generated Gruntfile and put my fonts in `app/styles/fonts`. Removing them doesn't change.

I have not changed anything in the `tests` folder.

I can see it's a spawn call that dies, but being new to Node, not sure how to trace it further than that.

`grunt server` works fine.

Edit: I tried downgrading imagemin to 0.1.4 as suggested and that did not help. I am not using images yet either so unsure how that would help.

OSX 1.8.2 w/X11
ruby 2.0.0p247
compass 0.12.2
Node v0.10.17
npm 1.3.8
yo 1.0.3
bower 1.2.4
grunt-cli v0.1.9
grunt v0.4.1

.gitignore =

```
.DS_Store
dist
.tmp
.sass-cache
```

```
$ ⇒ grunt test
Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "concurrent:test" (concurrent) task

    Running "coffee:dist" (coffee) task

    Running "coffee:test" (coffee) task

    Done, without errors.

    Elapsed time
    coffee       508ms
    coffee:test  10ms
    Total        518ms

    Running "copy:styles" (copy) task
    Copied 6 files

    Done, without errors.

    Elapsed time
    copy:styles  518ms
    Total        518ms

Running "autoprefixer:dist" (autoprefixer) task
File ".tmp/styles/bootstrap.css" created.
File ".tmp/styles/font-awesome.min.css" created.
File ".tmp/styles/landing.css" created.
File ".tmp/styles/main.css" created.
File ".tmp/styles/plugin.css" created.
File ".tmp/styles/theme.css" created.

Running "connect:test" (connect) task
Started connect web server on localhost:9000.

Running "mocha:all" (mocha) task
Testing: http://localhost:9000/index.html

/Users/Adam/Sites/webapp/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by passy** [comment]
You appear to not have `compass` on your `$PATH`.

**Comment by thewalkingtoast** [comment]
Good thinking but nope, it's there.

**Comment by thewalkingtoast** [comment]
It looks like this has something to do with mocha instead of compass.

`grunt-compass` works fine, but `grunt mocha` throws the error.

Edit: I can also remove the mocha task from the Gruntfile and proceed without error.

**Comment by thewalkingtoast** [comment]
I figured it out. It is in grunt-mocha. Or rather, it's dependency on Obvious/phantomjs. When this npm module is installed, it takes a system absolute path to the phantomjs binary it bundles along with itself.

On OSX, executing the following:

```
cd ~ && mkdir webapp
cd webapp
yo webapp
...
```

This will create a hardcoded path in
`webapp/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js`
to the hard-coded absolute path of
`/Users/Adam/webapp/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs`

This prevents the webapp folder from being moved from this location (in my case, my home directory where I first generated the app but then moved it).

This issue already exists with the responsible repository:
https://github.com/Obvious/phantomjs/issues/97
