### ISSUE TITLE
webapp build errors

### ISSUE THREAD

**Issue by billyoncetoldme** [yeoman/generator-webapp_DEPRECATED#147]
updated yo to 1.0.4 on two of my 3 machines.  
am getting the below string of errors when running yo webapp.  (apologies is this a novice mistake on my part)  both mac, one an intel mac tower running 10.7.5, the other a newer imac running 10.8.4.  updated as many things as i could think of to remedy.  performed permissions repair.  
Older version of yeoman is working perfectly on my macbook air.  However, projects i have been working on that i have synced to all three machines will not employ the grunt server command.  Grunt seems to be the glaring issue.  
Thanks in advance.
npm WARN package.json web@0.0.0 No description
npm WARN package.json web@0.0.0 No repository field.
npm WARN package.json web@0.0.0 No README data
npm ERR! Error: EACCES, open '/Users/billyoncetoldme/.npm/2cc6dac2-grunt-contrib-uglify-0-2-0.lock'
npm ERR!  { [Error: EACCES, open '/Users/billyoncetoldme/.npm/2cc6dac2-grunt-contrib-uglify-0-2-0.lock']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/billyoncetoldme/.npm/2cc6dac2-grunt-contrib-uglify-0-2-0.lock' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/billyoncetoldme/Desktop/web
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR! path /Users/billyoncetoldme/.npm/2cc6dac2-grunt-contrib-uglify-0-2-0.lock
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/Users/billyoncetoldme/.npm/2cc6dac2-grunt-contrib-uglify-0-2-0.lock'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/billyoncetoldme/Desktop/web/npm-debug.log
npm ERR! not ok code 0

**Comment by sindresorhus** [comment]
npm issue not us. post there instead.
