### ISSUE TITLE
Installation works but generator isn't found by yo

### ISSUE THREAD

**Issue by PaulMougel** [yeoman/generator-webapp_DEPRECATED#148]
The  `generator-webapp` installation works fine in npm, but Yeoman doesn't seem to find it.

```
$ sudo npm install -g generator-webapp
[…]
generator-webapp@0.4.1 /usr/local/lib/node_modules/generator-webapp
├── cheerio@0.12.1 (entities@0.3.0, underscore@1.4.4, htmlparser2@3.1.4, cheerio-select@0.0.3)
└── yeoman-generator@0.13.4 (dargs@0.1.0, diff@1.0.5, debug@0.7.2, text-table@0.1.1, mime@1.2.11, async@0.2.9, mkdirp@0.3.5, isbinaryfile@0.1.9, rimraf@2.2.2, chalk@0.2.1, shelljs@0.1.4, underscore.string@2.3.3, iconv-lite@0.2.11, tar@0.1.18, glob@3.2.6, request@2.25.0, findup-sync@0.1.2, lodash@1.3.1, inquirer@0.3.1)
```

```
$ yo webapp
Error webapp 

You don't seem to have a generator with the name webapp installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.
```

and it doesn't show indeed in `yo --help`. Any idea?
Mac OS 10.8.4, npm v1.3.9 ; node v0.10.17 ; yo v1.0.4

I tried https://github.com/yeoman/yeoman/issues/1008 but this doesn't fix the issue.

**Comment by passy** [comment]
Maybe you have different prefixes for your root and normal user. That's one reason why I strictly advice against using `sudo`. Maybe this answer on SO could be helpful: http://stackoverflow.com/questions/18212175/npm-yo-keeps-asking-for-sudo-permission/18277225#18277225

**Comment by PaulMougel** [comment]
Indeed, your SO answer fixed it! Thanks a lot.
