### ISSUE TITLE
New Glyphicons aren't copied during build

### ISSUE THREAD

**Issue by passy** [yeoman/generator-webapp_DEPRECATED#149]
As it turned out my idea to just reference the fonts from the `bower_components` wasn't that smart, because during the build the `bower_components` aren't copied over. 

There are two options to fix this, which I both don't really like:
- Copy the fonts during the generation from `bower_components` to `app/styles/fonts`
- Add a copy task to the Gruntfile _if bootstrap is enabled_ that copies either the whole `sass-bootstrap` folder or just the font files during the build step.

I think I dislike the first option more, because there's a chance that the fonts and styles go out of sync during an update to Bootstrap.

Any ideas how to improve this?

**Comment by sindresorhus** [comment]
I would go with option 2.

**Comment by addyosmani** [comment]
I like option 2 as well. I think I favor pulling in just the font files during the build step. Was there a particular reason you wanted to copy all of `sass-bootstrap`?.

**Comment by sindresorhus** [comment]
Just fonts

**Comment by edouard-lopez** [comment]
+1 for second proposition as it sounds more _grunt-ish_ (others tasks already manage others files' format).

**Comment by passy** [comment]
The idea with copying over the whole folder was to allow dynamic loading of
other components like the JS. But I guess that would be very easy to add
manually if needed and would just cause unnecessary bloat for everyone else.

So option 2 with fonts folder only it is. :)

**Comment by jeroennoten** [comment]
It goes still (or again) wrong: I did a new installation today and after building, the font files now are copied to <code>dist/bower_components/bootstrap/dist/fonts</code>. And the css file refers to <code>../fonts</code>.

It seems that this can be fixed by copying the bootstrap font files separately and set the <code>cwd</code> and <code>dest</code> to something deeper:

<pre>
...
                }, {
                    expand: true,
                    dot: true,
                    cwd: '<%= yeoman.app %>/bower_components/' + (this.includeCompass ? 'sass-' : '') + 'bootstrap/' + (this.includeCompass ? '' : 'dist/'),
                    dest: '<%= yeoman.dist %>/styles',
                    src: [
                        'fonts/*.*'
                    ]
                }]
...
</pre>

**Comment by vanduc1102** [comment]
when i run $grunt build
i checked vendor.css and found
url(/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff) format('woff'),
url(/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf) 
Why we have that.
I just only want it like:
url(bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff) format('woff'),
url(bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf) 

If it look like that.
I just need to add a task copy all fonts to
dist/
-------styles/
--------------vender.css
--------------bower_components/bootstrap/dist/fonts/
