### ISSUE TITLE
use grunt-newer

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp_DEPRECATED#151]
This an essential missing piece in grunt. Luckily for us @tschaub created a task to only run tasks on changed files.

https://github.com/tschaub/grunt-newer

I did a quick test and looks like it would bring our build time from 10s to 2s. Though a much more important place for it is with `grunt server`.

**Comment by passy** [comment]
This looks amazing! :+1:

**Comment by sindresorhus** [comment]
@tschaub would you be interested in doing a PR to integrate your task?

**Comment by tschaub** [comment]
Gladly @sindresorhus.

Question about the setup though.  With [bower@c87f049](https://github.com/bower/bower/commit/c87f0495c00e03b4072c657549d1612707cec3a8), [generator-webapp@a89b280](https://github.com/yeoman/generator-webapp/commit/a89b2800366a62ea07f03e424104403dd532e9cf), and [generator-mocha@dfcdacc](https://github.com/yeoman/generator-mocha/commit/dfcdacc3a20cd6818b9e3c05d9c0332b26ad791c) I end up with mocha and chai in `test/app/bower_components` (given what is in [`.bowerrc`](https://github.com/yeoman/generator-webapp/blob/master/app/templates/bowerrc#L2)), but the `test/index.html` [expects them](https://github.com/yeoman/generator-mocha/blob/dfcdacc3a20cd6818b9e3c05d9c0332b26ad791c/lib/templates/index.html#L11) at `test/bower_components`.

This leads to the following on `grunt test`:

```
Running "mocha:all" (mocha) task
Testing: http://127.0.0.1:9000/index.html

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.
```

I can edit my way out of this, but I was wondering if there was a specific version mix that I should be using.

**Comment by sindresorhus** [comment]
> end up with mocha and chai in test/app/bower_components (given what is in .bowerrc), but the test/index.html expects them at test/bower_components.

We [load the `app` folder](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L74) too when you run the tests, so it tries the `app` folder if `bower_components` isn't found in `test`.

> I can edit my way out of this, but I was wondering if there was a specific version mix that I should be using.

I saw that the other day too. Looks like a bug.

**Comment by addyosmani** [comment]
Confirmed as a bug. Would love to get grunt-newer support in once it's been resolved.

**Comment by CaseyLeask** [comment]
Has anyone raised an issue for it? I'd love to see `grunt-newer` in `generator-webapp`.

**Comment by sindresorhus** [comment]
@tschaub still interested? this would be huge perf wise, and give your task a lot of usage ;)

**Comment by tschaub** [comment]
@sindresorhus sure, I'll dig into this again.

I'm still seeing test failures because of the custom `.bowerrc` (`generator-mocha` expects components in `./bower_components` relative to `index.html`, but the `generator-webapp` Bower config makes them go in `./app/bower_components`).  yeoman/generator-mocha#10 proposes one solution.  Alternatives would be to use Bower's own logic for determining the path to the components dir or to not include a `.bowerrc` in this generator.

See also #192 - a trivial change to get the default `grunt` task passing in generated webapps.

**Comment by sindresorhus** [comment]
@tschaub can you ignore the failure for now? we're probably going to drop the .bowerrc

**Comment by tschaub** [comment]
(The GitHub API won't let me turn this issue into a PR - see #193)

I'm probably missing something, but unfortunately I don't see a _ton_ of room for speeding things up here because of the clean tasks.  @sindresorhus let me know if you had other tasks in mind - I'll keep poking around.
