### ISSUE TITLE
yeomanConfig.app vs. <%= yeoman.app %>

### ISSUE THREAD

**Issue by robwierzbowski** [yeoman/generator-webapp_DEPRECATED#154]
Some parts of the gruntfile use underscore templating with [yeoman.app](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L26) while others reference the [yeomanConfig](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L65) object directly. Can someone explain to me the reasoning for each?

**Comment by sindresorhus** [comment]
It goes back to before grunt supported templates in options. Should be fixed now. PR?

**Comment by robwierzbowski** [comment]
Sure, one sec.
