### ISSUE TITLE
Rev favicon, add apple-touch-icon?

### ISSUE THREAD

**Issue by robwierzbowski** [yeoman/generator-webapp_DEPRECATED#156]
Two parts here:

There's no apple-touch-icon in the repo. H5BP is switching to providing one 150px icon by default. Should the generator do the same?

The generator follows H5BP and lets the browser automatically find favicon.ico (and apple-touch-icon-precomposed.png if it's included). But if we link them in the `head` we can rev them, which would be nice.

If people want either of these I'll write a PR.

**Comment by sindresorhus** [comment]
Sure

**Comment by robwierzbowski** [comment]
OK. PRs after the Usemin issue is resolved.

**Comment by sindresorhus** [comment]
ping

**Comment by eddiemonge** [comment]
double ping

**Comment by robwierzbowski** [comment]
Sorry, haven't had a chance to look at this. Keep the issue closed, I'll
take a quick look tonight and see if the regex still ignores the favicon,
and if so check the usemin queue for issues.

On Tuesday, February 4, 2014, Sindre Sorhus notifications@github.com
wrote:

> Closed #156 https://github.com/yeoman/generator-webapp/issues/156.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/156
> .

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com
