### ISSUE TITLE
Bus error: 10 on OS X 10.9 DP7

### ISSUE THREAD

**Issue by oskarrough** [yeoman/generator-webapp_DEPRECATED#157]
Hi, I realize I'm running a developer preview 7 of OS X 10.9 but before I roll back to 10.8 I wanted to see if there's a fix to the following error. When a change is detected, the watch task breaks my 'grunt server' with the following:

```
Running "watch" task
Waiting...Bus error: 10
```

Any ideas of where to look? Let me know if I can supply more information about my setup. It's the 0.4.2 version of generator-webapp.

**Comment by sindresorhus** [comment]
You should probably post over at grunt-contrib-watch ;)

Also include more info, like your Gruntfile, node version, etc.

**Comment by oskarrough** [comment]
Of course, thank you.

Opened at https://github.com/yeoman/generator-webapp/issues/157

**Comment by mavfly** [comment]
Anybody know how I can fix it?

**Comment by oskarrough** [comment]
Yea, check the issue above https://github.com/yeoman/generator-webapp/issues/157. You have to update node to 10.21.

**Comment by midlantica** [comment]
Thanks!

**Comment by creativesands** [comment]
I started getting error after including bootstrap in my project. When i remove bootstrap.css from the project, it works fine.
