### ISSUE TITLE
Build with Requirejs missing modules folder

### ISSUE THREAD

**Issue by justinboyd** [yeoman/generator-webapp_DEPRECATED#162]
First I want to say thank you for Yeoman, it's amazing!

I came across an issue in my webapp builds since upgrading to v1.0.4. When building a fresh webapp project with requirejs I receive an error prompting me with a 404 error. The folder '/modules' and the containers file 'main.js' were missing from the build. Once I added the folder and file the error was gone.

Win 7 32-bit

**Comment by sindresorhus** [comment]
RequireJS support has been removed. It bloated the generator and none of us use it so we can't provide a good service for it. I'm sure the community will fork generator-webapp and make generator-webapp-rjs ;)

https://github.com/yeoman/generator-webapp/commit/f53d0d49e2f8c334494d782e6620f6c4bf36d41d

**Comment by justinboyd** [comment]
Sounds good, thanks for everything!
