### ISSUE TITLE
Fatal error: Port 9000 is already in use by another process

### ISSUE THREAD

**Issue by zeroxme** [yeoman/generator-webapp_DEPRECATED#166]
I grabbed the latest version and i get this message all the time "Fatal error: Port 9000 is already in use by another process" in the connect:test task

changing the port doesn't fix the issue!

Running OS X mountain lion and yeoman 1.0.4

**Comment by passy** [comment]
It does. You can figure out which application uses that port through `netstat -alnp | grep 9000` for example.

Ongoing discussion about preventing this is in https://github.com/yeoman/yeoman/issues/1170

**Comment by duncanfinney** [comment]
I know this issue is closed, but I just thought I'd leave this here in case someone ever comes across this page on google. 

Very easy tool that lets you kill the process right from the app: http://technet.microsoft.com/en-us/sysinternals/bb897437.aspx

**Comment by zeroxme** [comment]
@duncanfinney @passy thanks guys
