### ISSUE TITLE
Make generator-webapp more lean

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp_DEPRECATED#168]
One of consistent pieces of feedback we've had is that this generator is a little too heavy. Let's try to fix that :haircut: 

Summarizing some of what our users have said:
- I would have liked the option to just use Bootstrap's CSS without Sass
- I almost never use CoffeeScript support
- I only use RequireJS with a framework generator
- It's difficult to understand the Gruntfile generated. There's too much going on and there are few comments that explain what you've created for me. I don't feel what this generator does is adequately documented (e.g how should automagical wiring be used?).

Progress:
- 4c932802eafc44d932bbc7b83fcf5128c1a6be73 made Coffee optional :+1: 
- #114 suggests making Compass optional as well. I second this.

Ideas:
- Drop RequireJS support from the generator or move it to a flag, similar to coffee. Perhaps `--requirejs`. 
- Ask users if they would like to just use (compiled) Bootstrap CSS rather instead of Sass Bootstrap. 
- Make users more aware of `generator-gruntfile` `generator-gruntplugin` and the other projects which can help them create their own leaner Grunt starts. Maybe via `yo`?
- Offer a way to get richer comments for the Gruntfile or document this as part of the wiki. I personally prefer code-comments as they encourage that all changes come with them, but we can just document if the team feel strongly that is the right call.

Any other ideas?

cc @sindresorhus @passy @stephenplusplus @sboudrias @kevva

**Comment by addyosmani** [comment]
Another point of reference: some users feel something like http://getfireshell.com/ would be a better starting point. I feel we could offer a better solution to this once we've trimmed down on the fat a little more.

**Comment by kevva** [comment]
+1 for dropping support for requirejs, better code comments and making Compass optional (I'd like to get rid of it altogether).

**Comment by stephenplusplus** [comment]
> Offer a way to get richer comments for the Gruntfile or document this as part of the wiki. I personally prefer code-comments as they encourage that all changes come with them, but we can just document if the team feel strongly that is the right call.

I fully agree we need to document why we made the Gruntfile the way we made it. I also agree that nothing beats inline code comments as being helpful. However, I have two concerns with that for this particular case:

1) It would be huge. If our Gruntfile is scary now, it'll be really scary when someone feels like we accidentally named a word document "Gruntfile.js".

2) Instead of approaching this type of help from the angle of "Here's how we connect _grunt-task-1_ to _grunt-task-2_ in `generator-webapp`", which won't help any of our other generators, we can instead abstract the what, how, and where of each grunt task to a wiki post, and share that link at the top / throughout the Gruntfile.

**Comment by sindresorhus** [comment]
It's funny how this actually was lean, but we were "bullied" by users into bloating it up and now they want it lean again.

But ya, huge :+1: to all of this.

> Drop RequireJS support from the generator or move it to a flag, similar to coffee. Perhaps --requirejs.

I would favor dropping it and rather have a separate generator-webapp-rjs maintained by someone in the community actually using RequireJS. Supporting it mean having ifdefs in all the places.

> Offer a way to get richer comments for the Gruntfile or document this as part of the wiki. I personally prefer code-comments as they encourage that all changes come with them, but we can just document if the team feel strongly that is the right call.

I'd say we go for some kind of Docco style. I like the one we used on the Traceur todomvc app.

All tasks should have an explanation how they works and what they do and a link to the task, at minimum.

Then have a prompt to ask "Do you want the Gruntfile with comments". And if no, just strip them.

**Comment by addyosmani** [comment]
> I would favor dropping it and rather have a separate generator-webapp-rjs maintained by someone in the community actually using RequireJS. Supporting it mean having ifdefs in all the places.

:+1: 

I also like the idea of going for Docco style comments as in the Traceur app. Big plus one to the prompt for Gruntfile comments.

**Comment by addyosmani** [comment]
For Bootstrap CSS, how should we handle this?
- Break the current prompt into two prompts - 1) ask if you'd like Bootstrap, 2) if so, ask if you want just CSS or Sass/Compass
- Introduce a new (pure) CSS prompt in addition to the Sass prompt
- Make pulling in Bootstrap CSS the default for the prompt and only pull in Sass if you pass a flag
- Other?

**Comment by kevva** [comment]
I'm fine with either alternative one or two. Alternative one is a little bit nicer but it also involves an extra step but that shouldn't be too bad imo.

**Comment by addyosmani** [comment]
Hmm. Wait - why aren't we just calling out to generator-bootstrap for that step? 

```
$ yo bootstrap
[?] In what format would you like the Twitter Bootstrap stylesheets? (Use arrow keys)
❯ css
  sass
  less
  stylus
```

**Comment by passy** [comment]
@addyosmani The problem there was, IIRC, that the template relies on the choice the user makes in this dialog, because at the very least the paths, sometimes the files that need to be included vary based on the selection. We would at least need a response back from the bootstrap generator to adjust those after it is done.

**Comment by addyosmani** [comment]
Thanks for explaining @passy. I wonder how feasible it would be for us to try getting back such a response from the generator. A hack would be including the logic from generator-bootstrap directly inside -webapp, but it would be a lot more ideal to be able to reuse an existing generator in a more composable fashion. Wonder how hard it would be to achieve pre the 2.0 redesign.

**Comment by SBoudrias** [comment]
Maybe just using the env? `this.env.run("bootstrap", { /* cmd arguments */ });` (May need adjustement to the Bootstrap generator though)

**Comment by eddiemonge** [comment]
How about making bootstrap itself optional? I always felt like that was bloatware.

Would it be more scary if each piece of the grunt file config was split into its own file in a folder like grunt.d or grunt-config?

**Comment by davemo** [comment]
I don't have much to add here except a huge :+1:, glad to see you guys are listening to user feedback about the size of the Gruntfile and attempting to pare things down.

**Comment by eddiemonge** [comment]
@davemo PR's welcome hehe. You could pull in some lineman idealogies.   ps: i feel like you are stalking me now.

**Comment by mrtnbroder** [comment]
+1 for moving requirejs to the flag --requirejs. But I'd not drop the support for it, as I really like working with it.

**Comment by b-long** [comment]
@addyosmani @sindresorhus @yeoman Please don't remove the RequireJS support entirely!  Isn't one of the goals of Yeoman & Grunt to move the broader JS development workflow forward?  There are so many organizations today stuck writing non-modular JavaScript, using poor build tools, lacking testing, etc.  I think we as the community of JS developers _need_ something pushing us toward more sophisticated software engineering practices.  The Grunt community (which is wonderful) is already so fractured and trying to keep track of what might be considered the current industry standard configuration of a build that includes concatenation, minification, linting and automated test is already so difficult.

I realize that there's some desire here to keep the `generator-webapp` codebase simple and I completely support that effort, but shouldn't we be more concerned with recommending best practices in projects that use `generator-webapp` as a starting point at the expense of complexity internal to `generator-webapp` ?  I'm hoping, for example, that `generator-webapp` will continue to be a reference to current best practices and in the future, we might see it recommend that users prefer Harmony modules over AMD/RequireJS.

**Comment by Sinetheta** [comment]
Wow, I'm sad to see requirejs gone. What were people using this for if not sophisticated projects?

That's a lot of manual shimming I'm going to have to do now; has anyone created a sub-generator yet to pick up the slack?

**Comment by davemo** [comment]
@Sinetheta requirejs !== sophistication; it's also not the common case for people building webapps and not needed to get a web app rolling out of the gate. It adds significant complexity to unit testing setup and other areas of web application development lifecycle. I think what the @yeoman team is doing here is the right thing; supports the common case of not using requirejs, and still allows those who want to use it to do so with the flag.

**Comment by Sinetheta** [comment]
@davemo Sure, but when performing an organ transplant you usually wait for a heart to become available before removing the old one.

It was this very generator which introduced me to the idea of AMD. So if using it is now seen to "complicate unit testing", then what's the suggested way to modularize a codebase. Because monkey patching this thing back together [is proving to be a nightmare](https://github.com/yeoman/grunt-usemin/issues/192).

**Comment by davemo** [comment]
@Sinetheta how big is your codebase for the app you are using AMD in? Can you not just keep using the locked version of the generator-webapp that supported requirejs or use the flag that will be enabled going forward? 

Many large apps don't use AMD, or any module format at all. Many people are just [waiting until ES6 lands before investing in modules](http://blog.testdouble.com/posts/2013-06-16-unrequired-love.html). You can go a long way using concatenation and smart utilities like [extend.js](https://github.com/searls/extend.js/) that make namespacing much less dependent on load order.

I wouldn't consider the defaults that are provided in the grunt plugin configurations are in any way representative of best practices; it's too subjective a thing to hope to achieve in one utility belt like Yeoman. Opinions and examples are the best way I would describe them.

**Comment by Sinetheta** [comment]
Thanks @davemo, that's the kind of nudge I was hoping for.

I understand that best practices are subjective, which is why it's nice for us js mortals to be able to do a little imitation until we have the experience to make an informed decision :wink:

**Comment by davemo** [comment]
You are well ahead of the curve if you're using tools like Yeoman and Grunt @Sinetheta, keep experimenting and learning :)

**Comment by soswow** [comment]
Ok. Now I confused. 

Simple question - why list "What more would you like?" doesn't contain coffeescript option? If you think minority use it - then make it deselected by default. I mean why coffee, (and compass in the future) should be selected with flag `--coffee` and Modernizr don't? I use coffee all the time, most of the time I use compass and I don't care about modernizr.

Also when I start from just `yo` and select Webapp generator from the list I can't put flag `--coffee`

**Comment by yhpark** [comment]
I've been confused for several days with no requirejs support after seeing 'out-of-the-box requirejs support' on the website.
So can anyone tell me how can I scaffold with requirejs now? It seems there is no '--requirejs' option.

**Comment by addyosmani** [comment]
It appears in f53d0d49e2f8c334494d782e6620f6c4bf36d41d Sindre removed
RequireJS support for generator-webapp so it currently isn't available
behind a flag to the best of my knowledge. Our current guidance there is to
select a generator for the framework you are using and use its RequireJS
support instead as this will avoid file/config conflicts.

Team: worth considering bringing back RJS behind a flag?

On Thursday, November 21, 2013, Younghoon Park wrote:

> I've been confused for several days with no requirejs support after seeing
> 'out-of-the-box requirejs support' on the website.
> So can anyone tell me how can I scaffold with requirejs now? It seems
> there is no '--requirejs' option.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/168#issuecomment-28966775
> .

## 

_Addy Osmani_
Phone: +44 7771 334170

**Comment by alefteris** [comment]
Should grunt-time be included by default or at all? Personally I don't care how much time a task takes to complete every time I run it. It is actually distracting to have it at the end of the task results. If it is possible it would be best to have as an option when running a grunt task, ex. `grunt build --time`

**Comment by changalberto** [comment]
Can we bring back RJS as a flag at least. I was so used the the workflow already...
Even adding http://assemble.io/ would be nice. But maybe that's too much to ask for this project..

+1 to RJS

**Comment by eddiemonge** [comment]
@changalberto what specifically do you use rjs for?

**Comment by changalberto** [comment]
I was more used to the process of downloading vendor JS with bower and then importing it via with grunt bower task automagically. It makes development much faster doing this way versus having to add new JS tags at the footer on each page every time you have new plugins to add — specially when you have like 10 pages. It also helps by packaging all the JS into one file and minifying it. But I suppose the minification process can be accomplished through UglifyJS.

FYI, by RJS I mean requireJS and not the r.js. Sorry if caused any misunderstanding.

**Comment by eddiemonge** [comment]
Have you tried grunt-bower-install to automatically link the files?

**Comment by changalberto** [comment]
No, I haven't. I just read through, that actually might be a better solution. Thanks!

**Comment by addyosmani** [comment]
If we get a few more votes for bringing back RequireJS via a flag, I'll land a patch to support it. Please keep in mind though that most of the time, RequireJS is something you'll use with a framework or library (like Backbone). Our generators for those types of projects have RequireJS support in there as a first-class citizen. If however you find that the lack of RequireJS support here is causing workflow issues we'll reconsider our position on it.

**Comment by atwoodjw** [comment]
+1 for --requirejs
also: +1 for --assembleio

**Comment by changalberto** [comment]
Again, big fan of Assemble now. So Assemble +100

Also... Ideally... It would be very very nice if the generator prompted us with the option to create custom paths for assets and bower components. I usually keep all my css, sass, js, and images in assets/
And bower by default keeps its components under "bower_components" But I like to call it components. I know these are all stuff that can be customized after being generated, but I think it's much cleaner to just do it in one go with the generator.

**Comment by SBoudrias** [comment]
This is generator webapp... Why not simply creating your own generator-assemble?

**Comment by changalberto** [comment]
@eddiemonge 
So using Assemble as my preferred static site generator, I usually have 10+ .html templates being generated per project. Your recommendation to use grunt-bower-install will not likely work in my favor at the the moment... ;[

https://github.com/stephenplusplus/grunt-bower-install/issues/31#issuecomment-30460840

**Comment by b-long** [comment]
@addyosmani +1 for `--requirejs` .  I realize there are other ways of wiring together applications (e.g. assemble.io), however I think the `--requirejs` is invaluable for legacy applications to use as an example to **begin** refactoring (and updating/modernizing) their applications.  Let's face it, RequireJS.org can be a bit overwhelming and many users just want to see something (or better yet `npm install` something), modify it and get started quickly.  The ability to "_Get started_" quickly **is the value proposition** of Yeoman.

**Comment by eddiemonge** [comment]
-1 for requireJS as its simple enough to add in on your own but adds more overhead to the project and slows new features. So for all the +1's, please take that into consideration

**Comment by kevva** [comment]
@eddiemonge, +1 on your -1.

**Comment by jaseemabid** [comment]
I'm sad to see rjs go without an optional flag, but happy to see the reduction in number of ifdefs. Not sure if I shoud :+1:  or :-1:

**Comment by thebengeu** [comment]
+1 for `--requirejs` - defaults would still be lean, and it'd be easier to keep the ifdefs in sync than with a separate generator-webapp-rjs fork.

**Comment by roggel2000** [comment]
Definite +1 for --requireJS
I understand framework generators come with this kind of stuff, but I don't always need a framework and if I do, those generators are almost always bugged.
I consider the web-app generator bugged too, as long as it fails on the inclusion of a requirejs block.

**Comment by addyosmani** [comment]
Okay. I'll put together a PR which adds it back in.

**Comment by devinfd** [comment]
So just for clarity sake, is requireJS/AMD not "best practice" any more? I thought Yeoman was opinionated? Should we not be following best practices then?

Not at all trying to be a troll, but just looking for clarification on the decision to remove requireJS altogether.

+1 for adding requireJS back.

**Comment by addyosmani** [comment]
The PR for adding back was submitted. I need to clean it up then land.

**Comment by changalberto** [comment]
I'm not sure if this is the right thread to start this discussion. But any plans to consider gulp over grunt?

**Comment by arthurvr** [comment]
>  But any plans to consider gulp over grunt?

@changalberto Therefor we have [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp).

**Comment by silvenon** [comment]
Ok, closing this ancient discussion. Most of these goals have been achieved.
