### ISSUE TITLE
Usemin renames rev'd files but changes aren't reflected in 'dist/'

### ISSUE THREAD

**Issue by mikefowler** [yeoman/generator-webapp_DEPRECATED#169]
When I run my build via `grunt build`, I can see the usemin step renaming paths to my fonts:

![screen shot 2013-09-25 at 6 48 00 pm](https://f.cloud.github.com/assets/744542/1214872/b47ff672-264d-11e3-8c5e-d402fc06ba6c.png)

And yes, I can verify this by opening `.tmp/styles/main.css` and checking the paths to the fonts, which now match up with the fonts that have been copied to `dist/styles/fonts`.

The issue is that the stylesheet that usemin copies over to `dist/styles` does not have these renamed paths. Odd, since usemin doesn't copy the CSS file over until it's finished its renaming tasks.

Thoughts, anybody?

**Comment by eddiemonge** [comment]
what versions of yo, generator-webapp? What changes have you made to the project?
