### ISSUE TITLE
Don't install bower components in /app

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-webapp_DEPRECATED#171]
This is just a proposal.

I think bower components should be installed in the root directory or in some kind of /vendor or /lib folder (more on why in a second). The reason I think it should not be installed in /app is that folder should be reserved for the user's app code, meaning that anything in there is maintainable by the user or created by the user. Bower should be managing the b_c folder, not the user.

It would be nice if npm supported installing to a named directory so b_c and node_modules could both be under a single folder.

B_c files could be supported with middleware in connect proxy similar to how .tmp is done so it wouldn't affect dev. This means that it would need to be in a subfolder then so it could be served as /bower_components still as if you point the middleware to <% bower_components %> it will try to serve from a b_c folder there instead of the actual folders (unless there is an option I am missing).

**Comment by robwierzbowski** [comment]
Ignoring the b_c folder in version control and concatenating into a non-ignored file in dist seems more understandable and straightforward to me — the components are part of the application, just not versioned parts. 

I'm currently getting my co-workers up to speed on Yeoman conventions and looking at it through their eyes it's a little more complicated than I had thought (familiarity makes everything seem simple). I think we should strive for the most direct, understandable structure and dev / build workflow possible. Not sure about this complication, but open to other opinions of course.

**Comment by eddiemonge** [comment]
I was actually trying to simplify the complications. I think its easier to say "hey everything in that there /apps folder be yer code so take care of it" instead of "ok you can modify everything in the /app folder except for that one folder there. and if you forget and make changes in it and it gets wiped out, well, oh well."

**Comment by sindresorhus** [comment]
I agree. The reason it's in the /app folder is because we previously copied everything over, now we only selectively copy files over to dist.

**Comment by eddiemonge** [comment]
@sindresorhus agree with who/what/which?

**Comment by sindresorhus** [comment]
you. move it.

**Comment by robwierzbowski** [comment]
Will we add a copy task to move bower components to .tmp on every `serve`? 

Wondering how I'll target Bower components from a non-root file. Right now I can do `/bower_components/mycomponent/bla`, but if the directory is outside of the server root not sure how that will work.

**Comment by eddiemonge** [comment]
thats the part that kept me from doing a PR on it. in my project I had to have /vendor/javascript/b_c and then in the middleware, point at vendor. I want to take a look at the connect plugin to see if there is a way to reference b_c in the root of project but serve it from an aliased folder so it looks normal to the server (like its in apps, when it isnt)

**Comment by oskarrough** [comment]
I understand the argument about bower_components not being something you should edit but they are an integral part of all generated apps and not just for development (like node_modules).

Wouldn't it just make things more complicated (confusing) if we move it out of /app? Having your scripts/components in the root of your app (app) is where you'll want them anyway.

**Comment by eddiemonge** [comment]
from the grunt server perspective, they would still be in /app but from the developers perspective, they wouldnt be. The goal is to make editing _your app_ easier and by focusing on whats in there that is hopefully accomplished.

**Comment by kvnwolf** [comment]
Agree with @eddiemonge proposal.

**Comment by jonocodes** [comment]
+1 for the proposal.

**Comment by eddiemonge** [comment]
Ok but I still am not sure how to accomplish this. Open to suggestions

**Comment by robwierzbowski** [comment]
I'm slowly coming around to the proposition too. A questions though:

If we're serving `bower_components` like `.tmp` and `test`, should we serve `bower_components` as a sibling of those folders and `app`? Would the middleware would cascade `.tmp`, `test`, `bower_components`, `app`? That would change component references in html/js/css from `bower_components/mycomponent/index.js` to `mycomponent/index.js`. Could possibly lead to name collisions and it's a big enough change that we should get an OK from the Yeoman issue queue.

**Comment by eddiemonge** [comment]
Ideally it would still keep the html references as `bower_components/mycomponent/index.js`. The actual folder would be a sibling of `app`, `node_modules`, etc. I have to dig into connect to see if this is possible without using something like grunt-rewrite

**Comment by addyosmani** [comment]
Just a fwiw, I would be open to us landing a change to bring this into place, but it would need to go through extensive testing (of course). I'm particularly curious about how well we can make this work with the intermediate serve task as that was originally one of the driving reasons behind it landing in /app.

**Comment by eddiemonge** [comment]
I have it working in my project but to do that I had to create a vendor/bower_components folder path. I still have to look into having a rewrite or something to accomplish this without the stuffing vendor folder.

**Comment by rwxrob** [comment]
Being a noob to all this I just got a handle on why and how bower puts <site>/bower_components at that location. Moving it out is going to minimally confuse people coming at this from just Bower exposure. That is, until they see that the `dist` directory built has them in the expected location.

While we are moving Bower stuff around. Has anyone dared suggest we inline all the bower components into other things that are being built? Fewer links the better, no?

**Comment by eddiemonge** [comment]
what do you mean by inline all the bower components? usemin is already concatenating them where it can.

**Comment by josephdburdick** [comment]
If the consensus is that we shouldn't install b_c in /app why does the yo generator still place it there? I just updated and re-ran it.

**Comment by oskarrough** [comment]
@josephdburdick, check your .bowerrc file, perhaps it's still set to install into /app.

**Comment by silvenon** [comment]
Or check if you have a `~/.bowerrc`.

**Comment by josephdburdick** [comment]
I've done all of that with the same results. Looks like gulp-webapp doesn't follow the practices from here, it still sets .bowerrc to app/bower_components. I'll write an issue there. Thanks.

**Comment by eddiemonge** [comment]
are you having an issue with `generator-webapp` or `generator-gulp-webapp`?

**Comment by josephdburdick** [comment]
I'm having trouble with generator-gulp-webapp so you can ignore further comments from me on this repo.

**Comment by alokp-chromium** [comment]
I just tried generator-polymer and it installed b_c under app/. Are there plans to update generator-polymer?

**Comment by silvenon** [comment]
You're right, thanks for the heads up. You can raise an issue there referencing [this](http://yeoman.io/blog/bower_components-in-project-root.html) post.
