### ISSUE TITLE
Compass relative assets issue in build

### ISSUE THREAD

**Issue by primozcigler** [yeoman/generator-webapp_DEPRECATED#172]
I am running the dist webapp in the subfolder of the production URL, for example: `http://example.com/subfolder/index.html`.

When building the dist version of the app, the images in the CSS will not be pointing to the correct path.
1. **`relativeAssets: true`**
   
   the problem here is that the relative assets will be pointing to the original app directory and not the the optimized images in the dist: `../../app/images/some-image.jpg`
2. **`relativeAssets: false, httpImagesPath: '/subfolder/images'`** 
   
   the problem here is that is it not referencing the minified images. In generated CSS I get `url(/subfolder/images/blackboard-sm.jpg?1380479560)` instead of `url(/subfolder/images/36337cc7.blackboard-sm.jpg?1380479560)`

I have been struggling around this quite a lot already, maybe it is just me doing something wrong here, but I cannot make it somehow to work.

```
1.0.4
%PATH% %NODE_PATH%
win32 { http_parser: '1.0',
  node: '0.10.17',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.14',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e' }
Gruntfile.js is ./Gruntfile.js
```

I am using this in Win7.

**Comment by eddiemonge** [comment]
@primozcigler Are you still experiencing this issue?

**Comment by primozcigler** [comment]
Hi Eddie,

Yes, the issue is still present, however I must admit I don't use the `yo` anymore for the time being, since I didn't understand very well Grunt before and it really irritates me when I am using the tool which I don't understand how it works.

So for now I am setting up my Gruntfiles by myself since I am still learning and adding task by task (yo created too much stuff at once for me!). It may happen that I will will find the solution myself once I understand the Grunt plugins in depth.

**Comment by Misiur** [comment]
Hello there, I've started using this generator and I'm experiencing exactly the same issue.
