### ISSUE TITLE
RequireJS missing after grunt build

### ISSUE THREAD

**Issue by paoloboschini** [yeoman/generator-webapp_DEPRECATED#173]
Hi,

If I create a 'yo webapp' and do 'grunt build' I get modernizr, sass-bootstrap and requirejs in dist/bower_components/

However, if I remove 'uglify' from the list in grunt.registerTask('build'... in Gruntfile.js, requirejs is missing from dist/bower_components/

Is that the expected behavior? Am I missing something important?

Appreciate any help!

**Comment by sindresorhus** [comment]
RequireJS support has been removed. It bloated the generator and none of us use it so we can't provide a good service for it. I'm sure the community will fork generator-webapp and make generator-webapp-rjs ;)

https://github.com/yeoman/generator-webapp/commit/f53d0d49e2f8c334494d782e6620f6c4bf36d41d
