### ISSUE TITLE
Index.html doesn't refer to the leaner custom build of Modernizr

### ISSUE THREAD

**Issue by wzxu** [yeoman/generator-webapp_DEPRECATED#176]
So grunt-modernizr compiles a custom build from `<%= yeoman.app %>/bower_components/modernizr/modernizr.js` to `<%= yeoman.dist %>/bower_components/modernizr/modernizr.js`, 
but then usemin also uglifies the complete original file `<%= yeoman.app %>/bower_components/modernizr/modernizr.js` to `<%= yeoman.dist %>/scripts/vendor/modernizr.js`, 
and that remains as the one index.html points to.

Is this the intended behavior? How do I set up Gruntfile.js so that it only compiles the custom Modernizr and makes index.html point to it? 

Thanks!

**Comment by stereokai** [comment]
I think you should try removing the build comments around the Modernizr script tag in index.html. Does that makes sense?

**Comment by wzxu** [comment]
Huh. Looks like that did it. Still pretty new to this (yeoman, grunt, bower). Thanks!
Shouldn't it use the custom one by default, though? Or it's actually other package that's responsible for the index.html?

**Comment by stereokai** [comment]
I don't know how is this generator configured, I never used it. But if you need Grunt to build a custom Modernizr build for you, perhaps consider using usemin with useminPrepare comments (the things that look like this: `<!-- build:js scripts/app.js -->`) or if you really have to, use Require.js

**Comment by kevva** [comment]
We are using https://github.com/Modernizr/grunt-modernizr. Feel free to modify your `gruntfile.js` to fit your needs.
