### ISSUE TITLE
broken out of box - grunt doesn't copy bootstrap js libraries into /dist/  

### ISSUE THREAD

**Issue by sholtomaud** [yeoman/generator-webapp_DEPRECATED#178]
I'm having trouble with yeoman's out of the box generator:

```
>yo webapp
```

I managed to get the bootstrap css to work after a bit of googling, however I still can't get bootstrap js libraries like bootstrap-tab.js, or bootstrap-modal.js to come across into the /dist/ directory after a grunt build. 

All I get is the bootstrap.js file. So out of the box the demo webapp has no bootstrap tab or dropdown functionality etc.

How do I get this to work?

Cheers,

Sholto

**Comment by sivicencio** [comment]
The Bootstrap JS functionality doesn't seem to be working even in the local webapp (the one generated with `grunt server`). I've made a simple test with a dismiss alert, clicked the `x` button, but it didn't close the alert.

I think no Bootstrap JS file is being loaded  (I don't see any in `index.html` file).

Is this happening to someone else?

**Comment by addyosmani** [comment]
I just ran the latest version of the generator with both Sass Bootstrap and regular Bootstrap and didn't run into these issues with `dist` at build time. Perhaps I'm missing something.

@stephenplusplus or @passy could you verify if the above happens for you too?

**Comment by addyosmani** [comment]
ping.

**Comment by eddiemonge** [comment]
Seems more appropriate for stackoverflow and there hasn't been any activity in 3 weeks.
