### ISSUE TITLE
Bootstrap for Sass javascript not included. Jquery included twice

### ISSUE THREAD

**Issue by jarrodmedrano** [yeoman/generator-webapp_DEPRECATED#183]
I did a default 'yo webapp' and selected Bootstrap for Sass.
I noticed that none of the bootstrap javascript is working. For instance If I make a default collapsible navbar, it does not open on mobile unless i explicitly include collapse.js in the html.

http://getbootstrap.com/components/#navbar-default

Also jquery is included once in the body tag of index.html and again in main.js.

**Comment by Ahrengot** [comment]
Alright, just to make clear:

Unless you use require.js you're supposed to include the scripts manually. [Grunt-usemin](https://github.com/yeoman/grunt-usemin) then concatenates the stuff you actually use when you do `grunt build`.

Hope that makes sense :smile:

**Comment by addyosmani** [comment]
I think the above raises a good point - we should make it more clear that the scripts need to be included manually.

**Comment by eddiemonge** [comment]
I think this issue is invalid now. I generated a project right now (from master, not npm) using the default prompts and my index.html has:

``` html
        <!-- build:js scripts/plugins.js -->
        <script src="bower_components/sass-bootstrap/js/affix.js"></script>
        <script src="bower_components/sass-bootstrap/js/alert.js"></script>
        <script src="bower_components/sass-bootstrap/js/dropdown.js"></script>
        <script src="bower_components/sass-bootstrap/js/tooltip.js"></script>
        <script src="bower_components/sass-bootstrap/js/modal.js"></script>
        <script src="bower_components/sass-bootstrap/js/transition.js"></script>
        <script src="bower_components/sass-bootstrap/js/button.js"></script>
        <script src="bower_components/sass-bootstrap/js/popover.js"></script>
        <script src="bower_components/sass-bootstrap/js/carousel.js"></script>
        <script src="bower_components/sass-bootstrap/js/scrollspy.js"></script>
        <script src="bower_components/sass-bootstrap/js/collapse.js"></script>
        <script src="bower_components/sass-bootstrap/js/tab.js"></script>
        <!-- endbuild -->
```

@jmedran Can you confirm this is fixed for you so we can close this issue or is there something else?

**Comment by eddiemonge** [comment]
I definitely this is invalid now that grunt-bower-install is in
