### ISSUE TITLE
Consider using harp to simplify the gruntfile and speed up the development loop

### ISSUE THREAD

**Issue by alexandrosm** [yeoman/generator-webapp_DEPRECATED#185]
I've recently been exploring https://github.com/sintaxi/harp which is an integrated webserver and preprocessor. Having a .less or .coffee file in a directory and requesting a .css or .js respectively, will lead to the webserver performing the appropriate transformation transparently. While it doesn't have all the bells and whistles needed for production use (concatenation, minification, cache-busting, etc), it's pretty great for development.

By using harp, the style transformation, coffeescript compilation, and lots of the copy task can be removed. (but it does not support sass, only less/stylus, so that may be an issue). Also, it can directly execute in the app/ directory, obviating the need for a .tmp directory altogether, further simplifying the gruntfile. As a bonus, it adds native support for markdown, ejs, and jade, all auto-converted to html by the web server.

When the time comes to build, harp can be run as a static file generator that can output directly to a temp directory, with the current rest of the process on concatenation/minification being used. 

I am already using it for a yeoman-derived project and early signs are looking good. I can package my code into a grunt-harp task if there is interest.

**Comment by sindresorhus** [comment]
While harp is nice, it doesn't really fit into this generator. However I would encourage you to fork this generator add it in and publish it on npm with a new name, so others can try it out ;)

**Comment by alexandrosm** [comment]
Will do. Its a pretty massive rewrite that ive done, but will come out at
some point.
