### ISSUE TITLE
Modernizr task doesn't seem to serve a purpose.

### ISSUE THREAD

**Issue by KingScooty** [yeoman/generator-webapp_DEPRECATED#190]
The grunt modernizr task which triggers during a build doesn't seem to be plumbed in properly. It produces a compact custom modernizr script in a `bower_components` folder within `dist`, which isn't linked to any of the project files and doesn't replace the existing `vendor.js` concatenated file in the header.

Is there a way to automate concatenating this back into the vendor.js file and adding the cache busting seed number to to the end of the file? e.g. vendor.3532523.js

https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L307-L316

**Comment by addyosmani** [comment]
I consider this a bug. We should be writing up the compact modernizr build for you if the task is being run in a project actually using Modernizr.
