### ISSUE TITLE
--test-framework <framework> should be --test-framework=<framework>

### ISSUE THREAD

**Issue by jdelight** [yeoman/generator-webapp_DEPRECATED#191]
From the readme, missing an equals sign  :)

**Comment by sindresorhus** [comment]
Equal sign is optional.

**Comment by jdelight** [comment]
Ahh ok thanks - didn't seem to work for me but I'll try again. Also having recently used the ember generator where the docs have a very similar but slightly different command it would be nice to use the same format to reduce confusion.
https://github.com/yeoman/generator-ember

readme for generator-ember:
--test-framework=[framework]

readme for generator-webapp:
--test-framework &lt;framework&gt;

minor point I know - but consistency would be nice.

Also really appreciate all your work for the web community! So thanks :)

**Comment by paulRbr** [comment]
@sindresorhus I indeed had a problem specifying the test-framework from command line, see https://github.com/popox/generator-webapp-rjs/issues/2

and

my PR
