### ISSUE TITLE
grunt-usemin@2.0.0 causing a problem with removing cssmin/uglify tasks

### ISSUE THREAD

**Issue by sarith** [yeoman/generator-webapp_DEPRECATED#197]
Hey guys,

I'm not 100% this is really a bug per se -- possible that I just need to adjust my workflow here.

With older version of `generator-webapp` (using `grunt-usemin@~0.1.10`), during development I used to like to be able to disable CSS minification JS uglification during `build` by simply commenting out the lines in my `Gruntfile.js`:

``` javascript
grunt.registerTask('build', [
        'clean:dist',
        'useminPrepare',
        'concurrent:dist',
        'autoprefixer',
        'concat',
        // 'cssmin',
        // 'uglify',
        'copy:dist',
        'rev',
        'usemin'
]);
```

This would normally preserve the file copying and all that in the `dist` directory, but with easily-readable CSS / JS files.

With the newest update, generator-webapp has upgraded its Usemin dependency to `grunt-usemin@2.0.0`.  As a result, when I remove the `cssmin` and `uglify` tasks from the `build` task, it neither creates the `styles` and `scripts` directories, nor does it create my files.

As a quick fix for my own workflow - I've manually downgraded the `grunt-usemin` dependency to `grunt-usemin@~0.1.10`.  This solves my problem.  For the future, though, can someone give me some insight as to why this is happening and if there is something else I should be doing to get it working like this in the newest version of `generator-webapp`?

**Comment by eddiemonge** [comment]
why would you need the unminified versions? you should only need those for development, which are created in the .tmp folder.

**Comment by sarith** [comment]
Mostly because I'm working with other developers who are not using a Yeoman-based workflow quite yet.  Building in this manner gives me a nice clean (but still workable) distributable directory that I can just pass off.

**Comment by eddiemonge** [comment]
why dont you pass off the whole directory? make their lives easier too

**Comment by sarith** [comment]
I'm working on a large enough team that it will take some time (more than I have for the current project) to on-board everyone to a Yeoman/Grunt/Bower-based front-end workflow.  I know - not ideal - but that's just situation right now.  In any case, the above issue is somewhat unrelated to this fact -- I suppose the real question is whether or not I should be editing my Gruntfile in some other way to remove minification/uglification while still allowing the necessary files to be concatenated and moved properly?

**Comment by addyosmani** [comment]
It's inevitable that upgrades to some of our dependencies may introduce minor changes or regressions to workflow. We do generally review these changes before deciding to upgrade, however if you find that the official generator-webapp has switched to something that doesn't quite work for you, I'd recommend forking (as you appear to have) and manually bringing back in changes you like.

In the future once we have better support for composable generators all of this will be significantly more straight-forward.

**Comment by Danmer** [comment]
For example, you can replace `cssmin` and `uglify` to `copy:concats` if add this target to `copy` config:

``` js
copy: {
    dist: { ... },
    styles: { ... },
    concats: {
        expand: true,
        dot: true,
        cwd: '.tmp/concat',
        dest: '<%= yeoman.dist %>',
        src: '**/*.*'
    }
}
```

It helped me in same situation.

**Comment by sarith** [comment]
@Danmer the copy:concats tasks was a wonderful idea and worked perfectly. Thank you!

@addyosmani Understood - thanks for all the efforts to you and the Yeoman team!

**Comment by frankfuu** [comment]
@Danmer 

That was brilliant!
