### ISSUE TITLE
Drop RequireHM support

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp_DEPRECATED#2]
We are going to try adding in support for Traceur in the near future. As HM usage has been fairly low I think it would be more useful to devs if we dropped this question.

@sindresorhus have you already applied this locally? Happy to remove it from the generator if that helps.

**Comment by sindresorhus** [comment]
@addyosmani already done locally.

**Comment by addyosmani** [comment]
Awesome. I'll leave it up to you to push then :)
