### ISSUE TITLE
Image paths in css files get revved and can't be found

### ISSUE THREAD

**Issue by gsklee** [yeoman/generator-webapp_DEPRECATED#205]
Say I got an image background:

``` css
background: #c7a07f url('images/phone.png');
```

After running it through `grunt`, the filename of the image has been revved into `53a6ac41.phone.png` and the browser can't locate it. Is there any way to annotate the CSS so that it automatically updates to something like this?

``` css
background: #c7a07f url('images/53a6ac41.phone.png');
```

I believe there is a way to do this but can find no way about it anywhere on available documents.

**Comment by gsklee** [comment]
Okay, I was able to fix this by using the absolute path:

``` css
background: #c7a07f url('/images/phone.png');
```

Seems to be the same issue with https://github.com/yeoman/yeoman/issues/824

BTW this is happening in v0.4.3 since v0.4.4 is not working properly currently (#204).

**Comment by eddiemonge** [comment]
so are you still having an issue/

**Comment by gsklee** [comment]
Yep, it should be able to work on relative paths as well.

**Comment by eddiemonge** [comment]
this is a usemin bug and should be opened there (i think it already has been).
