### ISSUE TITLE
Compass mixin transform-origin does not compile

### ISSUE THREAD

**Issue by MichaelKaeser** [yeoman/generator-webapp_DEPRECATED#206]
When grunt runs the compass task, this mixin: @include transform-origin(0,100%,0); can't get compiled. Show error message: Mixin transform-origin takes 1 argument but 3 were passed. But that's not true, the compass doc says that multiple arguments can get passed.

I compiled my .scss file with codekit and it worked great. Also tried to reinstall the compass gem, both v.0.12.2 and the older version v.0.12.1, but did not change anything.

Someone an idea?

**Comment by eddiemonge** [comment]
does it work if you use compass without using grunt? either way, i think this should be opened in grunt-contrib-compass

**Comment by MichaelKaeser** [comment]
Compass doc: @include transform-origin( [ origin-x, origin-y, origin-z, 3D-only ] ). Just tried the include without comma separated values, like so: @include transform-origin(0 100% 0); and it worked! Really weird, seems like the compass task can't always handle those commas... So, this issue can be closed.

**Comment by rcstr** [comment]
yes, it works without comma (,)
