### ISSUE TITLE
Files with Mac line endings are created on Linux machines

### ISSUE THREAD

**Issue by mdkess** [yeoman/generator-webapp_DEPRECATED#208]
It seems that the files generated by this generator have Mac line endings, which is confusing the coffeescript compiler. On version 0.4.4 of the generator.

Backstory:
I made a new project with this generator on my Ubuntu box with

``` bash
yo webapp --coffee
```

and the command succeeded as expected. However, when I edited hello.coffee, I started getting strange errors.

``` coffeescript
console.log "'Allo from CoffeeScript!"
console.log "This is a test"
```

Which resulted in the following great message from the grunt server:

```
Running "coffee:dist" (coffee) task
>> SyntaxError: unexpected IDENTIFIER
>> In file: app/scripts/hello.coffee
>> On line: 0
console.log "This is a test"offeeScript!"
```

which makes sense ('\r' is the line ending on Mac, '\n' on Linux), but is confusing. A little sed action fixed this for me, but might be nice to fix for others.

**Comment by sindresorhus** [comment]
That's a bug. It should only generate `\n` line-endings. A PR would be awesome :)

**Comment by eddiemonge** [comment]
just goes to show what the people who work on this project use ;)

**Comment by eddiemonge** [comment]
I can't reproduce this error and if it continues then its a bug in your node installation as the generator use the standard fileWriteSync node api method. If you try reinstalling node and still get this error then you might want to file a bug at nodejs. I am closing it as I can't reproduce it and it couldn't be fixed here anyway.
