### ISSUE TITLE
No styles after running build process

### ISSUE THREAD

**Issue by haydenbleasel** [yeoman/generator-webapp_DEPRECATED#211]
I'm having an issue where, after running either `grunt` (and manually opening `dist/index.html`) or `grunt serve`, styles aren't being copied to the `dist` folder, which results in no styles being applied to the page. I've detailed the build log in [this gist](https://gist.github.com/haydenbleasel/7539859). There's a prominent error at line 116:

```
Running "cssmin:generated" (cssmin) task
>> Destination not written because minified CSS was empty.
```

The closest issues I've found so far (but not the same) are:
- https://github.com/yeoman/yeoman/issues/411
- https://github.com/yeoman/generator-webapp/issues/204
- https://github.com/yeoman/generator-webapp/issues/174

Also, I'm running the latest version of `yo` and `generator-webapp` on Mac OSX 10.9.

![screenshot 2013-11-27 02 01 40](https://f.cloud.github.com/assets/4142719/1622852/c8cbdb9e-56ab-11e3-9196-97980d180c06.png)

**Comment by oskarrough** [comment]
And your styles are not being copied to the hidden folder `dist/.tmp`? Otherwise perhaps you could zip your webapp to me and I'll test it on my setup.

**Comment by haydenbleasel** [comment]
@oskarrough - Emailed the archive to you. It's a fresh build of webapp, just run `npm install` to grab the dependencies.

**Comment by haydenbleasel** [comment]
Okay @oskarrough and I fixed it via email. For anyone who has this error, it's a Compass issue. Check your Ruby (`ruby -v`), Sass (`sass -v`) and Compass (`compass version`) versions. Running `compass version` gave me the following error:

```
/Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/definition.rb:16:in `build': /Gemfile not found (Bundler::GemfileNotFound)
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:148:in `definition'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:116:in `setup'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/bin/compass:26:in `<top (required)>'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247/bin/compass:23:in `load'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247/bin/compass:23:in `<main>'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
    from /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

Searching the internet a bit, I found a [related issue](https://github.com/chriseppstein/compass/issues/1424). Next, I ran the following command to uninstall rubygems-bundler from the global scope:

`gem uninstall -i /Users/haydenbleasel/.rvm/gems/ruby-2.0.0-p247@global rubygems-bundler`

This allowed `compass version` to work, which in turn fixed the build process for the webapp generator.

All good now homies.

@eddiemonge

**Comment by ecurtis** [comment]
I am getting this same behavior, however I get no errors when running the version commands you mentioned:

$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

$ sass -v
Sass 3.2.13 (Media Mark)

$  compass version
Compass 0.12.2 (Alnilam)

Any other ideas on how to fix?

**Comment by haydenbleasel** [comment]
@ecurtis - Run `gem list` and show us the list of local gems you have installed.

**Comment by ecurtis** [comment]
Thank you for the quick response. Here are the results:

CFPropertyList (2.2.5, 2.2.4, 2.2.0)
chunky_png (1.2.9)
compass (0.12.2)
fssm (0.2.10)
libxml-ruby (2.7.0, 2.6.0)
mini_portile (0.5.2, 0.5.1)
nokogiri (1.6.1, 1.6.0, 1.5.6)
sass (3.2.13, 3.2.12)
sqlite3 (1.3.8, 1.3.7)

**Comment by haydenbleasel** [comment]
@ecurtis - I think it might be because you have 2 versions of SASS installed (`3.2.13` and `3.2.12`). Try uninstalling SASS and Compass explicitly (`gem uninstall compass` and `gem uninstall sass`) then re-install just Compass (`gem install compass`) since Compass carries SASS as a dependency.

**Comment by ecurtis** [comment]
Thank you for the suggestion, however that did not solve it. Here is the updated gem list:
CFPropertyList (2.2.5, 2.2.4, 2.2.0)
chunky_png (1.2.9)
compass (0.12.2)
fssm (0.2.10)
libxml-ruby (2.7.0, 2.6.0)
mini_portile (0.5.2, 0.5.1)
nokogiri (1.6.1, 1.6.0, 1.5.6)
sass (3.2.13)
sqlite3 (1.3.8, 1.3.7)

**Comment by haydenbleasel** [comment]
@ecurtis - Interesting. Check if it's a fault on the SASS level by running `sass --watch main.scss:main.css` and seeing what happens. Otherwise, you could try uninstalling your gems / running Grunt / reinstalling your gems to determine whether that's the problem.

**Comment by ecurtis** [comment]
I will dive into some more tomorrow. I take it that a fresh install of the generator works well for you. Are you on OS X? If so which version? Also which version of sass, compass, and ruby are you running?

**Comment by haydenbleasel** [comment]
Ruby `2.0.0p247`, Compass `0.12.2 (Alnilam)`, Sass `3.2.12 (Media Mark)`, Mac OSX 10.9.1.

**Comment by ecurtis** [comment]
I ran npm update -g and now while I get the error it is outputting the css to the dist folder. So I guess we are good to go!

In case it is of interest prior to running the npm update, it was outputting some css, but not the:

@import 'sass-bootstrap/lib/bootstrap';

So most styles were off.

Thank you for your help. Cheers.

**Comment by josephdpurcell** [comment]
I am having this issue too. I'm at a complete loss; any help would be greatly appreciated!

```
$ ruby -v
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin12.3.0]
$ sass -v
Sass 3.2.18 (Media Mark)
$ compass version
Compass 0.12.4 (Alnilam)
Copyright (c) 2008-2014 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
```

The following works fine:

```
sass --watch main.scss:main.css
```

However, I get the issue just like Hayden described. Here is my grunt --debug --verbose output for cssmin:

```
Running "cssmin:generated" (cssmin) task
[D] Task source: /Users/jpurcell/src/sites/myapp/node_modules/grunt-contrib-cssmin/tasks/cssmin.js
Verifying property cssmin.generated exists in config...OK
Files: [no src] -> dist/styles/vendor.css
Files: .tmp/styles/main.css -> dist/styles/main.css
Options: report=false, root="app"
>> Destination not written because minified CSS was empty.
Reading .tmp/styles/main.css...OK
Reading .tmp/styles/main.css...OK
Writing dist/styles/main.css...OK
File dist/styles/main.css created.
```

What is perplexing to me is that after building I get a file: dist/styles/eec6e6bc.main.css. If I change the app/index.html file to point the main.css to eec6e6bc.main.css all the styling works!

Possibly related, is that if I look at the console log for any 404s this returns a 404: /styles/vendor.css. But, I don't see any files vendor.css.

Any thoughts?

**Comment by lagden** [comment]
There's a bug!!

I think that the problem with glob.

`src: ['**/*.css'] # bug` 
`src: ['{,*/}*.css'] #bug` 
`src: ['*.css'] #ok`

**Bug**
```coffeescript
cssmin:
  dist:
    options:
      keepSpecialComments: 0
      report: 'gzip'
    files: [
      expand: true
      flatten: false
      cwd: '<%= project.dev %>/css'

      # This way return: >> Destination not written because minified CSS was empty
      src: ['{,*/}*.css']

      dest: '<%= project.prod %>/css/'
      ext: '.css'
    ]

**OK**
```coffeescript
cssmin:
  dist:
    options:
      keepSpecialComments: 0
      report: 'gzip'
    files: [
      expand: true
      flatten: false
      cwd: '<%= project.dev %>/css'
      
      # OK
      src: ['*.css']

      dest: '<%= project.prod %>/css'
      ext: '.css'
    ]
```

**Comment by moneytree-doug** [comment]
:+1: Has anyone figured out a way to fix this?

**Comment by silvenon** [comment]
I'll investigate.

**Comment by dustintheweb** [comment]
Make sure your packages are up to date, worked for me

```
$ npm install -g npm-check-updates
$ npm-check-updates -u
$ npm install
```

also, yeoman

```
$ npm install -g yo
```

**Comment by silvenon** [comment]
We have a pending PR which updates all deps, I just have to test it first.

**Comment by silvenon** [comment]
Just released v0.6.0, lots of things has changed and this should work now. I'll reopen if you are still experiencing issues with this.

**Comment by sebastianha** [comment]
I just used the generator-webapp to generate a new app with bootstrap only and first it looks fine, grunt:serve works as expected.

But when I build the project the Bootstrap CSS seems to miss and the web page is displayed like on the screenshot of the first post here.

I updated everything to the latest version but could not figure out what's wrong. Can anyone help me?

**Comment by silvenon** [comment]
Does this happen with the fresh install? Did you modify your `Gruntfile.js` or `index.html`? If yes, could you tell us what you changed?

**Comment by sebastianha** [comment]
I did a fresh install, just "yo webapp", selected bootstrap only and then did a "grunt serve" (which works well) and then a "grunt" or "grunt build". This results into an empty "vendor.XXX.css" file. When I replace this file with the original "bootstrap.css" everything is fine.

Here is a list of my installed versions:
├── bower@1.4.1
├── generator-webapp@0.6.2
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── npm@2.12.1
└── yo@1.4.7

**Comment by silvenon** [comment]
Thanks for reporting. The solution is very simple, change this line:

``` html
<!-- build:css styles/vendor.css -->
```

to this:

``` html
<!-- build:css(.) styles/vendor.css -->
```

**Comment by sebastianha** [comment]
Thank you very much, works now!

**Comment by wilsonbradleyc** [comment]
I'm having this same problem.  I just created a new project using 'yo angular StockDog' and the CSS is not found for the default app.  (I'm going through 'Professional AngularJS -> Wrox)

During set up, I did not include Sass w/Compass, but did select to use Bootstrap.

index.html has the correct build:ccs line (I didn't have to change it):

`<!-- build:css(.) styles/vendor.css -->`

**Comment by silvenon** [comment]
This is an issue with [generator-angular](https://github.com/yeoman/generator-angular) then, not generator-webapp.

**Comment by wilsonbradleyc** [comment]
Ok thanks.  I'll move the discussion over there.

**Comment by TeChn4K** [comment]
Thank you @silvenon, your solution works. But ... all vendors images path are broken... Any solution ?

EDIT : i use dw-bxslider-4 and fontawesome. And my generated vendor.css contains wrong image and font path

**Comment by silvenon** [comment]
@TeChn4K unfortunately you'll have to do some hacking to fix these paths, this is not really something we can solve. [gulp-replace](https://github.com/lazd/gulp-replace) might be helpful.

**Comment by TeChn4K** [comment]
OK thank you, i'll give it a try.
If someone have a draft solution to this problem I will be grateful :)

**Comment by silvenon** [comment]
StackOverflow is great for these kinds of questions, with tags `#yeoman` and `#grunt` in this case. I suggest giving more details if you decide to ask there.
