### ISSUE TITLE
Add support for grunt-uncss

### ISSUE THREAD

**Issue by kvnwolf** [yeoman/generator-webapp_DEPRECATED#215]
Take a look at this `uncss` wrapper by @addyosmani: https://github.com/addyosmani/grunt-uncss.

It would be vey useful to integrate that plugin into the webapp generator.
What did you guys think?

**Comment by addyosmani** [comment]
I think we should consider adding this as an optional task when grunt-uncss is a little more stable. For example, one thing we don't currently support is injection of CSS dynamically (via JS). This is done often and I'd be concerned that until we have that developers may run into a ton of issues that would result in a poor experience.

So, +1 for adding in the future but -1 until stable :)

**Comment by sindresorhus** [comment]
Yeah, might be useful, but I have concerns right now of it being too fragile. Let's revisit when it gets more stable ;)
