### ISSUE TITLE
Bower install during initialize

### ISSUE THREAD

**Issue by jbravar** [yeoman/generator-webapp_DEPRECATED#222]
The `bower install` that runs during the init process doesn't seem to catch Modernizr anymore, leading to a failed build until another `bower install` is run.

Fresh after a `yo webapp`

```
Running "modernizr" task

Enabled Extras
>> shiv
>> load
>> cssclasses

Looking for Modernizr references
Warning: Can't find your Modernizr development build at app/bower_components/modernizr/modernizr.js
       grunt-modernizr needs this path to avoid false positives

       Update your gruntfile via the modernizr.devFile config option
       See https://github.com/doctyper/grunt-modernizr#devfile-string for more details

       Use --force to continue.

Aborted due to warnings.
```

Works fine after re-running `bower install`.

**Comment by eddiemonge** [comment]
What version of the generator?

**Comment by jbravar** [comment]
`generator-webapp@0.4.4`

**Comment by inlikealion** [comment]
I can confirm the same issue. 

`v0.4.4` is giving us lots of weird issues (which I can open new issues for) such as not compiling sass (bootstrap-sass option) through the `.tmp` process, JSHint indent errors in `Gruntfile.js`.

**Comment by addyosmani** [comment]
@inlikealion we'd really appreciate that.

**Comment by eddiemonge** [comment]
There are a few problems going on that I see:
1. `Bower install` runs for the mocha generator but not for webapp because of https://github.com/yeoman/generator-mocha/issues/17
2. `Bower install`, when it does run for webapp throws errors similar to for random packages:

```
bower ENOENT        ENOENT, lstat '/Users/eddie/Desktop/test/app/bower_components/jquery/jquery-migrate.js'

Stack trace:
/usr/local/share/npm/lib/node_modules/bower/node_modules/fstream/lib/writer.js:284:26
Object.oncomplete (fs.js:107:15)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/share/npm/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/usr/local/share/npm/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/share/npm/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/share/npm/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/local/share/npm/lib/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.10.22
OS: Darwin 13.0.0 x64
```
1. grunt-modernizr seems to hang the first run through when it tries to download the source files (why its doing that I don't know)

**Comment by addyosmani** [comment]
Confirmed against master. This is a blocker on the next release being made.

**Comment by addyosmani** [comment]
Investigating what we can do to workaround or fix this issue. Just to note: we have no issues with the `grunt` build if `Modernizr` is not selected as an option during initialization.

```
.....

Processing as HTML - dist/index.html
Update the HTML to reference our concat/min/revved script files
<script src="scripts/vendor.js" changed to <script src="scripts/d41d8cd9.vendor.js"
<script src="scripts/main.js" changed to <script src="scripts/b6c3df09.main.js"
<script src="scripts/plugins.js" changed to <script src="scripts/d41d8cd9.plugins.js"
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input

Running "usemin:css" (usemin) task

Running "htmlmin:dist" (htmlmin) task
File dist/404.html created.
File dist/index.html created.

Done, without errors.
```

**Comment by addyosmani** [comment]
@eddiemonge even after a `bower install` mine hung for at least a solid 5 minutes while the task tried getting the latest source files. This was reported by someone else over at https://github.com/Modernizr/grunt-modernizr/issues/45.

```
Looking for Modernizr references

in dist/styles/main.css
>> svg
>> input

Downloading source files
200 modernizr-latest.js
```

Confirmed this is still an issue with grunt-modernizr 0.3.1 and 0.4.1.

**Comment by stephenplusplus** [comment]
The only problem I'm having is `bower install` not being run during `yo webapp`. It grabs the test's b_cs, but not the others. Manually running `bower install`, then `grunt build` after produces no errors.

**Comment by addyosmani** [comment]
Tried testing with yo 1.0.0 -> 1.0.6, generator versions 0.14.0 -> 0.14.2, latest bower in case it was a different issue, but I'm still perplexed as to what is causing the issue. One thing I'm consistently seeing is that we seem to try calling out to Bower, but are perhaps failing silently (nothing Bower related is logged between these lines):

```
I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.




I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.
```

**Comment by tgig** [comment]
I noticed the same problem today as @stephenplusplus, and a subsequent manual command of <code>bower install</code> seems to fix it. This may also be the reason for a lot of SO and github issues with styles not loading by default.

More detail:

I run <code>yo webapp</code> and then <code>grunt serve</code>. The default page loads, but w/o styles:

![image](https://f.cloud.github.com/assets/1834003/1750773/b72c070e-65b2-11e3-9fff-0b1094134d93.png)

And that's b/c the bower_components directory is not created:

![image](https://f.cloud.github.com/assets/1834003/1750775/e58821d2-65b2-11e3-92f2-1aa833ef6e0a.png)

If I run <code>bower install</code> and <code>grunt serve</code>, then page loads w/ styles:

![image](https://f.cloud.github.com/assets/1834003/1750776/f8cf6106-65b2-11e3-9e26-4399d985593c.png)

Let me know if I can provide any more info. :smile:
