### ISSUE TITLE
Issue with bower / sass when using webapp

### ISSUE THREAD

**Issue by matthewfowles** [yeoman/generator-webapp_DEPRECATED#225]
Hi

Have just set up webapp. When i run grunt serve i get the error. 

 error app/styles/main.scss (Line 121 of app/bower_components/sass-bootstrap/lib/_mixins.scss: Invalid CSS after "...-shadow($shadow": expected ")", was "...) {")

I'm sure this is a bower or sass problem but not sure which? I have updated to latest sass and bower it makes no difference.

Sorry if I'm posting in the wrong place.

Help greatly appreciated

**Comment by eddiemonge** [comment]
Did you change anything in the files?

**Comment by matthewfowles** [comment]
No I change nothing.

I had a really old version of yeoman from when it first came out. Had Not used it so i deleted it and re-installed with the web app generator. Had another issue that when i run "yo webapp" it did not insert the bower components so i solved this by doing "bower install" after it had set up.

**Comment by eddiemonge** [comment]
ok i am closing this issue then
