### ISSUE TITLE
main.js empty when using coffescript

### ISSUE THREAD

**Issue by dotch** [yeoman/generator-webapp_DEPRECATED#233]
I was using the generator with coffeescript.
However, when doing a build, the resulting main.js in the dist folder is empty.
Using serve works, using serve:dist does not work.

**Comment by eddiemonge** [comment]
Did you add anything to the `main/scripts/main.coffee` file? If not, it should be empty since console.log's get stripped from the file

**Comment by dotch** [comment]
I did add Code there.

**Comment by eddiemonge** [comment]
You're right. I see what the problem is. Working on a fix
