### ISSUE TITLE
Yo Webapp Exit Code of #128

### ISSUE THREAD

**Issue by simara001** [yeoman/generator-webapp_DEPRECATED#235]
After installing bower, yo, grunt, (everything ok) I use $ yo webapp or $ yo angular and I am still receiving the same error:

 Failed to execute "git ls-remote --tags --heads git://github.com/components/jquery.git", exit code of #128 

I have tried cleaning the cache of bower, npm, I checked $ brew doctor, everything ok. Any ideas?

**Comment by sindresorhus** [comment]
That's Bower, not this generator.

https://github.com/bower/bower/issues/50
