### ISSUE TITLE
Grunt bower-install

### ISSUE THREAD

**Issue by changalberto** [yeoman/generator-webapp_DEPRECATED#236]
How much effort would it require to improve on bower-install to accept?

```
    'bower-install': {
        app: {
            src: '<%= yeoman.app %>/{,*/}*.html',  <<<-----------
            ignorePath: '<%= yeoman.app %>/'
        }
    }
```

Instead of:

```
    'bower-install': {
        app: {
            src: ['<%= yeoman.app %>/index.html', ...],   <<<-----------
            ignorePath: '<%= yeoman.app %>/'
        }
    }
```

**Comment by changalberto** [comment]
Sorry — I know I've asked for this a few times already. And I see the progress happening. I just want to make one last effort to push it towards this direction if no one against it.

**Comment by sindresorhus** [comment]
@stephenplusplus

**Comment by eddiemonge** [comment]
should probably close this here and open it on the appropriate repo
