### ISSUE TITLE
Myth as install option

### ISSUE THREAD

**Issue by itmustbe** [yeoman/generator-webapp_DEPRECATED#243]
I'd love an option to use http://myth.io alongside the other options like Sass with Compass. I know about https://github.com/sindresorhus/grunt-myth but it'd be nice just to have as an option when running generator-webapp.

**Comment by addyosmani** [comment]
At the moment, we're working on making this generator more lean (see #168). This helps us keep it super-focused and able to help keep the scaffolding process fast for more general users.

We're also working on a feature called composability, which will make it super-easy to add in options like Myth or other CSS frameworks to your setup in the near future.
