### ISSUE TITLE
Destination not written because minified CSS was empty.

### ISSUE THREAD

**Issue by maxbrodie** [yeoman/generator-webapp_DEPRECATED#244]
Unlike #221, I didn't choose SASS / Bootstrap when configuring the generator. I also ran npm update -g as suggested in #221. This is my first time using yeowman - let me know what info I can provide to help debug.

**Comment by haydenbleasel** [comment]
Which file is causing the error? If it's `vendor.css`, refer to [this issue](https://github.com/yeoman/generator-webapp/issues/242). If not, copy your `grunt build` output into a gist and I'll take a look at it.

**Comment by maxbrodie** [comment]
Yup, that was it. Originally it was main.css that wasn't being generated, but npm update -g probably solved that. Thanks!
