### ISSUE TITLE
coffeescript problem?

### ISSUE THREAD

**Issue by jpuncle** [yeoman/generator-webapp_DEPRECATED#247]
I want to use coffeescript in my project, but it occurs some problems.

The generated `main.js` content is empty, so I changed the `index.html` to the following:

```
<!-- build:js(.tmp) scripts/main.js -->
<script src="scripts/main.js"></script>
<!-- endbuild -->
```

It is ok

**Comment by eddiemonge** [comment]
What version of the generator are you using? Have you updated? I fixed that problem a few versions ago

**Comment by jpuncle** [comment]
yes, the new version is ok, thanks
