### ISSUE TITLE
combine bower css and my css problem?

### ISSUE THREAD

**Issue by jpuncle** [yeoman/generator-webapp_DEPRECATED#248]
This generator use autoprefixer to process css, so the css files are in `.tmp` when build.

I want to combine bower css and my css as following:

```
<!-- build:css({.tmp,app}) styles/main.css -->
<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="bower_components/alertify/themes/alertify.core.css">
<link rel="stylesheet" href="styles/alertify.my.css">
<!-- endbuild -->
```

But the 'main.css' is both in '.tmp' and '.app', so it is included twice.

How should I resolve this problem? Thanks.

**Comment by eddiemonge** [comment]
it should only be grabbing the one from tmp, not from app.

**Comment by jpuncle** [comment]
yes, I want to use `.tmp` only, but the bower_components folder have many files those have no spec, so I can't decide which files should be copied to '.tmp'.

**Comment by eddiemonge** [comment]
you shouldnt manually be copying or using anything in tmp. The grunt tasks use that as a temporary location when processing the files for the build or for serving compiled assets from. You should only be editing files in app

**Comment by addyosmani** [comment]
In order for us to help with this issue further, could you please share your gruntfile? With the info provided so far I can't quite tell if you're doing anything else with stylesheet copying over into the .tmp directory manually.

**Comment by eddiemonge** [comment]
closing due to no response.
