### ISSUE TITLE
Question: font-awesome and yeoman

### ISSUE THREAD

**Issue by dbrans** [yeoman/generator-webapp_DEPRECATED#25]
Searching google for "font-awesome yeoman" offers up issues with integrating font-awesome and yeoman... but no solution or recommended integration method.

Could someone point me to a resource for integrating font-awesome into a vanilla yo webapp?

Thanks.

**Comment by dbrans** [comment]
This seems to work. I'm not sure it's the "right" way.

After `bower install --save font-awesome`, modify main.sass:

``` sass
$fontAwesomePath: "/components/font-awesome/font"

@import font-awesome/sass/font-awesome.sass

$baseFontFamily: "FontAwesome"

@import sass-bootstrap/lib/bootstrap

/* disable bootstrap icons in favor of font-awesome */
[class^="icon-"], [class*=" icon-"], .icon-white
  background-image: none

```

**Comment by chriskjaer** [comment]
You should include font-awesome after bootstrap. That way it will overwrite bootstraps defaults. Like this:

``` scss
@import 'sass-bootstrap/lib/bootstrap';
@import 'font-awesome/sass/font-awesome.scss';
```

Much cleaner :)

**Comment by Urigo** [comment]
@chriskjaer  That's great. how do you copy the fonts folder when you deploy?
Right now i'm using grunt copy task but I can see that in the current generator, the javascript files are being copied by usemin task with index.html annotations.
Should we use the same method with the fonts folder?
