### ISSUE TITLE
CoffeeScript optimizations

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp_DEPRECATED#251]
The generator should convert Gruntifle.js to Gruntfile.coffee if `--coffee` flag is on.

I might do this one, if it's approved.

Also, why is support for CoffeeScript implemented as a command option, instead of where all the other settings are, for Sass & Compass etc? It's easy to miss it.
- ~~Gruntfile.coffee~~
- ~~jshint > coffeelint~~
- [x] make the Gruntfile watch `Gruntfile.coffee` (`Gruntfile.{js,coffee}`)

**Comment by eddiemonge** [comment]
Its hidden behind a flag because unlike Sass, which is an actual recommendation made by the team, CoffeeScript is a 'we will support it as well since some people want it'.

As for the Gruntfile, its a toss up. On one hand, yes if you use CS, its nice having all CS files. On the other hand, it means we have to maintain two versions of the same file and any changes made to one have to be made to the other and people may not always know how ot do that.

**Comment by silvenon** [comment]
Or you could just convert the Gruntfile with [js2coffee](https://github.com/rstacruz/js2coffee) and let us clean up whatever output we get, though that tool is pretty good at it.

I still see no point in hiding it if you support it. For example, I don't read READMEs for generators, I just let Yeoman ask me questions, then I hop right into the Gruntfile and package.json to see what awesome stuff did you guys automate for us. The only reason why I suspected you were hiding CS somewhere was because for a brief moment I saw "coffee" in all that huge npm output.

Maybe you could do something like this?

```
[?] What more would you like? (Press <space> to select)
 ⬢ Sass with Compass
 ⬢ Bootstrap
 ⬢ Modernizr
❯⬡ CoffeeScript

<space>

[?] What more would you like? (Press <space> to select)
 ⬢ Sass with Compass
 ⬢ Bootstrap
 ⬢ Modernizr
❯⬢ CoffeeScript (fuck you)
```

**Comment by eddiemonge** [comment]
Have you tried the -- help option? `yo webapp --help`

**Comment by silvenon** [comment]
I wasn't aware of that option. Though the output of that command seems a bit incomplete too, it doesn't mention Compass and Modernizr, and CoffeeScript is still kinda hidden, unlike the readme of this repo. But that's a different issue, I guess.

**Comment by addyosmani** [comment]
@silvenon if you would like to open up an issue about us improving the output of that command we would be more than happy to entertain suggestions. We've been actively trying to minimize the number of prompts we present our users based on feedback and CS was one of those features that made more sense as an argument.

**Comment by silvenon** [comment]
Sure, I'd like to do that. I guess it does make sense, I'll open an issue to make it more prominent.

I don't know why I closed this issue, it was initially meant for converting Gruntfile to CS, which I believe is a good idea with the `--coffee` flag and it won't alter your workflow. Assuming you won't mind, I'll reopen.

**Comment by silvenon** [comment]
I converted this thread into CoffeeScript optimizations in general. I will add tasks in the first post. Currently I noticed [jshint](https://github.com/yeoman/generator-webapp/blob/v0.4.7/app/templates/Gruntfile.js#L125-L136) should really be coffeelint. I hope that makes sense.
