### ISSUE TITLE
Splitting tasks into files

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp_DEPRECATED#256]
The config object can grow very big very quickly, then you find yourself constantly browsing through 700 lines of code. It would be much easier to split them into files in a `grunt` folder, for example:

```
grunt
  |-- concat.js
  |-- copy.js
  |-- usemin.js
  |-- ... 
```

Then use `grunt.loadTasks("grunt")` to load them all. There are couple of gains here:
- much faster browsing
- easy to add new tasks
- no more wasting time thinking about where exactly to put a task configuration

It's a lot of work to do each time, so it would be nice to have it from the start.

I can submit a PR if you approve.

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/yeoman/generator-webapp/pull/245

**Comment by silvenon** [comment]
Shoot, forgot to search.
