### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp_DEPRECATED#257]
Perhaps a `Gemfile` could be created and bundled for the users who choose Sass & Compass.

**Comment by sindresorhus** [comment]
Ya, that's a good idea. Most people don't know about it, but it's a nice way to lock your Ruby deps. We would need to use the `bundleExec` option in grunt-contrib-compass. PR welcome.

**Comment by silvenon** [comment]
Will do.
