### ISSUE TITLE
BUG: copy task config output unprocessed

### ISSUE THREAD

**Issue by creynders** [yeoman/generator-webapp_DEPRECATED#259]
I'm pretty certain this is a bug with the current version, after scaffolding the `copy` task `src` looks like this:

``` javascript
src    : [
    '*.{ico,png,txt}', '.htaccess', 'images/{,*/}*.webp', '{,*/}*.html', 'styles/fonts/{,*/}*.*',
    'bower_components/' + (this.includeCompass
    ? 'sass-'
    : '') + 'bootstrap/' + (this.includeCompass
    ? 'fonts/'
    : 'dist/fonts/') + '*.*'
]
```

@silvenon could it be this is the result of your PR's?

**Comment by silvenon** [comment]
Yes, it could be, but I'm pretty sure that was a bug before my PR too. If you check the diff of my PR, you'll see that I just used the same coding style. Or perhaps I did make a mistake.

Anyway, I'll fix this in a few hours.

**Comment by eddiemonge** [comment]
should be fixed now
