### ISSUE TITLE
Project paths

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp_DEPRECATED#265]
These yeoman project config paths seem a bit unnecessary to me. Sooner or later we're going to use a function in our configuration, then we'll have to hardcode paths (like in #263), which makes the existence of variables pointless.

`app` is shorter and more readable than `<%= yeoman.app %>`.

**Comment by silvenon** [comment]
Paths can be changed with a simple search and replace.

**Comment by sindresorhus** [comment]
> which makes the existence of variables pointless.

Why is it pointless?

> Paths can be changed with a simple search and replace.

Yes, but not everyone is comfortable with that. I see no harm in making it easy.

**Comment by silvenon** [comment]
It's pointless if there are some place where you have to hardcode the value of a variable, because the whole point of variables is that you can change them all in one place, which isn't the case if they are hardcoded in some places. But I was wrong, you don't have to hardcode the values if you declare the config object outside of `grunt.initConfig`.

The harm is having to type `<%= yeoman... %>` every time, and it's less readable.

**Comment by sindresorhus** [comment]
> The harm is having to type <%= yeoman... %> every time, and it's less readable.

We can make it shorter.

**Comment by silvenon** [comment]
Alright, closing this then.
