### ISSUE TITLE
Dealing with timeouts

### ISSUE THREAD

**Issue by amboy00** [yeoman/generator-webapp_DEPRECATED#271]
When running `yo webapp`, I'm consistently getting this error:

``` sh
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Operation timed out
```

Doing some googling, I figured that the network I'm working in may be the culprit.  Someone posted a PR to another repo to get about this issue.

https://github.com/alindeman/upgradingtorails4/commit/8093da7eb3db86853041192791698c938aa7573d

Has anyone else run into this problem?

**Comment by eddiemonge** [comment]
at what point does that happen? 

@SBoudrias was this what you were talking about?

**Comment by SBoudrias** [comment]
Well, you have a network timeout (internet's not working or proxy issues) and the generator fails rather than continuing without the information.

**Comment by SBoudrias** [comment]
Well, note that the failure may be triggered by any packages I  the way. Without the trace this is not really useful...

**Comment by amboy00** [comment]
It's definitely a timeout error, and it happens randomly, so this may be more on me or at least the company I'm working on site with. :-/

This time it happened at pulling down autoprefixer.

```
grunt-autoprefixer@0.5.0 postinstall /Users/chriswilliams/Sites/test/node_modules/grunt-autoprefixer

bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/jlong/sass-bootstrap.git", exit code of #128
```

Another time it was Modernizr. Going over to another network (home) solved the problem.

**Comment by sindresorhus** [comment]
Sounds like a firewall blocking Bower.

**Comment by collinforrester** [comment]
We have that issue here at work and it is caused by the firewall blocking the git protocol.  Refer to sindresorhus's answer here to see if it works for you http://stackoverflow.com/questions/15669091/bower-install-using-only-https

**Comment by amboy00** [comment]
@collinforrester @sindresorhus Perfect! Thank you. _dancing gif_
