### ISSUE TITLE
Exceptions on execution beginning and never finished

### ISSUE THREAD

**Issue by oaleynik** [yeoman/generator-webapp_DEPRECATED#273]
Hi,

I've faced an issue with webapp generator on Windows 8.1 Pro Build 9600 x64.

Regardless of set of checked params, on start generator throws two exceptions:
https://www.dropbox.com/s/4qdjtysoeqk16i4/webapp-generator-exception.png

... continues execution and never finished. It stops on this:

https://www.dropbox.com/s/hlzlfewochi93j2/webapp-generator-neverfinish.png

Any suggestions?

**Comment by sindresorhus** [comment]
try reinstalling. looks like your install is corrupt.

**Comment by oaleynik** [comment]
@sindresorhus I've uninstalled it and cleared npm cache. Then I've installed it again. Problem still exists.

**Comment by oaleynik** [comment]
@sindresorhus ok, now it's gone. Pretty strange, however, it was probably an environment issue

**Comment by oaleynik** [comment]
Hey again, it's back.

I've investigated it a bit and here is results.

I've reinstalled nodejs at all and all of the packages.
Than running `yo webapp --skip-install` successfully scaffold web app.
`bower install` works like a charm, but I can't tell it about `npm install`. It fails on grunt-contrib-imagemin with the next output:

npm ERR! Error: shasum check failed for C:\Users\Oleg\AppData\Local\Temp\npm-944-k65S8kDU\1392315665390-0.004815640859305859\tmp.tgz
npm ERR! Expected: 2a6ddfa43de542bcefd4145cc861b16d9a943443
npm ERR! Actual:   c5328643b4746f7727e520a034f635ada56db432
npm ERR! From:     https://registry.npmjs.org/pngquant-bin/-/pngquant-bin-0.1.5.tgz
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "grunt-contrib-imagemin@~0.2.0"
npm ERR! cwd D:\Coding\home...tmp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Coding\home...tmp\npm-debug.log

Than I've tried to install the grunt-contrib-imagemin standalone using the version specified in generated package.json like `npm install grunt-contrib-imagemin@~0.2.0`
It repeats error. However, the latest version of imagemin 0.5.0 installs well.

**Comment by kmile** [comment]
We are having the same issues with checksums in pngquant-0.1.5. I guess that was packaged with a wrong checksum? Or maybe packaged using a version of `npm` that had issues with the checksum (which it seemed to have a while ago: http://stackoverflow.com/questions/20629788/shasum-check-failed-for-installing-phone-gap-using-npm#comment30911761_20630821)

**Comment by krolow** [comment]
same issue here

**Comment by oaleynik** [comment]
@kmile @krolow NPM is pretty unstable lately. pngquant successfully can be installed from NPM without version specified. Workaround for your issue is the same:

`npm install pngquant` and check the version installed
Than running `yo webapp --skip-install` scaffold web app
Change the version of pngquant in package.json to determined in first step
Than run `npm install`

**Comment by oaleynik** [comment]
The same issues affect generator-angular

**Comment by krolow** [comment]
@oaleynik thanks for the workaround ;)
