### ISSUE TITLE
How do I access images that have been revved with my scss

### ISSUE THREAD

**Issue by fluke** [yeoman/generator-webapp_DEPRECATED#277]
I'm using Yeoman to build my webapp but my images aren't showing up on looking through assets I realised that the image assets are getting prefixes.

```
dist/images/e8c3168a.small-clouds.png
```

As they should but the css still compiles to the standard image

```
Failed to load resource: the server responded with a status of 404 (Not Found) .../images/small-clouds.png
```

In Rails this was solved by using image-url(); sass mixin. How can I use the prefixed images in my yeoman build. Perhaps replace the images in the scss with their prefixed alternatives.

**Comment by silvenon** [comment]
I think [grunt-smartrev](https://github.com/disqus/grunt-smartrev) might be the solution.

**Comment by fluke** [comment]
Yeah that sounds like the right idea. Any chance this could be built into Yeoman.

**Comment by silvenon** [comment]
I didn't have time to check out grunt-smartrev vs. grunt-rev yet, but it seems very probable.

**Comment by silvenon** [comment]
What is super-confusing now is that there is a [grunt-filerev](https://github.com/yeoman/grunt-filerev) plugin maintained by the Yeoman team, which seems to play nicely with grunt-usemin, but at the moment I don't know what's the difference between grunt-filerev and grunt-rev, they seem very similar.

I hope this gets cleared up.

**Comment by silvenon** [comment]
@kartikluke Actually, after studying grunt-usemin for a while and managing to get my build process to finish successfully, I think you're doing something wrong if the URLs don't get updated for you. grunt-usemin is in charge for updating URLs and it does it well.

Can you share with me more info about your configuration and project structure?

**Comment by fluke** [comment]
I have this `#parallax-1{background:url(../images/large-clouds.png) 0 0 repeat transparent;z-index:-100}` line in my styles.css in the styles folder of yeoman and I've added the line

```
<!-- build:css(.tmp) styles/main.css -->
<link rel="stylesheet" href="styles/main.css">
<link rel="stylesheet" href="styles/styles.css">
<!-- endbuild -->
```

It doesn't get replaced.

Okay this message shows in the log:

```
Running "usemin:css" (usemin) task

Processing as CSS - dist/styles/787edb7d.main.css
Update the CSS to reference our revved images
```

But the image isn't getting updated.

**Comment by fluke** [comment]
https://github.com/yeoman/yeoman/issues/824#issuecomment-32691465

Running "usemin:css" (usemin) task

```
Processing as CSS - dist/styles/787edb7d.main.css
Update the CSS to reference our revved images
url(../images/large-clouds.png) changed to url(../images/bc71aa61.large-clouds.png)
url(../images/medium-clouds.png) changed to url(../images/3566c936.medium-clouds.png)
url(../images/small-clouds.png) changed to url(../images/e8c3168a.small-clouds.png)
```

Found the issue in grunt-usemin

Thanks anyway. Didn't know the exact problem so I couldn't find the answer previously.
