### ISSUE TITLE
revving files that refer to revved files

### ISSUE THREAD

**Issue by salomvary** [yeoman/generator-webapp_DEPRECATED#280]
Reposted from https://github.com/yeoman/yeoman/issues/1228

Looks like revved files filename doesn't change if any of the revved files change which it refers to. Not sure this is a bug/lack of feature in grunt-rev or grunt-usemin or the way they are integrated by yeoman, therefore submitting here.

Example:

```
yo webapp:app
# answer no to every option
echo "body{background-image: url(images/bg.jpg)}" >> app/styles/main.css 
wget -O app/images/bg.jpg http://placekitten.com/196/196
grunt build
```

Grunt output:

```
[...]
Running "usemin:css" (usemin) task

Processing as CSS - dist/styles/80362b61.main.css
Update the CSS to reference our revved images
url(images/bg.jpg) changed to url(images/93516094.bg.jpg)
```

Checksums:

```
MD5 (dist/images/93516094.bg.jpg) = 4771130e50bc62254221117e7f7b2bf2
MD5 (dist/styles/80362b61.main.css) = b7bf699e8a5482019a15e7c8de75b3d6
```

Modify an image referred from css:

```
wget -O app/images/bg.jpg http://placekitten.com/80/80
grunt build
```

Grunt oputput:

```
[...]
Running "usemin:css" (usemin) task

Processing as CSS - dist/styles/80362b61.main.css
Update the CSS to reference our revved images
url(images/bg.jpg) changed to url(images/7c7b7c0e.bg.jpg)
```

Checksums:

```
MD5 (dist/images/7c7b7c0e.bg.jpg) = 0ef2542de2db26f233b5bd93fbf4494f
MD5 (dist/styles/80362b61.main.css) = 1704bd1dc14f48ce4f8580844954e12f
```

**The issue**: the file name of main.css did not change while its content did (by rewriting the url() reference to an image which changed). 

Output of
`yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js`:

https://gist.github.com/salomvary/04006a2640da13606a3b

**Comment by silvenon** [comment]
Sounds like an issue with grunt-rev.

**Comment by silvenon** [comment]
@addyosmani This issue was fixed by d493c26092615d4171c1e907a4c8d8a1dee761cd, 67977e0769c293e96c01d8b8346cf8aeaf5d7778 and 13d76d6ed62ec44e10745e298450589bccf66c98, I tested it now and it works fine.

**Comment by silvenon** [comment]
Oh, I'm an idiot, I didn't carefully read the issue. This is still an issue, and a pretty serious one.

**Comment by stevemao** [comment]
Is it still an issue since this is using `grunt-filerev`?

**Comment by silvenon** [comment]
Not sure, I haven't checked.

**Comment by silvenon** [comment]
Now I checked, this has been fixed with `grunt-filerev`. If you modify the image with the same name, it gets a new fingerprint and the its references are updated.

**Comment by jaipandya** [comment]
@silvenon I don't think the issue has fixed, also I think it is not just specific to `filerev` but `filerev` and `usemin` both. According to the issue, if you change `fileA` which is also referred in `fileB`, it correctly changes the hash of `fileA` and usemin updates the reference in `fileB` to the updated hash. But it doesn't change the name of `fileB` to reflect this change in content. This is because changing the reference in a file to updated hashed file is `usemin`'s responsibility but changing the name of the file is `grunt-filerev`'s responsibility. And both run only once.

I ended up using https://gist.github.com/markrian/aa185c5ec66232a38a68 a few days back when I was stuck with this issue. Still, a serious one.

**Comment by silvenon** [comment]
Damn, it's a tough cookie.

Thanks for clarifying the issue. You seem to have a good grip on it, if you'd like to submit a PR, we'd appreciate it. No pressure, though :wink:

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
