### ISSUE TITLE
Inconsistent Indentation

### ISSUE THREAD

**Issue by rwxrob** [yeoman/generator-webapp_DEPRECATED#286]
Noticed when converting from compass to stylus according to this [gist](https://github.com/yeoman/yeoman/wiki/Stylus-integration) that jshint became very unhappy with me, which was when I noticed the default .jshintrc is set to `indent: 4`.

I'd group fixing Gruntfile.js indentation and changing the .jshintrc file with 'reasons some will not use an efficiency' helper.

If no one beats me to it, I'll set everything to 2 space indent (per [Google](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)] and [NPM/Node](https://www.npmjs.org/doc/coding-style.html) JavaScript style standards) and submit a pull request.

**Comment by sindresorhus** [comment]
4 spaces is what we've chosen for the scaffolding. We're planning to implement functionality to make that configurable.

**Comment by rwxrob** [comment]
Is there any reason you decided to not go with the rest of the node and JavaScript community?

**Comment by aendra-rininsland** [comment]
+1 to @robmuh's question. It also goes against [Yeoman's own style guide](http://yeoman.io/contributing/style-guide.html):

> This project uses single-quotes, **two space indentation**, multiple var statements and whitespace around arguments.

(Emphasis mine.)

**Comment by eddiemonge** [comment]
yup it can change but no one has pr'ed it yet
