### ISSUE TITLE
Any plans on switching to bootstrap-sass-official instead of sass-bootstrap?

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#288]
Now that Bootstrap 3.1 officially supports SASS, is there any plan to offer this as an option?

**Comment by kevva** [comment]
Yes.

**Comment by ghost** [comment]
Thumbs up!

**Comment by kevva** [comment]
Going to leave this open until we've implemented it.

**Comment by ghost** [comment]
Oops sorry about that. Thanks, Kevin!

**Comment by kevva** [comment]
Already implemented https://github.com/yeoman/generator-webapp/commit/4c49ef9621faa28fbeb319d21337dab3a11d6aa0.

**Comment by ghost** [comment]
When is this going live (so `npm update -g` will fetch it?)
