### ISSUE TITLE
LiveReload Redundant?

### ISSUE THREAD

**Issue by rwxrob** [yeoman/generator-webapp_DEPRECATED#289]
Just reading this on grunt-contrib-livereload saying livereload is deprecated. Are we keeping the livereload in this webapp generator because we support back versions? Otherwise can it be removed from the generator?

**Comment by kevva** [comment]
Yep, should remove it.

**Comment by eddiemonge** [comment]
We aren't using grunt-contrib-livereload, we are using grunt-contrib-watch. Livereload isn't deprecated, grunt-contrib-livereload is.
