### ISSUE TITLE
Feature request: Change copy:dist from matching a "whitelist" to matching "all files minus a blacklist"

### ISSUE THREAD

**Issue by strille** [yeoman/generator-webapp_DEPRECATED#293]
I have only recently started using this generator, but have run into cases where not all my files were copied to the dist folder (.pdf, .json among others).

Would it be possible to not try to match all the files to copy but instead first match all files and then exlude a list of files (concatenated css/js, optimized image files etc.)? Or am I missing something here and it's a lot more complicated to do than I realize?

It would certainly be more robust. In case there's a bug in the matching rules, I would rather have some unnecessary files being copied than missing to copy critical files.

The comment  "Copies remaining files to places other tasks can use" in the Gruntfile actually makes it sound like it already works this way, so at the very least I think this comment should be rephrased to something like "Copies matching files to places other tasks can use. Add additional file extensions relevant to your project".

Regards, Strille

**Comment by sindresorhus** [comment]
> It would certainly be more robust. In case there's a bug in the matching rules, I would rather have some unnecessary files being copied than missing to copy critical files.

There are equally many that don't. We actually did the opposite previously, but had to switch because of a lot of complaints.
