### ISSUE TITLE
compass:server running really slow

### ISSUE THREAD

**Issue by fluke** [yeoman/generator-webapp_DEPRECATED#294]
```
Running "compass:server" (compass) task
overwrite .tmp/styles/main.css (7.705s)
Compilation took 7.71s

Running "autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/styles/main.css" created.

Done, without errors.


Execution Time (2014-03-04 15:49:54 UTC)
compass:server     10.2s  94%
autoprefixer:dist  689ms   6%
```

**I looked up the grunt-contrib-compass plugin and I found this issue. So it seems that there isn't a way to fix this. As of now it's closed but if anyone could take a look at that and come up with some solutions that would be great.**
https://github.com/gruntjs/grunt-contrib-compass/issues/89

This task takes a lot of time to complete and causes compiling to take forever. Is there another way to compile my scss without breaking the Yeoman workflow.

**Comment by fluke** [comment]
In the setup I was given the option of Sass with Compass. Not selecting that would remove Sass entirely or just Compass?

**Comment by kevva** [comment]
It would remove Sass completely. You could try using https://github.com/sindresorhus/grunt-sass which is much faster if you don't need Compass support.

**Comment by eddiemonge** [comment]
or you could switch to stylus which is super fast

**Comment by kevva** [comment]
Or Rework. But that might be beside the point here.

**Comment by sindresorhus** [comment]
Or CSS, it's much faster.

**Comment by kevva** [comment]
Could still write CSS and preprocess it with Rework (inline `@imports` for example) :PpPp. Also, variables is nice.

But yeah, not as fast as one big `main.css` file with 500+ LOC :horse:.

**Comment by fluke** [comment]
I've made the switch to grunt-sass and it's tons better. Do you think we could make it an option to run grunt-sass instead of compass when you're setting up. 

Also how do I go about making a custom version of this with npm update still working, etc.

**Comment by craig-o-curtis** [comment]
Slow... my compass server takes between 30 and 45 seconds on Mac El Capitan.  On my work Dell it takes 2-3 seconds.
