### ISSUE TITLE
Scripts in app/components can't be concatenated

### ISSUE THREAD

**Issue by callumlocke** [yeoman/generator-webapp_DEPRECATED#30]
(Not 100% sure if the bug is specific to this repo, let me know if I should move it.)

A friend at my office just told me this morning that his component scripts weren't being included in his concatenated output. He had a build block something like this:

```
<!-- build:js scripts/main.js -->
<script src="scripts/thing.js"></script>
<script src="components/jquery/jquery.js"></script>
<script src="components/something/else.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```

...but the resulting `dist/scripts/main.js` did not contain either of his `components/**.js` scripts. It was just the concatenated result of `scripts/thing.js` and `scripts/main.js`, with no jQuery or other components.
### Verifying the bug

I couldn't replicate this on my existing project (which I made using `yo webapp` a few days ago). But then I updated yo, grunt, and bower and created a new project, and I was able to replicate the bug, on a `yo webapp`–generated project, right out of the box:

```
mkdir testgrunt && cd testgrunt
npm install -g yo grunt-cli bower
yo webapp
  # ('no' to Bootstrap for Sass)
  # ('no' to RequireJS)
npm install && bower install
```

All the above completed successfully. Had a look at the directory structure; all seemed correct. Then:

```
grunt
```

Here is the command output: https://gist.github.com/callumlocke/5089736 (It all looks correct.)

But my `dist/scripts/main.js` file contains only the following line:

```
console.log("'Allo 'Allo!");
```

It **should** contain jQuery before that line, because `app/index.html` contains this:

```
<!-- build:js scripts/main.js -->
<script src="components/jquery/jquery.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```
### Workaround

I tried changing the name of the output file, like this:

```
<!-- build:js scripts/foo.js -->
<script src="components/jquery/jquery.js"></script>
<script src="scripts/main.js"></script>
<!-- endbuild -->
```

Now it works – when I run `grunt`, I get a complete `dist/scripts/foo.js`, consisting of jQuery followed by `console.log("'Allo 'Allo!");`.

**Comment by kevva** [comment]
This happens because the uglify task overrides the concatenated main.js from the build block in index.html.

``` js
files: {
    '<%= yeoman.dist %>/scripts/main.js': [
        '<%= yeoman.app %>/scripts/{,*/}*.js'
    ]
}
```
