### ISSUE TITLE
Option for Sass without Compass

### ISSUE THREAD

**Issue by fluke** [yeoman/generator-webapp_DEPRECATED#302]
As mentioned in #294 compass runs really slow. One of the suggestions was to use https://github.com/sindresorhus/grunt-sass and I have implemented it. It's much faster now.

Could we have another option for Sass without Compass?

I'm trying to make a custom version for myself. How do I add the option for Sass without Compass to the CLI and set a variable like includeCompass, so as to make the appropriate templates?

**Comment by silvenon** [comment]
That would be a very good improvement. Everything starts from `index.js`, so you can read the docs on [yeoman.io](http://yeoman.io) to see how it works.

The Yeoman team seems to be very careful about how options in this project are structured, so it may be best to wait for their suggestions before submitting a PR.

**Comment by fluke** [comment]
Sure, I'll have a look, if you could spread the idea I would be grateful.

**Comment by silvenon** [comment]
Well, I'm sure the team got the notified, we'll ping them if they don't respond for a while :D

**Comment by fluke** [comment]
Alright. I'll work to make my own generator and I'll submit a pull request if I manage.

**Comment by addyosmani** [comment]
How are things going @kartikluke?

**Comment by fluke** [comment]
This slipped my mind completely, I found it much easier to copy paste the Gruntfile from my other projects. I'll try making it. As silvenon said 

> The Yeoman team seems to be very careful about how options in this project are structured, so it may be best to wait for their suggestions before submitting a PR.

I decided to to wait as he advised.

**Comment by silvenon** [comment]
Yeah, this one is a bit tricky because Compass includes Sass, so on `yo webapp` we can have:
- Sass
- Sass with Compass
- Bootstrap
- Modernizr

But then you can select both "Sass" and "Sass with Compass", which is weird. Maybe we could deselect "Sass" if "Sass with Compass" is selected.

Or perhaps:
- Sass
- Compass
- Bootstrap
- Modernizr

Where "Sass" gets selected automatically (if not already selected) when "Compass" is selected. This is a less weird solution, in my opinion.

**Comment by fluke** [comment]
I'm working on building this. As for the options. I've made it as follows: You can select Sass if Sass is selected it gives you the option to add Compass support as well. The inquirer.js code I've used is below.

```
var prompts = [{
    type: 'checkbox',
    name: 'features',
    message: 'What more would you like?',
    choices: [{
      name: 'Bootstrap',
      value: 'includeBootstrap',
      checked: true
    },{
      name: 'Sass',
      value: 'includeSass',
      checked: false
    },{
      name: 'Modernizr',
      value: 'includeModernizr',
      checked: false
    }]
  }, {
    when: function (answers) {
      return answers.features.indexOf('includeSass') !== -1;
    },
    type: 'confirm',
    name: 'Compass',
    message: 'Would you like Compass as well?',
    value: 'includeCompass',
    default: false
  }];
```

**Comment by fluke** [comment]
And for my templates I'm leaving the includeCompass. And setting my Sass with `includeSass && !includeCompass`

**Comment by fluke** [comment]
I've made a pull request accordingly. Works fine as far as I can see. https://github.com/yeoman/generator-webapp/pull/315

**Comment by eddiemonge** [comment]
> Sass
> Compass
> Bootstrap
> Modernizr
> Where "Sass" gets selected automatically (if not already selected) when "Compass" is selected

I think this would be better but with the Compass text reading: `Compass (Sass will be included too)`

**Comment by fluke** [comment]
@eddimonge So like this? https://github.com/kartikluke/generator-webapp/commit/29a88894bfe234a63c4118b730c4a6320c86e7d3 There doesn't seem to be a way to automatically select a choice. But I think it's fairly obvious and Compass will be set up whether Sass is set as well or not.  
![terminal2](https://f.cloud.github.com/assets/3857139/2490209/3481bac8-b199-11e3-8036-da2d5db11c9f.png)

**Comment by addyosmani** [comment]
I've mentioned this on another thread, but just wanted to ask for opinions on here again: rather than us continuing with the complexity of supporting Compass, what if we dropped support for it and just stuck with pure Sass? That would ensure we kept three options.

**Comment by silvenon** [comment]
@addyosmani I like that idea! :smiley: What do you think, @kartikluke?

**Comment by fluke** [comment]
That was what I planned to do when making my own generator but I had to keep Compass support if I wanted to contribute to the project itself. 

I think it's a much better alternative, people can import a Compass library or something like that if they need it but having grunt-sass do the heavy lifting, especially since it's based in Node.js, is a great idea.

If we all agree I'll make the changes to my pull-request which should probably undergo some testing.

**Comment by sindresorhus** [comment]
I've suggested this multiple times, but I haven't had the time to follow this up.

Though there should be an option between grunt-sass (libsass) and grunt-contrib-sass (ruby sass) as libsass while relatively stable is missing a lot of recent functionality.

**Comment by silvenon** [comment]
I think we should always give them Ruby Sass because it has an expected set of features, and devs who know about libsass will easily switch over. Having to choose between the two may confuse beginners.

Or, we could have a follow-up prompt which asks them whether they want Ruby Sass or libsass. Because the change seems too small for having it as a separate option in the initial list of options.

**Comment by sindresorhus** [comment]
Second option sounds fine to me. It should explain to the user the difference. Faster, but missing some features.

**Comment by fluke** [comment]
As long as it takes less than a couple seconds to compile I'm game.

**Comment by silvenon** [comment]
Yeah, it should explain the difference. Cool, I like this idea very much.

**Comment by fluke** [comment]
Alright I'll get at it. Though I still don't know why the follow up question I put for compass didn't show for you @silvenon

**Comment by silvenon** [comment]
Oh, I forgot to answer that one. Because I didn't know it was implemented as a follow-up question, I just looked at the first set of options and then stopped. So everything's fine.

**Comment by fluke** [comment]
Alright @silvenon I think it have it working. https://github.com/yeoman/generator-webapp/pull/315 According to what @sindresorhus said. Have just Bootstrap, Sass and Modernizr with a follow up question.   

![screenshot from 2014-03-24 01 51 34](https://f.cloud.github.com/assets/3857139/2494500/c705a924-b2c8-11e3-8c13-436419d6c06a.png)

**Comment by addyosmani** [comment]
It's encouraging to see us heading in this direction. I do think we need to be careful about how we implement the grunt-sass vs grunt-contrib-sass options. 

In my opinion, the way we present the two options above may confuse the longtail of developers who just want us to make a call about what they should be using to get sass into their workflow.

Does anyone else feel this way? I'd almost be tempted to say we should opt for one option and allow you to override the choice via a flag. Open to alternative opinions if the above representation makes more sense.

(Thanks btw to everyone that has been working on this!)

**Comment by silvenon** [comment]
I was thinking about this also, but I really like the option above as a transitional phase towards grunt-sass. libsass isn't stable enough, so I think it's important to tell the developers that so they don't spend time trying to make some hot new Sass feature work, only to realize it's not yet supported by libsass.

If we want to be as little confusing as possible, we would have to make grunt-contrib-sass the default and have grunt-sass as a flag, but I think that approach wouldn't help us if we some day want to transition to grunt-sass completely. Also, flags are annoying and I always forget them :P

**Comment by fluke** [comment]
grunt-contrib-sass is definitely a better choice since the speed difference isn't that much, and it supports a wide range of things. Though you need to have the gem installed.

Going for that extra bit of speed through a flag is definitely a better choice.

I definitely would get confused by the options and would have to look up both options before I proceeded. Given that I don't know which features are missing and such. Let me know what is decided and I'll work it in.

**Comment by fluke** [comment]
I've implemented the flags. We can rollback if we decide against it.

The flag is `--libsass`.

**Comment by silvenon** [comment]
There is a significant speed gain, libsass compiles in under a second, while the gem can take couple of seconds and Compass even a dozen seconds.

But ok, I guess I'll live with a flag :P

**Comment by sindresorhus** [comment]
I don't like the use of flag here. Most people won't know about it or use it. We're also trying to move away from flags as we intend to implement persistent prompt choices; so you only have to answer them once.

> Faster, but missing some features.

This was not meant to be the actual text. It has to be better explained than this. Should probably include an url for where people can read about the difference and what features that are missing.

**Comment by fluke** [comment]
So what should we do about it till persistent prompt choices are implemented. We could explain it better in the readme along with the other options. We could expect them to read that, if not we decide what's best. As @addyosmani said:

> In my opinion, the way we present the two options above may confuse the longtail of developers who just want us to make a call about what they should be using to get sass into their workflow.

**Comment by addyosmani** [comment]
If we have clearer text, I'm down with the two prompts. It just needs to be as clear as we can make it :)

**Comment by silvenon** [comment]
We should also in some way say "choose Ruby Sass if you want everything working, choose libsass if you're a power user and you know what you're doing". That way they can instantly choose Ruby Sass if they don't know what libsass is or does.

**Comment by silvenon** [comment]
Maybe we could only ask if they want libsass, not make them choose between the two. That way we can present it as a sort of an optional enhancement/risk.

So many ways to implement this :smiley:

**Comment by fluke** [comment]
Having too much text in the prompt would be confusing. We can have a confirmation whether they want libsass and link them to a page in the wiki explaining the differences.

That way we can make it as clear as we want, while keeping the prompts minimal.

**Comment by fluke** [comment]
Okay there's no wiki but we can make a **libsass.md**

**Comment by silvenon** [comment]
Yes, that sounds great. We'll see what others think.

**Comment by fluke** [comment]
I've implemented this line of thought. Hopefully it'll stick :P

**Comment by silvenon** [comment]
Nice :+1: I feel like I'm pushing my preferences to hard, sorry, which solution do you like best @kartikluke?

**Comment by fluke** [comment]
Anything that will get rid of that nasty 10s compass build time.

**Comment by fluke** [comment]
PR got pulled. Thanks everybody.

**Comment by silvenon** [comment]
Good job! :hatched_chick:

**Comment by digitaljhelms** [comment]
Can't wait for this to drop! When's the next release scheduled?

**Comment by fluke** [comment]
I'd like to know as well. Should probably finish this first. https://github.com/yeoman/generator-webapp/issues/326

**Comment by silvenon** [comment]
@digitaljhelms

``` sh
$ git clone https://github.com/yeoman/generator-webapp
$ cd generator-webapp
$ npm link
```

Now `yo webapp` will use the latest version, i.e. from the `generator-webapp` directory. Then each time you want to update the generator, just navigate to `generator-webapp`, `git pull origin master` and that's it!

**Comment by aaronbalthaser** [comment]
Hello there, I didn't have time to read all the comments but from what I read and what I see in the generator-webapp options you no longer have compass. This is unfortunate for me since my personal sass boilerplate depends on compass and susy which I have been having trouble integrated with the latest build. I am not a grunt ninja, just know enough to get by. Any tips on how to get add compass and susy to the app or do I have to go through an entire course learning the in and outs of grunt.js?

**Comment by silvenon** [comment]
You wouldn't have to do anything dramatic, [here](https://gist.github.com/silvenon/11271918)'s the diff of the changes you would have to make. Note that this is not the diff Git would create, I made it a bit easier to read.

I didn't test this, but I'm pretty sure it works.

**Comment by silvenon** [comment]
I suggest learning a bit about Grunt, there's a big chance you'll have to modify something eventually, and that's hard to do if you don't know what's going on. (I learned a lot about Grunt just by messing around with this project, so that's a good place to start.)

**Comment by aaronbalthaser** [comment]
Thank you, I appreciate the time you took to assist me. I also downloaded some extensive video courses to learn.

**Comment by silvenon** [comment]
No problem, can you read that diff? I forgot to mention, you also have to do:

```
npm install --save-dev grunt-contrib-compass
```

**Comment by aaronbalthaser** [comment]
Hello, I am getting the following error. Not sure what to do about it. I am fairly new at this. I know I do have compass installed @ the system level in Library/Ruby/2.0.0/gems/compass-core-1.0.0.alpha.19. Any ideas?

Warning: Running "compass:server" (compass) task
    Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

**Comment by silvenon** [comment]
You don't have `compass` installed in your path. What do you get when you run `which compass`?

**Comment by aaronbalthaser** [comment]
Your right, I get nothing. Maybe when I installed the new codekit something was changed. How do I fix this?

**Comment by silvenon** [comment]
Assuming you don't have similar problems with binaries from other gems (like rails, sass etc.) you can try running `gem prune compass`.

**Comment by aaronbalthaser** [comment]
I actually ran sudo gem install compass --pre and everything seems to work now. I am curious about the command you just posted.

**Comment by silvenon** [comment]
My command was wrong, I meant `gem pristine compass`, which tries to fix stuff which is broken about a gem (in your case, install a binary). Cool, I'm glad that it works!

**Comment by aaronbalthaser** [comment]
Again I express my appreciation for you taking the time to assist. Thank you.

**Comment by udoschmitz** [comment]
This is unfortunate. I'm just trying Yeoman for the first time and was irritated to not find options to use compass :-/ Like aaronbalthaser I want to use Compass and Susy. Wouldn't it be an option to have an alternate generator-webapp-with-compass? Editing Gruntfile.js and "npm install --save-dev grunt-contrib-compass" kinda defeats the purpose?

**Comment by silvenon** [comment]
The purpose of this generator is to provide a basic set of common tasks, which you can then alter and expand. Even if supporting every tool and preprocessor was possible to implement, it would clutter the code beyond maintainability.

You can create your own fork of this generator:

``` sh
$ git clone https://github.com/yeoman/generator-webapp
$ mv generator-webapp generator-webapp-with-compass
$ cd generator-webapp-with-compass
# implement Compass
$ npm link
```

Then you can use `yo webapp-with-compass` :sunglasses:

**Comment by udoschmitz** [comment]
Yup. As I just noticed that I would have to add Susy manually anyway (http://ericdfields.com/post/installing-compass-frameworks-in-a-yeoman-project) -- maybe that is my best option.
What could possibly go wrong? :-D

**Comment by silvenon** [comment]
Yeah, just have to add a `require: 'susy'` to the Compass task.

**Comment by cjerdonek** [comment]
What is the commit that resolved this issue?  The final comment by @kartikluke before closing just says, "PR got pulled. Thanks everybody."

**Comment by silvenon** [comment]
Sorry, I'm not really sure, the change seems scattered.

**Comment by fluke** [comment]
It's PR #315 I think in the end we just decided to drop Compass. We use either libsass or the sass gem. At least that was the case at the time.

**Comment by cjerdonek** [comment]
Okay, thanks, @kartikluke.  It would have been better if the commit message said that the option to use Compass was taken away.  Currently, it only says that an option was added, which is misleading (unless I am missing something): "Add option for Sass without Compass."

**Comment by fluke** [comment]
It was my intent but after speaking to the project managers we took up
another path.

**Comment by cjerdonek** [comment]
Yes, that's fine.  I was just saying that it's good if the commit message reflects what was done in the patch rather than the initial idea.  Otherwise, it's hard to tell later on.

**Comment by fluke** [comment]
Oh that. I squashed my commit into one. I ought to have changed the commit
message. I'll keep that in mind next time.
