### ISSUE TITLE
imagemin cache problem

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-webapp_DEPRECATED#305]
Hi there, when I use grunt -force to compile my project, my images are not compiled properly when cached and they are completely blank in dist/images folder. 
![screen shot 2014-03-14 at 10 56 31 am](https://f.cloud.github.com/assets/6316590/2416731/233227e2-ab0b-11e3-9b44-c3f1a4354f39.png)

If I modify one of them everything will be fine. Originally there was one huge image in the folder (not sure if this would help to identify the problem) and I shrank it but the problem still exists. I reinstalled imagemin but didn't help. The reason I use -force is I don't have any unit test in my project and I problems in jshint...

Doesn't look like there is any error in the output..
$ grunt -force
Running "newer:jshint" (newer) task

Running "newer:jshint:all" (newer) task

Running "jshint:all" (jshint) task

app/scripts/main.js
  line 6   col 5   Missing "use strict" statement.
...

app/scripts/svgcheckbx.js
  line 8   col 22  A leading decimal point can be confused with a dot: '.2'.
...

✖ 43 problems

Warning: Task "jshint:all" failed. Used --force, continuing.

Running "newer-postrun:jshint:all:1:/.../node_modules/grunt-newer/.cache" (newer-postrun) task

Running "test" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "concurrent:test" (concurrent) task

```
Running "copy:styles" (copy) task


Done, without errors.


Execution Time (2014-03-13 23:49:43 UTC)
loading tasks  2ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 29%
copy:styles    5ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 71%
Total 7ms
```

Running "autoprefixer:dist" (autoprefixer) task

Running "connect:test" (connect) task
Started connect web server on 127.0.0.1:9001.

Running "mocha:all" (mocha) task
Testing: http://127.0.0.1:9001/index.html

  ․

  1 passing (1ms)

> > 1 passed! (0.00s)

Running "clean:dist" (clean) task
Cleaning dist/.htaccess...OK
Cleaning dist/images...OK
Cleaning dist/index.html...OK
Cleaning dist/robots.txt...OK
Cleaning dist/scripts...OK
Cleaning dist/styles...OK

Running "useminPrepare:html" (useminPrepare) task
Going through app/index.html to update the config
Looking for build script HTML comment blocks

Configuration is now:

  concat:
  { generated: 
   { files: 
      [ { dest: '.tmp/concat/styles/vendor.css', src: [] },
        { dest: '.tmp/concat/styles/main.css',
          src: [ '.tmp/styles/main.css' ] },
        { dest: '.tmp/concat/scripts/vendor.js',
          src: 
           [ 'app/bower_components/jquery/dist/jquery.js',
             'app/bower_components/fastclick/lib/fastclick.js',
             'app/scripts/svgcheckbx.js' ] },
        { dest: '.tmp/concat/scripts/main.js',
          src: [ '{app,.tmp}/scripts/main.js' ] } ] } }

  uglify:
  { generated: 
   { files: 
      [ { dest: 'dist/scripts/vendor.js',
          src: [ '.tmp/concat/scripts/vendor.js' ] },
        { dest: 'dist/scripts/main.js',
          src: [ '.tmp/concat/scripts/main.js' ] } ] } }

  cssmin:
  { generated: 
   { files: 
      [ { dest: 'dist/styles/vendor.css',
          src: [ '.tmp/concat/styles/vendor.css' ] },
        { dest: 'dist/styles/main.css',
          src: [ '.tmp/concat/styles/main.css' ] } ] } }

Running "concurrent:dist" (concurrent) task

```
Running "copy:styles" (copy) task


Done, without errors.


Execution Time (2014-03-13 23:49:46 UTC)
loading tasks   4ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
copy:styles    10ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 67%
Total 15ms

Running "imagemin:dist" (imagemin) task
✔ app/images/australia_states_map.png (saved 185.67 kB)
✔ app/images/logo.png (saved 54.79 kB)
✔ app/images/tool.jpg (saved 70.65 kB)
Minified 3 images (saved 311.10 kB)

Done, without errors.


Execution Time (2014-03-13 23:49:46 UTC)
loading tasks   4ms  ▇▇▇ 5%
imagemin        1ms  ▇ 1%
imagemin:dist  77ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 94%
Total 82ms

Running "svgmin:dist" (svgmin) task

Done, without errors.


Execution Time (2014-03-13 23:49:46 UTC)
loading tasks    5ms  ▇▇▇ 4%
svgmin:dist    111ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 117ms

Running "compass:dist" (compass) task
directory .tmp/styles/ 
   create .tmp/styles/main.css (0.035s)
Compilation took 0.035s

Running "compass:server" (compass) task
unchanged app/styles/main.scss
Compilation took 0.006s

Done, without errors.


Execution Time (2014-03-13 23:49:46 UTC)
compass:dist    393ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 56%
compass:server  308ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 44%
Total 707ms
```

Running "autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/styles/main.css" created.

Running "concat:generated" (concat) task
File ".tmp/concat/styles/vendor.css" created.
File ".tmp/concat/styles/main.css" created.
File ".tmp/concat/scripts/vendor.js" created.
File ".tmp/concat/scripts/main.js" created.

Running "cssmin:generated" (cssmin) task

> > Destination not written because minified CSS was empty.
> > File dist/styles/main.css created.

Running "uglify:generated" (uglify) task
File "dist/scripts/vendor.js" created.
File "dist/scripts/main.js" created.

Running "copy:dist" (copy) task
Copied 3 files

Running "rev:dist" (rev) task
dist/scripts/main.js >> 39f74953.main.js
dist/scripts/vendor.js >> 83f64eba.vendor.js
dist/styles/main.css >> 0b384bf3.main.css
dist/images/australia_states_map.png >> d41d8cd9.australia_states_map.png
dist/images/logo.png >> d41d8cd9.logo.png
dist/images/tool.jpg >> d41d8cd9.tool.jpg

Running "usemin:html" (usemin) task

Processing as HTML - dist/index.html
Update the HTML to reference our concat/min/revved script files
<script src="scripts/vendor.js" changed to <script src="scripts/83f64eba.vendor.js"
<script src="scripts/main.js" changed to <script src="scripts/39f74953.main.js"
Update the HTML with the new css filenames
<link rel="stylesheet" href="styles/main.css" changed to <link rel="stylesheet" href="styles/0b384bf3.main.css"
Update the HTML with the new img filenames
<img class="cover-image" src="images/tool.jpg" changed to <img class="cover-image" src="images/d41d8cd9.tool.jpg"
<img class='ni-logo' src="images/logo.png" changed to <img class='ni-logo' src="images/d41d8cd9.logo.png"
<img src="images/australia_states_map.png" changed to <img src="images/d41d8cd9.australia_states_map.png"
<img src="images/australia_states_map.png" changed to <img src="images/d41d8cd9.australia_states_map.png"
<img class='cover-image' src="images/tool.jpg" changed to <img class='cover-image' src="images/d41d8cd9.tool.jpg"
<img src="images/logo.png" changed to <img src="images/d41d8cd9.logo.png"
Update the HTML with data-main tags
Update the HTML with data-\* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input

Running "usemin:css" (usemin) task

Processing as CSS - dist/styles/0b384bf3.main.css
Update the CSS to reference our revved images

Running "htmlmin:dist" (htmlmin) task
File dist/index.html created.

Done, but with warnings.

Execution Time (2014-03-13 23:49:42 UTC)
jshint:all        100ms  ▇ 2%
concurrent:test   839ms  ▇▇▇▇▇▇▇ 14%
mocha:all          1.1s  ▇▇▇▇▇▇▇▇▇ 19%
concurrent:dist    2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37%
uglify:generated   1.3s  ▇▇▇▇▇▇▇▇▇▇ 21%
usemin:css        249ms  ▇▇ 4%
Total 6s

**Comment by stevemao** [comment]
Would this be related to #303 ? When I created this project, I was stuck at grunt-contrib-imagemin and used control+c to continue. But I did reinstall imagemin from npm though... also works fine when there is a change in image folder.

**Comment by sindresorhus** [comment]
Open a ticket at grunt-contrib-imagemin
