### ISSUE TITLE
images not showing in my dist site.

### ISSUE THREAD

**Issue by HeruLutalo** [yeoman/generator-webapp_DEPRECATED#309]
Hi whenever I run the grunt command to build my site for distribution, the images and font awsome don't show, even the gliph don't show as well. when I look in the images folder all the images names were changed and file size equal 0 bites. I'm using the sass version. I haven't touched any config files.

**Comment by silvenon** [comment]
Very weird, I just tested the generator and everything works fine on my side.

What are the steps to reproduce your error? Do your paths work in development? Do your image paths start with `images/`? Can you paste your HTML?

**Comment by eddiemonge** [comment]
@HeruLutalo can you push your project to github so we can test?

**Comment by HeruLutalo** [comment]
@silvenon yes I found it very weird myself, all the paths work in development here is the html for one of the pages I'm working on, yes my image paths starts with images/

[deleted as the source code has been provided](https://gist.github.com/eddiemonge/5a45e489d148a7b4f336)

Thanks in advance for your help

**Comment by silvenon** [comment]
Could you please properly markup your code? Like this:

```html
<!doctype html>
<!-- the rest of your code -->
```

It will render like:

``` html
<!doctype html>
<!-- the rest of your code -->
```

But from what I've seen, everything looks ok. I guess we need more information. Could you share your repo? If that's not possible, a directory structure would be helpful.

**Comment by silvenon** [comment]
I see you're using `data-at2x` attributes, which won't get updated, AFAIK. That's the problem you might be seeing, are you viewing your site on a retina device?

**Comment by silvenon** [comment]
gruntjs/grunt-contrib-imagemin#163 seems to fit your issue. Try downgrading it to 1.4.1 by changing this line in your `package.json`:

``` js
"grunt-contrib-imagemin": "~0.5.0",
```

to

``` js
"grunt-contrib-imagemin": "~0.4.1",
```

Then run `npm install` and try again.

**Comment by HeruLutalo** [comment]
@silvenon and @eddiemonge I've pushed my project on github here it is https://github.com/HeruLutalo/Sifa-website.git

**Comment by HeruLutalo** [comment]
@silvenon yes I building a retina ready site, when I do the npm install what will i be installing is their a specific file i need to refer to or just type npm install? Thanks again

**Comment by silvenon** [comment]
You shouldn't have to type `npm install`, when running `yo webapp`, `npm install` will run automatically. I will take a look at your code soon.

**Comment by HeruLutalo** [comment]
@silvenon Thanks

**Comment by silvenon** [comment]
Sorry, I misread your question. You have to run `npm install` when you edit dependencies in `package.json`. So follow my instructions for downgrading grunt-contrib-imagemin, then run `npm install`, exactly like that.

**Comment by HeruLutalo** [comment]
Hi @silvenon downgrading grunt-config-imagemin did the trick for the images, now the only thing that's not working is the Font-Awsome and Bootstrap Glyphicons, thanks for all the help

**Comment by eddiemonge** [comment]
Which images aren't showing up?

**Comment by HeruLutalo** [comment]
@eddiemonge images are working great now its just the Font-Awsome fonts and bootstrap Glyps thats not showing on the dist site

**Comment by eddiemonge** [comment]
Check your paths. A fix was checked in last night for this issue. Look at where they are in the gruntfile compared to the source and were they should end up

**Comment by HeruLutalo** [comment]
@eddiemonge Ok I'll take a look I'm pretty new to grunt, bower and yeoman workflow so please bear with me and thanks for the help much appreciated.

**Comment by silvenon** [comment]
When I go to `sifa-members.html`, I see Glyphicons just fine as arrows in the carousel. But I can't find Font Awesome you mentioned. How did you include it and where are those files?

**Comment by eddiemonge** [comment]
@HeruLutalo still there?

**Comment by silvenon** [comment]
Maybe @HeruLutalo was having issues with the old grunt-contrib-imagemin, but there's a new fixed version, so this can be closed until @HeruLutalo writes back? @addyosmani @sindresorhus
