### ISSUE TITLE
Sass build workflow

### ISSUE THREAD

**Issue by benoitgrelard** [yeoman/generator-webapp_DEPRECATED#31]
Hi,

Currently it is not possible to use sass generated files in usemin blocks.
- Let's say I have `<link rel="stylesheet" href="styles/main.css">` in the head of the document (but in reality am authoring sass file `styles/main.scss`).
- When using `grunt server`, it is compiling the actual `main.scss` file in the background and serving it from the `.tmp` folder: **Perfect so far**
- However now, if I have a min block like this: 

``` html
<!-- build:css styles/all.css -->
<link rel="stylesheet" href="components/ratchet/dist/ratchet.css">
<link rel="stylesheet" href="styles/main.css">
<!-- endbuild -->
```
- The concat config will be updated to concatenate `app/components/ratchet/dist/ratchet.css` and `app/styles/main.css` into `dist/styles/all.css`
- However it will never find the `main.css` file in the app styles folder cause it doesn't exist (it is located in `.tmp` where it is compiled).

So far I can't find any good solution to make the sass workflow work for both server mode and build mode. (to fix the build you can do  this `<link rel="stylesheet" href="../.tmp/styles/main.css">` but it breaks the server mode...)

Anyone has thoughts about that?

**Comment by passy** [comment]
This is a known issue and we're working on it. grunt-usemin is being redesigned at the moment to do exactly what you're describing. Thanks for writing this up. :)

**Comment by passy** [comment]
For further reference, a lot if this has been covered in #12.

**Comment by alejandroiglesias** [comment]
Any news about this? I'm experiencing similar issues on #35.

**Comment by msvbg** [comment]
I've also noticed this issue and am eagerly awaiting an update. Until then, I'm sticking with the hack that breaks in build mode.

**Comment by bstro** [comment]
I am still experiencing the issue described in #35. Yeoman v1.0.0-beta.3

**Comment by kevva** [comment]
@bstro, what exactly? Problems with Compass images or CSS in `.tmp` folder? You should also upgrade to v1.0.0-beta4.
