### ISSUE TITLE
Running grunt test on a cloned webapp repository of fails at PhantomJS

### ISSUE THREAD

**Issue by johnfumaster** [yeoman/generator-webapp_DEPRECATED#313]
I created a webapp at work by running `yo webapp`, did some work, and then checked it in to git. I didn't change anything in the .gitignore, so none of the modules/bower components were in the git.

When I got home, I tried to work on it a bit more. So I started by cloning the repository. Then in nodejs, I ran `npm install && bower install` to install the project's dependencies:

I then ran `grunt test` to make sure it works, but what I got was an ERROR.

> Warning: PhantomJS unable to load "http://0.0.0.0:9001/index.html" URI. Unable to continue.

But if I ran yo webapp again and overwrite everything except for existing files in /app/ to keep my work intact, the generator would install a bunch of things (which I don't know what they are), and then grunt test would work.

As I don't want to ask my colleagues who would be cloning this project to run the risk of overwriting the files in /app/, I'd rather they install the missing components. Can anyone help me please?

Thanks

**Comment by eddiemonge** [comment]
Is your project public so we can clone to try it? If not, could you add me to it?

**Comment by johnfumaster** [comment]
Hi, I've created a duplicate repo under my github account.  (the original is located in BitBucket)
https://github.com/johnfumaster/TestWebapp

By the way, I am working in a Windows environment.

Thanks again.

**Comment by eddiemonge** [comment]
I get this error on Mac:

```
Running "mocha:all" (mocha) task
Testing: http://0.0.0.0:9001/index.html

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

Aborted due to warnings.
```

**Comment by johnfumaster** [comment]
That is the exact error I'm getting, i.e. the error I'm referring to in the post.  You can replicate the issue by just creating a new webapp by running `yo webapp`, push it up to a git repo, then pull it down to a new location locally, and running `grunt test`

**Comment by eddiemonge** [comment]
You have to go into the test directory and run `bower install` there as well

**Comment by johnfumaster** [comment]
ah ha!  it works now.  Thanks for looking into it Eddie.  I should have come here in the first place instead of doing all these testing and googling.  So many hours lost.
