### ISSUE TITLE
Grunt Serve Not Working in Ubuntu 12.04

### ISSUE THREAD

**Issue by sshnavin** [yeoman/generator-webapp_DEPRECATED#320]
HI i Started with the installations as mentioned on the http://yeoman.io and node.js installed too. 
I installed the Yeoman Globally along with generator-webapp but when i create a new project using " yo webapp " after a little bit of fetching dependencies i get this weird error PS: installed all the stuff using "sudo"
The error i get is this : 
<code>
npm http 304 https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/grunt-contrib-jshint
npm http 304 https://registry.npmjs.org/grunt-contrib-concat
npm ERR! Error: EACCES, mkdir '/home/naveen/tmp/npm-28994-7uELd4me'
npm ERR!  { [Error: EACCES, mkdir '/home/naveen/tmp/npm-28994-7uELd4me']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/naveen/tmp/npm-28994-7uELd4me',
npm ERR!   parent: 'yeoman-demo' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! System Linux 3.11.0-18-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/naveen/yeoman-demo
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /home/naveen/tmp/npm-28994-7uELd4me
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/naveen/tmp/npm-28994-7uELd4me'
npm http 304 https://registry.npmjs.org/grunt-contrib-cssmin
npm http 304 https://registry.npmjs.org/grunt-contrib-htmlmin
npm http 304 https://registry.npmjs.org/grunt-contrib-uglify
npm http 304 https://registry.npmjs.org/grunt-contrib-connect
npm http 304 https://registry.npmjs.org/grunt-contrib-clean
npm http 304 https://registry.npmjs.org/grunt-bower-install
npm http 304 https://registry.npmjs.org/grunt-rev
npm http 304 https://registry.npmjs.org/grunt-autoprefixer
npm http 304 https://registry.npmjs.org/grunt-contrib-imagemin
npm http 304 https://registry.npmjs.org/grunt-contrib-watch
npm http 304 https://registry.npmjs.org/grunt-usemin
npm http 304 https://registry.npmjs.org/grunt-newer
npm http 304 https://registry.npmjs.org/grunt-mocha
npm http 304 https://registry.npmjs.org/grunt-svgmin
npm http 304 https://registry.npmjs.org/grunt-concurrent
npm http 304 https://registry.npmjs.org/load-grunt-tasks
npm http 304 https://registry.npmjs.org/jshint-stylish
npm http 304 https://registry.npmjs.org/time-grunt
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/naveen/yeoman-demo/npm-debug.log
npm ERR! not ok code 0
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Appgenerator.EventEmitter.emit (events.js:74:15)
    at done (/usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
    at /usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:113:21
    at /usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
    at /usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
    at /usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:516:34
    at Appgenerator.<anonymous> (/usr/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/actions/install.js:43:7)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
naveen@ubuntu:~/yeoman-demo $
</code>

I even tried ignoring these errors and moved on to start the grunt server using both the "serve" as well as "server"

I got this error at the end : 

<code>
naveen@ubuntu:~/yeoman-demo$ grunt serve
grunt-cli: The grunt command line interface. (v0.1.13)
Fatal error: Unable to find local grunt.
If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:
http://gruntjs.com/getting-started
naveen@ubuntu:~/yeoman-demo$ 
</code>
I can see the app files being created in my app folder but only the html markup works in the browser.
I followed all the instructions carefully even tried installing the grunt stand alone later but none of it worked. I hope someone helps asap.
I'm really starting to like Yeoman with by watching all the videos on the website.

**Comment by kevva** [comment]
First and foremost: don't use `sudo`. Regardless of that, it seems like there are permission errors anyway.

**Comment by sshnavin** [comment]
without <code> sudo </code> it wont let me install it says needs root or admin access.
Anything else you find wrong with this thing ?

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/20330273/error-installing-yeoman
