### ISSUE TITLE
yo webapp stucks on windows 8.1 x64

### ISSUE THREAD

**Issue by lhwparis** [yeoman/generator-webapp_DEPRECATED#321]
when i start the generator on windows 8.1 x64 it stucks in this point:

grunt-contrib-imagemin@0.4.1 node_modules\grunt-contrib-imagemin
├── filesize@2.0.3
├── async@0.2.10
├── chalk@0.4.0 (has-color@0.1.4, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── pngquant-bin@0.1.7 (bin-wrapper@0.2.3)
├── jpegtran-bin@0.2.6 (bin-wrapper@0.2.3)
├── optipng-bin@0.3.3 (win-spawn@2.0.0, rimraf@2.2.6, tempfile@0.1.3, concat-str
eam@1.4.4, bin-wrapper@0.2.3)
└── gifsicle@0.1.5 (bin-wrapper@0.2.3)

have tried it several times but it never goes trough this point :(
no error or something

**Comment by sindresorhus** [comment]
That's an issue with grunt-contrib-imagemin. Open a ticket there ;)

**Comment by lhwparis** [comment]
its solved in 0.6.0 so maybe you ll update the package you use from 0.4.1 to 0.6.0?

**Comment by addyosmani** [comment]
Unless there's any opposition, this seems like an upgrade we should be making anyway. @sindresorhus any reason not to?

**Comment by sindresorhus** [comment]
Yes. 0.6.0 was released yesterday and fixes a bunch of things.

**Comment by lhwparis** [comment]
btw not directly related to this ticket but many packages in package.json are not up to date. i have updated all of them to the newest version and all seems to work well. are you interested in a pull request?

**Comment by sindresorhus** [comment]
@lhwparis yes please :)

though you don't need to bump patch version, only minor and major.
