### ISSUE TITLE
--skip-install still attempts to install Bower deps

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp_DEPRECATED#322]
I tried installing the latest version of generator-webapp using `--skip-install`. It correctly skipped the installation of `npm` deps, but still tried to install the Bower deps (some appear to be skipped - maybe it's just those for testing?). This can be an issue for users who are offline and just want to scaffold something quick without the other deps.

![screen shot 2014-03-29 at 11 49 48](https://cloud.githubusercontent.com/assets/110953/2558193/787a3e54-b738-11e3-88a5-632c3a98990b.png)

**Comment by lhwparis** [comment]
its just the boewer components for mocha testing not the main bower components isnt it? the main bower components getting skipped correctly for me

**Comment by addyosmani** [comment]
Yes. It's the Bower deps for Mocha testing. I (think) user expectation would be that any npm/bower dep installation all the way through would be respected.
