### ISSUE TITLE
Libsass.md

### ISSUE THREAD

**Issue by fluke** [yeoman/generator-webapp_DEPRECATED#326]
Could someone with some experience flesh this out. https://github.com/yeoman/generator-webapp/blob/master/libsass.md @addyosmani @sindresorhus @eddiemonge

**Comment by eddiemonge** [comment]
I think this should be a link in the readme and have it be a page on the .io site or a blog post

**Comment by fluke** [comment]
Both of those ideas sound great.

**Comment by silvenon** [comment]
To me an .io site sounds a bit too much for something that changes so rapidly. Maybe just a wiki page or README should be sufficient?

**Comment by addyosmani** [comment]
I think @eddiemonge was referring to just adding in a page into our existing markdown based https://github.com/yeoman/yeoman.io repo that powers the yeoman.io site. It's what we use instead of a wiki and can be updated at any time.

**Comment by silvenon** [comment]
Oh, my bad :) That does sound like a good idea.

**Comment by fluke** [comment]
Made a pull request https://github.com/yeoman/generator-webapp/pull/334 based on https://github.com/yeoman/yeoman.io/issues/175#issuecomment-39687705
