### ISSUE TITLE
Bower is installing to "app/bower_components"

### ISSUE THREAD

**Issue by sygint** [yeoman/generator-webapp_DEPRECATED#341]
I know this is not a bug of this project, but it is a problem I am having directly this project, so if anyone can help me out, that'd be great.

I do not have a ".bowerrc" in my home directory...

**Comment by sindresorhus** [comment]
Please use StackOverflow for support questions

**Comment by eddiemonge** [comment]
somewhat duplicate of https://github.com/yeoman/generator-webapp/pull/340
