### ISSUE TITLE
bower_components folder named incorrectly

### ISSUE THREAD

**Issue by KingScooty** [yeoman/generator-webapp_DEPRECATED#346]
The `bower_components` folder inside `/app` is showing as `app/components` for me and breaks all references.

Obviously the fix is as simple as renaming the folder back, but the generator seems to be creating this folder name incorrectly.

**Comment by kevva** [comment]
There shouldn't be any folder of that sort inside `app/`. `bower_components/` get's installed in the root folder. Make sure you don't have a global `.bowerrc` that's overriding things.

**Comment by lhwparis** [comment]
i had the same issue maybe its safer to restore the .bowerrc file just to make sure it overwrites a global one

**Comment by kevva** [comment]
I don't see the point to use a global one though.

**Comment by lhwparis** [comment]
me too but what i can say i have never created it or edited it myself. try to find out where it came from but maybe thats the same case for others too why it is more save to have a .bowerrc in webapp generator i think. this small file doesnt hurt much and its more fail safe with it.
