### ISSUE TITLE
mocha fails in ci, but not locally

### ISSUE THREAD

**Issue by FunTimeCoding** [yeoman/generator-webapp_DEPRECATED#347]
note, the CI Im talking about is installed locally, so it should both use the same environment.

when running tests locally in a terminal it works fine like `grunt test`

but inside jerkins this happens:

```
[4mRunning "connect:test" (connect) task[24m
Started connect web server on 10.0.0.116:9001.

[4mRunning "mocha:all" (mocha) task[24m
Testing: http://10.0.0.116:9001/index.html

[33mWarning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.[39m

[31mAborted due to warnings.[39m
```

..and that fails the build. all I changed in my grunt file was the http host to 0.0.0.0 like suggested if it shouldn't only go to 127.0.0.1, but even putting my bonjour name in there (which you can see gets resolved in the pasted output) didn't help. also, port 9001 isn't in use by anything.

**Comment by eddiemonge** [comment]
possibly duplicate of https://github.com/yeoman/generator-webapp/issues/348

**Comment by eddiemonge** [comment]
https://github.com/yeoman/generator-webapp/issues/349#issuecomment-46579496
