### ISSUE TITLE
issue with bower_components moved outside /app

### ISSUE THREAD

**Issue by lhwparis** [yeoman/generator-webapp_DEPRECATED#358]
bower components not inside /app can be an issue. i dont use all bower components inside my  so usemin can handle it and add it to the concated JS file.

instead i use yepnope for some bigger not so often used bower components. but these components are getting lost during grunt build because they were not copied in dist. so its not possible to use a bower_component which is not placed inside a usemin block.

what should be done is to check which bower components are used inside a usemin block and all other bower_components should be copied to dist (maybe in scripts/vendor)

**Comment by eddiemonge** [comment]
You know yepnode hasn't been updated in over a year (with the last release being 2 years ago) and isn't recommended for use anymore right?

If you are manually placing components in your html files, you should be wrapping them in a different usemin block so they get copied during build.

**Comment by lhwparis** [comment]
there are many other async.js loaders doing the same as yepnope and have the same problem for example require.js curl.js ... usemin does not recognize the js file inside of one of these js async loader scripts.
btw i dont like that you guys ever close tickets before you get a response if this was solving the problem.

**Comment by eddiemonge** [comment]
Its not really a bug in the system. This question would probably be better answered at stackoverflow. We are trying to keep the issues low so we don't get overwhelmed with requests for support when we really want to see issues for bugs. Your question also seems more likely an issue with usemin/yepnode/your script loader/how you are writing your scripts. If you want to give some actual code examples I can walk you through a possible solution.

**Comment by lhwparis** [comment]
i placed it here because it was working in older releases when bower_install was inside the app folder. but you are right its more an usemin issue. thank you.
