### ISSUE TITLE
bower components not getting automatically updated

### ISSUE THREAD

**Issue by lhwparis** [yeoman/generator-webapp_DEPRECATED#359]
if you are using git and someone else added a new bower component and you pull that change from git while your grunt serve (watch) is not running you do not get this bower component installed. you have to do a manual "bower install".

wouldn t it be a better solution to always do a bower install by starting grunt serve or grunt build?

**Comment by stephenplusplus** [comment]
This is a question of workflow. It would be helpful if that other dev somehow let you know they added a new component, or you would notice (say, in a PR), but you can't count on that. It should be part of your workflow to either always run `bower install` when you checkout, or look for changes before running it. The same goes for `npm` dependencies. Yeoman doesn't want to mask the inner workings of tools, so Grunt will continue to do Grunt things, Bower will do Bower, npm will do npm. This way, we all end up with a better idea of how to integrate these tools together for our needs, and some day, when one piece needs to be replaced, our whole workflow doesn't fall apart.

**Comment by Samirbekaert** [comment]
@stephenplusplus thanks for that answer. This uncovers quite a fundamental principle that is not that easy to know for new front-end devs who are jumping headfirst into yeoman. Perhaps you guys could consider adding this to the yeoman FAQ? cc @sindresorhus

**Comment by sindresorhus** [comment]
You can use a git post merge hook to run `bower install` automagically on merge: https://gist.github.com/sindresorhus/7996717
