### ISSUE TITLE
Add more questions to generator

### ISSUE THREAD

**Issue by alejandroiglesias** [yeoman/generator-webapp_DEPRECATED#36]
Hi, i would like to propose to add more questions to the generator, like the following:
- Would you like to include jQuery?
- Are you going to use CoffeeScript?
- Are you going to use Twitter Bootstrap at all? (this one answered "yes" could trigger "Would you like to include Twitter Bootstrap for Sass?")
- Are you going to use Compass?

If answered "no", remove the files, reference in `app/scripts/main.js`, Grunt plugins and Gruntfile code blocks.

This seems good to allow smaller projects initialization and not having to remove lots of scaffolded code.

**Comment by sindresorhus** [comment]
1. No, you can easily fetch it with Bower ourself: `bower install --save jquery`
2. No, need, this is handled transparently.
3. You only get Bootstrap for Compass if you answer yes. If you need vanilla, you can do `bower install --save bootstrap`
4. We are opinionated and recommend Compass, if you don't want it, use another generator or just remove that part of the config in the Gruntfile. Should take 10 sec.

**Comment by alejandroiglesias** [comment]
@sindresorhus thanks for taking time for answering, but you seem to understand partially the situation.
1. I know i can fetch jQuery with Bower. What i want is _not_ to use it, and it comes bundled by default.
2. I know CoffeeScript is included transparently but it would be good to remove it if not needed (i'm looking at ways to save precious Grunt build time as it currently takes much longer than my previous non-Yeoman Grunt setup and i'm looking at ways to optimize so running the build is not horribly tedious as compiling a Java app).
3. Yes, i know that too, but even answering "no" _does_ include the Bootstrap JS file and configures it in RequireJS config, which i _don't_ want.
4. I know and like that Yeoman is very opinionated, but the point of this whole post is "please, add a couple more questions so it's less of a hassle to remove certain things for little projects".

You see, requiring to do lots of Boilerplate is a hassle, that's why Yeoman exists, but also, removing unused scaffolding things is a hassle too and it doesn't do harm to add a couple of more questions, does it? My colleague designer should also benefit from a easy scaffolding as Yeoman does, but yesterday we tried and seemed to worry about too much things not needed in _every_ project.

I think it's better to be opinionated, but be opinionated in the workflow. If we say "we use Grunt to build like this, we use Bower for managing packages like this and with these tools you scaffold and build your app" it means in the end, it _helps you_ with **your** app. But this way it's like "write your app like this, using jBlabla and learn CoffeeScript even if it looks ugly to you and Compass, which is great but you may even not know what that is", that doesn't helps but _forces_. It's about choosing how i'll write my app and use the tool for the workflow.

Ok, i hope we keep exchanging our views on this.
Cheers.

**Comment by sindresorhus** [comment]
You have some good points, thanks for elaborating. Busy now, but will give a better answer another day.

**Comment by alejandroiglesias** [comment]
Of course man, thanks.

**Comment by kevva** [comment]
It's a fine line. Sure, we could ask questions about every feature like jQuery, Coffeescript, Modernizr, Compass and so forth, but maybe that is taking it too far, at least as a default. We could instead give the option to choose a default build to get started fast or a customised build where the users have the option to answer whether they want to include or exclude features like jQuery etc.

**Comment by passy** [comment]
I also see the technical problem, that we currently don't have a robust infrastructure that allows us to test all the different combinations sufficiently.

**Comment by alejandroiglesias** [comment]
@kevva maybe adding a `--custom` parameter enables more questions to be asked?
@passy regarding the technical, it shouldn't be too troublesome as many elements are independent of each other, like jQuery, CoffeeScript, Modernizr, RequireJS, Compass.

I know the workflow we use and love is meant to be opinionated, but I think this is also beneficial for newcomers that don't use these technologies to be able to adopt them gradually. It's too much to start using Modernizr, RequireJS and Compass all of a sudden. It makes your project too slow. I'm thinking of many co-workers wanting to drop it for that reason. I myself wasn't using RequireJS and dealing with grunt-usemin stuff and learning to manage Yeoman generated environment was troublesome to handle all at the same time.
My 2cents. Cheers!

**Comment by ghost** [comment]
If a package manager wants to be opinionated and force its users into adopting whatever its maintainers recommend no matter what then it should be capable of addressing those enforced dependencies. If it can't do that, then the opinions of anyone who thinks it's actually a package manager aren't especially valuable. 

There's a big difference between requiring a particular directory structure or set of file naming conventions and intentionally creating broken software installations that have no hope of ever working. The fact that this is even a discussion is baffling.

**Comment by ghost** [comment]
Supercool that the Angular generator requires CoffeeScript yet generates **no** CoffeeScript whatsoever, too. Nobody's actually using this for anything other than résumé padding, are they?

**Comment by passy** [comment]
@oncomeme Feel free to submit a PR. I'd be happy to review it.

**Comment by passy** [comment]
I'm going to close this for now. `generator-webapp` provides an opinionated starting point for a web application. It's not supposed to be minimal or a one-size-fits-all solution. We don't even bundle it anymore, so anyone who disagrees is free to create its own fork.
