### ISSUE TITLE
scripts under bower_components cannot loaded when app deploy to non-root context

### ISSUE THREAD

**Issue by shaqtsui** [yeoman/generator-webapp_DEPRECATED#360]
When I deploy app to context link : "/web"

These scripts path like : `<script src="../bower_components/modernizr/modernizr.js"></script>` will be resolved to `/bower_components/modernizr/modernizr.js` which can not be find

**Comment by eddiemonge** [comment]
This is meant as a starting point, not the finished product. If you move your project, you will still be responsible for updating the location to things. You might need to update your `.html` files as well as your `Gruntfile.js`
