### ISSUE TITLE
Bootstrap SASS not working

### ISSUE THREAD

**Issue by glennadva** [yeoman/generator-webapp_DEPRECATED#363]
When using yo webapp, choosing SASS I don't get Bootstrap working correctly.

For example, when I use the code (the container part) from http://getbootstrap.com/examples/grid/,
I don't get the columns to display in the correct way.
Another example is http://www.tutorialrepublic.com/examples/bin/output.php (the container part). On large screen the rows are not displayed on three lines, but over several lines.

The default Bootstrap option (via yo webapp) does work.
I'd like to use the SASS version if possible.

Any idea what might be causing this and how to solve it?

**Comment by eddiemonge** [comment]
what code are you using that fails?

**Comment by addyosmani** [comment]
@eddiemonge I'm seeing a few recent issues with the Bootstrap Sass setup causing problems (#367, #364 etc). We might want to take a look at whether there are known issues with the package upstream.

**Comment by eddiemonge** [comment]
or maybe just do an overhaul like i did with angular. we 'fix' one case and it breaks another. all options need to be tested on all changes

**Comment by zfarrell** [comment]
FWIW, i was having a similar issue with columns not positing correctly in firefox. After much debugging, i was able to resolve the issue by downgrading `grunt-autoprefixer` to v0.6.5. For some reason, after v0.7.0 vendor prefixes aren't correctly added.

**Comment by silvenon** [comment]
@glennadva Could you please show us how the grid is incorrectly displayed? Maybe paste it in a [pen](http://codepen.io) or whatever you use for this stuff. Also, in the second example everything is blank for me, did you remove it?

@addyosmani I don't think those issues are related to this one, they are related to paths, while this one is related to the compiled Bootstrap itself.

@zfarrell Whoa, that's weird! Thanks, now we know where to look :smiley:

Ideally I would like to autoprefix everything except Bootstrap, is that possible? Is it a problem for Autoprefixer if some prefixes exist beforehand?
