### ISSUE TITLE
Bootstrap Sass fonts not working on 'grunt serve'

### ISSUE THREAD

**Issue by sygint** [yeoman/generator-webapp_DEPRECATED#366]
This seems to be due to how main.scss locates the $icon-fonts-path.  The problem seems to be that main.scss uses this path for rendering out the path correctly for the 'grunt build'.

In other words, the main.scss $icon-font-path is set to work with 'grunt build' not 'grunt serve' and I can't figure out how to make it work for both at the same time.

**Comment by addyosmani** [comment]
Is this with the latest version of the generator on npm? Could you share the version you're using?

**Comment by sygint** [comment]
it happens with the latest version from the repo and npm

**Comment by eddiemonge** [comment]
which version does it say when you run `yo webapp --version` or `yo`

**Comment by sygint** [comment]
yo webapp --version: 1.1.2
yo: 0.4.9

**Comment by sygint** [comment]
if you look at how main.scss is created and remember that is must set the $icon-font-path to the finalized directory, then you know it can't also set it to the path in the bower_components directory

it's a logistical problem i fear.  a solution might be to do something like the way that usemin works and create something like a grunt-usemin-css that did usemin style optimizing for css paths

**Comment by eddiemonge** [comment]
it should be fixable. ill take a stab at it hopefully this week. i seemed to have fixed it in the generator-angular project so hopefully i can do the same here

**Comment by sygint** [comment]
awesome, i'm very interested to see the solution, maybe i'll take a look generator-angular and learn some tricks, thanks

**Comment by KingScooty** [comment]
The path in `main.scss` seems to have changed recently in the repo to `../styles/fonts`.

The path should really be `/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/`

But then i guess won't work for both `serve` and `build`?

**Comment by eddiemonge** [comment]
if someone wants to try, see if doing the fixes from https://github.com/yeoman/generator-angular/commit/0a66f54d14f1ae6533e21153ee9e19b1da6626bc helps here

**Comment by williscool** [comment]
I had this exact same issue guys. Can confirm @eddiemonge 's solution works

here is the final block just in case anybody else stuggles with this for hours like I did

``` javascript
    // Copies remaining files to places other tasks can use
    copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= yeoman.app %>',
          dest: '<%= yeoman.dist %>',
          src: [
            '*.{ico,png,txt}',
            '.htaccess',
            '*.html',
            'views/{,*/}*.html',
            'images/{,*/}*.{webp}',
            'fonts/*'
          ]
        }, {
          expand: true,
          cwd: '<%= yeoman.app %>/bower_components/bootstrap/dist',
          src: 'fonts/*',
          dest: '<%= yeoman.dist %>'
        }, {
          expand: true,
          cwd: '.tmp/images',
          dest: '<%= yeoman.dist %>/images',
          src: ['generated/*']
        }]
      },
      styles: {
        expand: true,
        cwd: '<%= yeoman.app %>/styles',
        dest: '.tmp/styles/',
        src: '{,*/}*.css'
      }
    },
```

**Comment by williscool** [comment]
now if I could just get usemin to rewrite the fonts to correct directory in the css files... probably will just resort to sed or a vim global replace to ship.

frustrating debugging this :/

_update:_

ended up using https://github.com/yoniholmes/grunt-text-replace

to fix things

``` javascript
    replace: {
        bower_css: {
          src: ['<%= yeoman.dist %>/styles/*.css'], // includes files in dir
          overwrite: true, 
          replacements: [{
            from: '/bower_components/bootstrap/dist/fonts/',
            to: '/fonts/'
          }, {
            from: '/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap',
            to: '/fonts/'
          }]
        }
      }
```

**Comment by silvenon** [comment]
Good job :+1: Text replacement is what we resorted to in [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp/blob/master/app/templates/gulpfile.js#L30) as well. Do you feel like submitting a PR?

**Comment by williscool** [comment]
@silvenon thanks for the complement.

I think a contributor should do it though.

With my solution it doesn't handle letting which ever grunt task renames files for cache busting do that with the fonts.

I know those dont change much but since it does it with everything else it might confuse someone or break something else.

**Comment by eddiemonge** [comment]
Im working on it now. Hopefully all these bootstrap troubles will be gone today
