### ISSUE TITLE
Open Graph inclusion simplified

### ISSUE THREAD

**Issue by dunckr** [yeoman/generator-webapp_DEPRECATED#368]
I always forget to include the open graph metadata tags when creating a project. When I do include, it tends to feel bloated especially when targeting all of the social media sites.

I want a simple API to manage the different meta tags required for all of the social media sites that would be included on a build.

In terms of interface I was thinking of a HTML comment style similar to [usemin](https://github.com/yeoman/grunt-usemin) rather than a config json:

```
 <!-- og
   description: '....',
   title: '....'
   ...
-->
```

However, now I have started leaning towards parsing the dom for existing metatags and then filling in the missing ones like CSSPrefixer. 

I have done a quick start [here](https://github.com/dunckr/grunt-og). However, the complete open graph API is more [involved](http://ogp.me/).

I wanted to know if this is something of interest for the generators and any suggestions rather than going down the wrong path.

Cheers

**Comment by sindresorhus** [comment]
How is the `og` block better than just defining the meta tags in HTML?

I kinda feel like this is outside the scope of the default boilerplate. We use HTML5 Boilerplate and there must be a reason it's not included there: https://github.com/h5bp/html5-boilerplate/blob/master/index.html

Can't find any docs about it atm, but I think OGP will fall back to `<title>` and `<description>` if it can't find any.

**Comment by dunckr** [comment]
Yeah I agree having a `og` block would be more of a nuisance.

I didn't realise that. I will look into HTML5 boilerplate issues and hopefully find some answers!

If that's the case then it kind of defeats the point. I thought that they were required for [Twitter Cards](https://dev.twitter.com/docs/cards) though?

**Comment by dunckr** [comment]
It seems that the social media ones aren't included by [choice](https://github.com/h5bp/html5-boilerplate/blob/ee0de7541fe6718b8f086d273a88c11997f90c5f/doc/extend.md)

`We don't want to include it all by default, as not everything fits with everyone's needs.`

Thanks for clearing that up.
