### ISSUE TITLE
Clean task does not remove dot files

### ISSUE THREAD

**Issue by alefteris** [yeoman/generator-webapp_DEPRECATED#37]
- Started with the files generated by webapp, I did a build
- I removed the `.htaccess`, from my app folder and Gruntfile copy task config
- After a build, `.htaccess` is still in the dist forder

**Comment by passy** [comment]
This is deliberate to allow the dist folder to be its own git repository
for deployment purposes. You can still adjust the behavior in the
Gruntfileif you like.

**Comment by alefteris** [comment]
Could this be made more explicit, with a comment maybe? Or even better a rule to exclude just the .git dir/files?

Also what I will need to change in Gruntfile to remove the dotfiles? Thanks.

**Comment by passy** [comment]
You could change the `dist: ['.tmp', '<%= yeoman.dist %>/*']` to `dist: ['.tmp', '<%= yeoman.dist %>']` for the clean task (removing just the whole dist directory instead of just the non-hidden files inside).

@sindresorhus Do you think a comment would be helpful here?

**Comment by sindresorhus** [comment]
@passy I would rather find a way to clean out everything except for `.git`. Any ideas?

**Comment by passy** [comment]
.gitignore would also be useful.

**Comment by sindresorhus** [comment]
yup

**Comment by kevva** [comment]
This works.

``` js
clean: {
  dist: {
    files: [{
      dot: true,
      src: [
        'dist/*',
        '!dist/.git*'
      ]
    }]
  }
}
```

**Comment by sindresorhus** [comment]
@kevva feel free to do that update directly ;)

**Comment by kevva** [comment]
Yep, done :)))))).

**Comment by sindresorhus** [comment]
@kevva awesome, thanks for doing this. Keep em coming :D

_Tip: use `fixes #ticketnumber` in commits to close issues directly from the commit and create a reference between them._

## 

Fixed in https://github.com/yeoman/generator-webapp/commit/7616dc42f9aa8857912e0314302a172388e45a52

**Comment by sindresorhus** [comment]
@kevva could you do the same on generator-angular?

**Comment by kevva** [comment]
@sindresorhus, I'm on it.
