### ISSUE TITLE
Support for Bower's devDependencies injection?

### ISSUE THREAD

**Issue by diagramatics** [yeoman/generator-webapp_DEPRECATED#387]
I came across to this problem when I wanted to use holderjs only on development to put placeholder images. Should there be something like `grunt wiredep:dev` or something to enable devDependencies injection on `grunt serve` or on user's request only?

Might be useful if there's specified libraries for debugging purposes only, although I never really gotten to the point of searching and finding one.

**Comment by sindresorhus** [comment]
Feel free to open a feature request on https://github.com/taptapship/wiredep

But I have yet to see someone use devDependencies, so not sure it's worth the complication.

**Comment by diagramatics** [comment]
Um, actually grunt-wiredep supports using devDependencies already with the `devDependencies: true` setting. I've tested it and it works fine as well.
