### ISSUE TITLE
yo command

### ISSUE THREAD

**Issue by xavierartot** [yeoman/generator-webapp_DEPRECATED#391]
Hi,
I have a a command no found after:
 _ npm install -g generator-webapp
yo webapp
zsh: command not found: yo

I use OSX
node: v0.10.28
npm: 1.4.9

My $PATH
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Applications/MAMP/Library/bin:/Users/xartot/snippets

**Comment by ragingwind** [comment]
Please install `yo` first with `npm install -g yo`

**Comment by xavierartot** [comment]
I did, but the problem it was in my $PATH, i fixed like this, in my .zshrc I add:
/Users/xartot/.npm/bin

WORKS !
