### ISSUE TITLE
Can't find your Modernizr development build

### ISSUE THREAD

**Issue by codingwithmanny** [yeoman/generator-webapp_DEPRECATED#393]
I got this error when trying to do **grunt build**.
I'm a bit new to requests, but I did find a work around.

**Error:**

```
Looking for Modernizr references
Warning: Can't find your Modernizr development build at                           bower_components/modernizr/modernizr.js
grunt-modernizr needs this path to avoid false positives

Update your gruntfile via the modernizr.devFile config option
See https://github.com/doctyper/grunt-modernizr#devfile-string for more details
```

The work around requires a modification in **Gruntfile.js**

**Original:**

```
        modernizr: {
            dist: {
                devFile: 'bower_components/modernizr/modernizr.js',
```

**Modification:**

```
        modernizr: {
            dist: {
                devFile: '<%= config.app %>bower_components/modernizr/modernizr.js',
```

**Comment by silvenon** [comment]
This sounds like you changed your `bower_components` path to `app/bower_components`. Did you? Or is it fresh build? Which version of generator-webapp are you using?

**Comment by codingwithmanny** [comment]
I did a fresh install of node, yeoman, and the web app generator 2 days ago.

**Webapp generator ( 0.4.9 )**

I had to make the modification so that the web app generator could build. Essentially, yes, it's referring to the directory `app/bower_components`.

**Comment by silvenon** [comment]
That's weird, `bower_components` shouldn't be installing there… Do `ls -a` in your project's root to see if you have a `.bowerrc` file telling Bower to install to `app/bower_components`.

**Comment by codingwithmanny** [comment]
Did `ls -a` and no `.bowerrc`

```
.       .gitattributes  .sass-cache app     node_modules
..      .gitignore  .tmp        bower.json  package.json
.editorconfig   .jshintrc   Gruntfile.js    dist        test
```

**Video of what I'm doing:**
https://www.youtube.com/watch?v=LLb6W6KWrBM

**Comment by silvenon** [comment]
Thanks so much for recording your issue. I was looking very closely and still can't seem to figure out how `bower_components` ended up in `app`, I didn't manage to reproduce the issue. What do you get when you run these commands?

``` sh
$ npm ls -g | grep generator-webapp
$ ls -a ~ | grep bower
```

**Comment by codingwithmanny** [comment]
**Command results:**

```
$ npm ls -g | grep generator-webapp

├─┬ generator-webapp@0.4.9

$ ls -a ~ | grep bower

.bower
.bowerrc
```

**Comment by silvenon** [comment]
Ha! I bet `cat .bowerrc` will output something like:

``` json
{
  "directory": "app"
}
```

If this is true, you have a global `.bowerrc` file which instructs Bower to install dependencies to `app`.

What are the contents of `.bower`?

**Comment by codingwithmanny** [comment]
```
$ cat .bowerrc
{
    "directory": "app/bower_components"
}
```

```
$ ls .bower
git_template
```

**Comment by silvenon** [comment]
Yeah, `app/bower_components`, not `app`, my bad. If you don't need that `.bowerrc`, you can just delete it and problem solved.
