### ISSUE TITLE
--sourcemap error in v0.5.0-1

### ISSUE THREAD

**Issue by richardwestenra** [yeoman/generator-webapp_DEPRECATED#395]
I'm getting the following issue when I try to serve/build the latest version of generator-webapp:

```
    Warning: OptionParser::InvalidOption: invalid option: --sourcemap
  Use --trace for backtrace. Use --force to continue.       
    Aborted due to warnings.
```

The error occurs immediately after `"copy:styles" (copy) task` runs without errors.

I don't get this error with v0.4.9. I managed to trace it back to the Sass task, but I can't fix it without removing sass. It seems to only occur when using ruby-sass, not node-sass. Also I have a feeling it might be related to 6a428a7 but I'm not sure.

Incidentally, I also get this error when scaffolding the app with yo, but I'm not sure whether it's related:

```
> pngquant-bin@0.3.1 postinstall /Users/.../generator-test/t9/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

✗ pre-build test failed, compiling from source...
libpng-dev is installed

{ [Error: Command failed: ar: creating archive libimagequant.a
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `install -m 0755 -p pngquant /Users/.../generator-test/t9/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant'
make: *** [install] Error 2
] killed: false, code: 2, signal: null }
```

**Comment by eddiemonge** [comment]
Its because node-sass has different options than ruby-sass. Thats why different options are used at https://github.com/yeoman/generator-webapp/commit/6dfe277a56df3ec3874b86d753b73dc506e48843#diff-8b50ebbf3a510307ebab0715e7d7aec4R194 depending on which sass you select.

Did you change which sass you use after generating the project?

**Comment by brunowego** [comment]
I get the same issue. Fresh install...

**Comment by brunowego** [comment]
I tried update sass (>=  sass-3.3.9.gem) and works now! Try it!

**Comment by richardwestenra** [comment]
Updating Sass seems to have fixed it for me too. Thanks @brunobatista!
