### ISSUE TITLE
Path to bower components

### ISSUE THREAD

**Issue by brandtparker** [yeoman/generator-webapp_DEPRECATED#398]
When I install 4.9, there is no 'bower_components' folder, yet there are references to this folder in both the grunt and sass files. Should the references point to 'app/components' instead?

**Comment by KingScooty** [comment]
The references are pointing to the right place. Is your `bower_components` folder being created elsewhere? Do you have a `.bowerrc` file set anywhere that's overriding where the bower folder is being created? May be worth checking your home dir.

**Comment by brandtparker** [comment]
If I do a 'yo webapp --skip-install'. That portion looks good (no components or bower_components folders, obviously). Then I do a 'bower install' which creates what I described: inside the 'app' folder is a 'components' folder that contains all the bower packages. However, if I try to do any 'grunt' tasks or if I look in the grunt or sass files, all the bower references are to a 'bower_components' folder that does not exist. Again, that's 4.9.

If I uninstall the web app generator and install 4.8, everything works as it should. I'd like to use 4.9, but I can't figure out what's causing the folder mismatch.

**Comment by KingScooty** [comment]
Yea, sounds like you've got a rogue `.bowerrc` file sitting somewhere above that project directory that's overriding where `bower_components` is going.

If you're on a Mac, cd into `~/` and run `ls -a` to show all hidden files. If you see a `.bowerrc` file, take a look inside it and see if that's what's causing it. If so, delete it.

**Comment by brandtparker** [comment]
Yep, you're right. I found one file above my project folder which uses 'app/components' and another inside my project folder that uses 'app/bower_components'. I should delete the one above/outside the project folder?

**Comment by KingScooty** [comment]
Is the `.bowerrc` file inside your project not overriding the one above it? (It should) But if it's not, and you don't need it to override anything elsewhere, delete it.

Also, the default dir for bower_components is : `bower_components/`, it sits outside of the `/app` folder in the root of the project.

**Comment by brandtparker** [comment]
Doesn't appear to be. I'm going to uninstall the 4.8 generator, delete the `.bowerrc` file outside my project folder, delete my project, then reinstall 4.9. We'll see if that gets me back on the right path.

**Comment by brandtparker** [comment]
Back on track. Thanks a lot @KingScooty.

**Comment by eddiemonge** [comment]
or do `npm install -g generator-webapp@0.5.0-1

**Comment by drewcovi** [comment]
this was super helpful, had the same issue. thanks!
