### ISSUE TITLE
Where did Compass go ?

### ISSUE THREAD

**Issue by mathieuartu** [yeoman/generator-webapp_DEPRECATED#402]
Hello,

I was using yeoman with compass flawlessly last year when working on some projets, then had to work on other things, and today I wanted to see what's new in Yeoman.

Everything is great, except one thing : I can't seem to use my Compass mixins now.
Even just @import "compass/css3" fails.

Why did you remove Compass ?
And is there a way to install it again ?

Thanks.

**Comment by silvenon** [comment]
You can read the discussion in #302.

TL;DR [this](https://gist.github.com/silvenon/11271918) gist explains how to bring Compass back.

**Comment by mathieuartu** [comment]
Thanks @silvenon , now I understand why it's gone.
It's pretty confusing though that pretty much every tutorial and documentation on the internet still mentions that compass is included (or on the contrary, there's no reference about compass being removed from yeoman). Maybe it could be a good idea to make a statement or I don't know.
Thanks anyway ! :-)

**Comment by silvenon** [comment]
Yeah, perhaps we'll include it as a recipe like we did with [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs/recipes).
