### ISSUE TITLE
Wrong url of library - ../bower_components/bootstrap/js/tab.js instead of ./components/bootstrap/js/tab.js

### ISSUE THREAD

**Issue by linediconsine** [yeoman/generator-webapp_DEPRECATED#403]
HI, I am new and I hope to not create invalid issue but after create a webapp setup with
yeo generator-webapp in /app/index the url of css and js (bootstrap, modernizr and jquery in my test seem to be wrong and give con consolo 404 not found.

For fix this by hand I changed url reference in index.html from  ../bower_components/ to  ./components/ and all seem to work ok.

Thanks

**Comment by silvenon** [comment]
Do you have a global `.bowerrc` somewhere? Try running `ls -a ~ | grep bower`.

Bower on your machine is somehow configured to install to `components` rather than `bower_components`, which is the default location.

**Comment by linediconsine** [comment]
Yes my .bowerrc was with wrong config.

Deleted .bowerrc in home directory  and then "bower install"

Now all seem to be fine now

Thanks
