### ISSUE TITLE
bower install include duplicate files

### ISSUE THREAD

**Issue by MillerRen** [yeoman/generator-webapp_DEPRECATED#404]
The grunt-bower-install task generate too many files for example name.js and name.min.js.
Many javascript lib include source and minify dependencies in bower.json.
```{
  "main":[
 "name.js",
  "name.min.js"
}

```
```

**Comment by MillerRen** [comment]
``` javascript
{
"main":[
"name.js",
"name.min.js"
}
```

**Comment by sindresorhus** [comment]
Can you open a ticket on the actual plugin instead: https://github.com/stephenplusplus/grunt-wiredep Thanks :)

**Comment by eddiemonge** [comment]
that plugin shouldn't have both files in the main. you should open an issue there

**Comment by silvenon** [comment]
Exactly what @eddiemonge said. It's not wiredep's job to correct mistakes of package authors. To fix this, you can exclude one of those files in the Gruntfile:

``` js
wiredep: {
  app: {
    // ...
    exclude: [
      // ...
      'bower_components/path/to/name.min.js'
    ]
  },
  // ...
},
```

**Comment by MillerRen** [comment]
@sindresorhus OK. I will.
