### ISSUE TITLE
bower_components folder linked statically

### ISSUE THREAD

**Issue by superandrew** [yeoman/generator-webapp_DEPRECATED#406]
Hello, I have this problem. When I launch `yo webapp`, the bower_components folder is not created inside /app but at the same level.

This means that if I serve the site with grunt serve links to `localhost:9000/bower_components/<file>` works, but if I use MAMP or apache to serve the files, they don't.

The main reason for this is because grunt serve creates a sort of symbolic link to the folder when launched
`connect().use(
                '/bower_components',
                connect.static('./bower_components')
              ),`

Is there something I can do? Am I doing something wrong maybe?

Thanks

**Comment by KingScooty** [comment]
If you're using apache, you don't need to use the `connect()` server. All you need to do is watch files for changes. With that in mind, if you have apache root pointing to `/app`, you can create a `.bowerrc` in your root directory file with the following:

```
{
  "directory": "app/bower_components"
}
```

And your bower components will be installed into `/app` by default for access by apache.

**Comment by superandrew** [comment]
@KingScooty man, thank you so much that was exactly what I was searching. Is it something which changed recently? I'm pretty sure I didn't have this problem one month ago with another app.

**Comment by KingScooty** [comment]
My pleasure! :)

Nope, `.bowerrc` has been around for ages. The default install directory for `bower_components` has always been in the root of the project (one up from app). Which works fine if you're using the bundled connect server, but can cause issues depending where you've set your apache root to. 

It's worth noting that if you _had_ a `.bowerrc` file in a parent directory, that would be inherited for all projects inside that directory, so perhaps that caused the discrepancy that you mention.

**Comment by superandrew** [comment]
well, since I am a quasi-noob I guess a month ago I did the same thing and completely obliterated it from my mind :)

I guess you can do something similar with apache and .htaccess to what grunt connect does, but I think this is an acceptable solution.

**Comment by silvenon** [comment]
In case you were wondering when this change was introduced, see the dates in #310. I'm glad it worked out, let us know if you have any more troubles with the setup.

**Comment by superandrew** [comment]
Now I understand the confusion, last time I used generator-angular instead of generator-webapp, it seems a change of about one month ago, see https://github.com/yeoman/generator-angular/blob/master/CHANGELOG.md#breaking-changes
