### ISSUE TITLE
import error, wiredep misconfiguration

### ISSUE THREAD

**Issue by danielreiser** [yeoman/generator-webapp_DEPRECATED#407]
grunt serve throws the following error:

```
Warning: Syntax error: File to import not found or unreadable: bootstrap-sass-    official/vendor/assets/stylesheets/bootstrap.scss.
              Load paths:
                /Users/username/Sites/testapp (DEPRECATED)
                /Users/username/Sites/testapp/app/styles
                /Users/username/Sites/testapp/bower_components
        on line 3 of app/styles/main.scss
  Use --trace for backtrace. Use --force to continue.

    Aborted due to warnings.
```

just comment line 202 in the Gruntfile.

But still in the index.html the js imports of bootstrapp-sass are incorrect...

**Comment by silvenon** [comment]
Which version are you using? Before or after #401 was pulled?

**Comment by danielreiser** [comment]
I updated the generator a few minutes ago. After yo webapp I've still got the old regex in my Gruntfile not the one from the pull.

looks like via npm install -g generator-webapp it pulls down the stable version 0.4.9 (which might be messing with my installation)

**Comment by silvenon** [comment]
Did you try linking the master?

``` sh
$ git clone https://github.com/yeoman/generator-webapp
$ cd generator-webapp
$ npm install
$ npm link
```

Now `yo webapp` should be using the latest build.

**Comment by danielreiser** [comment]
that did the trick! thanks @silvenon for your help and the good work you guys are doing! I really appreciate it!

**Comment by silvenon** [comment]
:+1:

**Comment by patrickbjohnson** [comment]
Still running into issue. Ran the link but still showing the same error. All generators updated as of tonight as well.
