### ISSUE TITLE
Uglifying javascript libraries

### ISSUE THREAD

**Issue by dan003** [yeoman/generator-webapp_DEPRECATED#408]
So far my experience with yeoman has been great. The idea of minifying/uglifying your code is beneficial if your hosting your site on Github like I do. Unfortunately, I have encountered some errors using different JavaScript libraries. Using the prototype library: 
$bower install --save prototypejs-bower

Next, I append the library to my index source:
$grunt bowerInstall

and Finally building the distribution with:
$grunt

This is resulting in the compressed vendor.js not functioning.

What am I doing wrong, are not all JavaScript tools from bower supported?

**Comment by silvenon** [comment]
How is it not functioning? All properly written Bower components should be successfully included. Could you paste your `vendor.js` to a gist?

**Comment by dan003** [comment]
Sure I placed the exact file here:
https://gist.github.com/dotsdan

**Comment by silvenon** [comment]
Prototype is in there, so you should have access to it. Do you happen to have jQuery included as well? They both use `$` so that might be the issue.

**Comment by eddiemonge** [comment]
The minification really shouldn't minify vendor properties. its an issue with usemin though
