### ISSUE TITLE
Should live reload watch for svg image files?

### ISSUE THREAD

**Issue by alefteris** [yeoman/generator-webapp_DEPRECATED#41]
Should live reload watch for svg image files? Right now it doesn't.

There could be a problem if the svg files are the "original" files (like .psd or .ai are), and they are exported to pngs manually or with scripts in order to be used by the site. In this case, I wouldn't want them to be watched by live reload.

But I think "original" files should kept in a directory outside of app/images/. What do you think?

**Comment by passy** [comment]
That makes sense. I think if they're in `app/images/` they should be treated like other images.
