### ISSUE TITLE
Separate files on folders inside /app

### ISSUE THREAD

**Issue by pedrofelipe** [yeoman/generator-webapp_DEPRECATED#412]
I'm developing an new project that has too many screens, so I created folders inside /app to better organize, ease the validation process, etc.

If I build the project, Grunt don't change any include path (CSS, JS and images), but in live reload ($ grunt serve) everything looks nice.

Is there any way to fix this? It is really delaying the validation process since he's not using Mac or Linux and will be better if I send already built.

Thanks for your attention.

**Comment by sindresorhus** [comment]
It's documented in the Gruntfile: https://github.com/yeoman/generator-webapp/blob/bd4ece03a4ef9f9288c63d95b54f1a414213e33b/app/templates/Gruntfile.js#L5-L9

Questions like these are better asked on StackOverflow ;)
