### ISSUE TITLE
What is the ETA for 0.5.0?

### ISSUE THREAD

**Issue by nareshbhatia** [yeoman/generator-webapp_DEPRECATED#413]
After installing generator-webapp@0.5.0-1, I tried to generate a webapp, but I am getting the following error:

"You don't seem to have a generator with the name mocha installed."

However I do have generator-mocha@0.1.4 installed. What am I missing?

P.S. Sorry to ask this question here, but I could not find any forum/community dedicated to yeoman or generator-webapp (went through the yeoman site). Are you folks on https://gitter.im by any chance? It seems to be very popular these days for building communities around github projects.

**Comment by silvenon** [comment]
What does the `yo --help` command return?

**Comment by nareshbhatia** [comment]
> yo --help
> Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist

Please choose a generator below.

Webapp
  webapp:app

> npm list -g --depth=0
> C:\Users\naresh\AppData\Roaming\npm
> ├── bower@1.3.8
> ├── generator-mocha@0.1.4
> ├── generator-webapp@0.4.9
> ├── grunt-cli@0.1.13
> └── yo@1.2.0

**Comment by silvenon** [comment]
This doesn't appear to be an issue with this generator, your yo doesn't detect generator-mocha for some reason. This is a frequent issue, try googling for it.

**Comment by nareshbhatia** [comment]
Ok, will google for this issue.

In the meanwhile, I am trying to figure out if I should switch over to this version. Could you please let me know if we are close to releasing it? Are we waiting just for issue #364 as indicated by the milestone?

**Comment by silvenon** [comment]
Apparently, but it seems inactive atm. You can always use the master branch until a new version gets released:

``` sh
$ git clone https://github.com/yeoman/generator-webapp
$ cd generator-webapp
$ npm link
```

Now `yo webapp` will use whatever version is in the `generator-webapp` directory, in this case the master branch. Hope this helps until the next release.

**Comment by eddiemonge** [comment]
yeah we need to do a new release soon

**Comment by nareshbhatia** [comment]
I cleaned up my yo install and reinstalled everything. Now generator-webapp@0.5.0-1 installed correctly. So I am closing this issue.
