### ISSUE TITLE
Whitespace collapse by htmlmin causes styling issues

### ISSUE THREAD

**Issue by peterlundberg** [yeoman/generator-webapp_DEPRECATED#414]
The current generator uses htmlmin `collapseWhitespace` when creating dist. This can lead to unexpected side effects especially for inline layout. E.g. `<span>foo</span> <span>bar</span>`will look different in production. This is described in detail in http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace.

Adding `conservativeCollapse: true` to Gruntfile.js under htmlmin.dist.options and bump version to `"grunt-contrib-htmlmin": "~0.3.0"` in package.json solves this in a better way as the space byte savings works and inline style will continue working as expected without styling hacks. This is relatively new release that seems straight forward: https://github.com/gruntjs/grunt-contrib-htmlmin/compare/v0.2.0...v0.3.0

This work well for us and is a easy workaround for others. Simplyfing style and development seams a better default for the generator than optimizing the last bytes.

**Comment by peterlundberg** [comment]
Or perhaps only bumping html-minfier version (via grunt-controb-htmlmin) is enough for most people. I just found this https://github.com/kangax/html-minifier/commit/90b482e8b283631799f5010aa7f3a4746ec7260c

But this was not enough for our case (we need conservativeCollapse) probably due to nested span sections. So conservative is probably still a good default unless chasing bytes and willing to re-test layout.

**Comment by sindresorhus** [comment]
> Adding conservativeCollapse: true to Gruntfile.js under htmlmin.dist.options and bump version to "grunt-contrib-htmlmin": "~0.3.0" in package.json solves

Yep, sounds like a good idea. PR welcome :)
