### ISSUE TITLE
Add gulp-webapp-like recipes

### ISSUE THREAD

**Issue by SevereOverfl0w** [yeoman/generator-webapp_DEPRECATED#415]
Gulp-webapp has a bunch of recipes which details how to add particular technologies to your project. I feel like webapp would benefit from this also!

**Comment by sindresorhus** [comment]
Sure, PRs welcome :)

**Comment by fluke** [comment]
Recipes in this case is just documentation right? Or are they some kind of scripts you can run?

**Comment by silvenon** [comment]
Documentation. See [gulp webapp recipes](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs/recipes) for examples.
