### ISSUE TITLE
glyphicons references do not use a relative path

### ISSUE THREAD

**Issue by nareshbhatia** [yeoman/generator-webapp_DEPRECATED#417]
I have installed my yeoman generated webapp at 'localhost/myapp'. When I run the distribution version at 'localhost/myapp/dist', I get 404 errors for the following requests:

```
http://localhost/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
http://localhost/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
http://localhost/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
```

It appears that Bootstrap glyphicons are resolved using an absolute path starting at `/bower_components` instead of a relative path at `bower_components`. Is there any way to fix this?

**Comment by nareshbhatia** [comment]
Upgraded to bootstrap-saas-official v3.2 and got a slightly different problem. Now the referenced url is:

```
http://localhost/myapp/bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
```

This works - no 404 error, but it is deceiving. The file should be really be picked up from http://localhost/myapp/dist/bower_components, but it is being picked up from the http://localhost/myapp/bower_components, where the original source just happens to exist! But in a real production environment, this would not work.

**Comment by silvenon** [comment]
When I try it out, I get a nice relative `../bower_components` path, as specified in [main.scss](https://github.com/yeoman/generator-webapp/blob/master/app/templates/main.scss). Did you change the `$icon-font-path` variable? Could you describe steps to replicate this issue from a fresh build?

**Comment by nareshbhatia** [comment]
Hmmm, my main.scss has ../../bower_components:

```
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";

@import "variables";

// bower:scss
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap.scss";
// endbower
```

which looks right because this file is sitting in app/styles and to get to bower_components you would have to traverse two levels up.

(Note that I am using bootstrap-sass-official v3.2)

**Comment by nareshbhatia** [comment]
Ok solved it. By default the generator (v 4.9) generates the following icon path:

```
$icon-font-path: "/bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/";
```

I changed it to the following and the problem is solved:

```
$icon-font-path: "../bower_components/bootstrap-sass-official/vendor/assets/fonts/bootstrap/";
```

Does the latest pre-release version fix this?

**Comment by silvenon** [comment]
You're right, 4.9 does generate an absolute path, but that version is ancient in generator-webapp-land :D Yes, the pre-release fixes it.

**Comment by nareshbhatia** [comment]
Ok, I better move to the modern world!
