### ISSUE TITLE
Unused scripts by default configurations

### ISSUE THREAD

**Issue by Rodsevich** [yeoman/generator-webapp_DEPRECATED#419]
Hi, suppose we have Bower deps in the DevDependencies category, Wiredep default configuration does not include this deps by default. They will never be used and it's a bad practise to include deps outside of  and  becoase you may forget of deleting them before deploying to production and if you include them inside the tags they will be deleted.

**Comment by eddiemonge** [comment]
Those are meant for development, not for the actual site/app/product. They are mostly used in testing where you manually setup the test. If your app does depend on them, then they should be in the dependencies section.

**Comment by Rodsevich** [comment]
I focus on dependencies used (or just created exclusively) for debugging/development only. And you don't want them in your actual production release.
In example: I don't need jQuery in my app but it's useful for selecting items in the developer's toolbar of the navigator for debugging or development purposes

**Comment by eddiemonge** [comment]
@Rodsevich You dont need jQuery for that. Select an element in the inspector in then in the console you can use `$0` to use it.

**Comment by Rodsevich** [comment]
@eddiemonge jQuery is just a simple example, what about specific unit testing libraries?

**Comment by eddiemonge** [comment]
You handle those in the tests folder by creating runner pages. You shouldn't have to edit your source files to enable testing. If you do, its time to look at a different testing framework.
