### ISSUE TITLE
generator always includes bootstrap.js?

### ISSUE THREAD

**Issue by stream7** [yeoman/generator-webapp_DEPRECATED#42]
16:15 ~/Code/apps/web (yeoman) $ yo webapp

```
 _-----_
|       |
|--(o)--|   .--------------------------.
```

   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /**_A**_\   '__________________________'
     |  ~  |
   **'._**.'__
 ´   `|° ´ Y`

Out of the box I include HTML5 Boilerplate, jQuery and Modernizr.
Would you like to include Twitter Bootstrap for Sass? (Y/n) n
Would you like to include RequireJS (for AMD support)? (Y/n) y
   create Gruntfile.js
   create package.json
   create .gitignore
   create .gitattributes
   create .bowerrc
   create component.json
   create .jshintrc
   create .editorconfig
   create app/favicon.ico
   create app/404.html
   create app/robots.txt
   create app/.htaccess
   create app/scripts/vendor/bootstrap.js
   create app/styles/main.css
   create app/scripts/app.js
   create app/index.html
   create app/scripts/main.js
   create app/scripts/hello.coffee
   invoke   mocha:app
   create     test/index.html
   create     test/lib/chai.js
   create     test/lib/expect.js
   create     test/lib/mocha/mocha.css
   create     test/lib/mocha/mocha.js
   create     test/spec/test.js

I'm all done. Just run npm install && bower install to install the required dependencies.

As you see in the log it creates app/scripts/vendor/bootstrap.js
Why is that? Since I answered "No" to bootstrap sass I would expect to skip the js too.

**Comment by kevva** [comment]
@sindresorhus @passy, should we remove bootstrap js by default? I agree with @stream7 that this is kinda unexpected behaviour.

**Comment by sindresorhus** [comment]
Yes from me, but it's @addyosmani or @paulirish that wanted it by default.

**Comment by passy** [comment]
+1 for not shipping the file when disabled

**Comment by sindresorhus** [comment]
ping @addyosmani @paulirish

**Comment by felquis** [comment]
Yes, It breaks my perfect workflow with yo webapp generator.

**Comment by addyosmani** [comment]
I'm +1 on not shipping the file when disabled as well.

**Comment by kevva** [comment]
Okay, I'll remove it for now.

**Comment by paulirish** [comment]
stick a knife in it.
