### ISSUE TITLE
no node_modules installed after running yo webapp

### ISSUE THREAD

**Issue by gorioli** [yeoman/generator-webapp_DEPRECATED#420]
For example when I run - grunt serve, I get:
Loading "Gruntfile.js" tasks...ERROR 
Error: Cannot find module 'time-grunt'

In addition, bower components are missing as well.

**Comment by sindresorhus** [comment]
You most likely had an issue with npm/bower when scaffolding. The scaffolding process runs npm/bower for you. Try running `npm install && bower install` manually. Also post the terminal output of the scaffolding so we can debug why it didn't work.

**Comment by eddiemonge** [comment]
Only post back if running `npm install` didn't fix the problem (which Im guessing 95% it will, unless you have network issues). Otherwise we'll take it as this is fixed.
