### ISSUE TITLE
Import failure (File to import not found or unreadable)

### ISSUE THREAD

**Issue by alekspetrov** [yeoman/generator-webapp_DEPRECATED#423]
Can't import anything including compass, susy, breakpoint. 

grunt serve gives this: 
Warning: Error: File to import not found or unreadable: compass.
           Load paths:
             /Users/aleks/Desktop/testing/app/styles
             /Users/aleks/Desktop/testing/bower_components
            on line 4 of app/styles/main.scss

**\* LOCAL GEMS ***

bigdecimal (1.2.4)
breakpoint (2.5.0)
bundler (1.6.5, 1.6.2)
bundler-unload (1.0.2)
chunky_png (1.3.1)
compass (1.0.0.rc.1)
compass-core (1.0.0.rc.1)
compass-import-once (1.0.5)
executable-hooks (1.3.2)
ffi (1.9.3)
fssm (0.2.10)
gem-wrappers (1.2.4)
io-console (0.4.2)
json (1.8.1)
listen (1.1.6)
minitest (4.7.5)
multi_json (1.10.1)
psych (2.0.5)
rake (10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rb-kqueue (0.2.3)
rdoc (4.1.0)
rubygems-bundler (1.4.4)
rubygems-update (2.4.1)
rvm (1.11.3.9)
sass (3.4.0.rc.3)
sassy-maps (0.4.0)
susy (2.1.3)
test-unit (2.1.2.0)

yo version: 1.2.1
generator-webapp version: 0.4.9

Import in main.scss
@import "compass";

Can anybody help, I spent a lot of time trying figure out.

**Comment by eddiemonge** [comment]
This is a better question for stackoverflow where youll probably be a faster answer.
