### ISSUE TITLE
Jquery plugin css are not injected in html

### ISSUE THREAD

**Issue by Tropicalista** [yeoman/generator-webapp_DEPRECATED#424]
If I try to add a jquery plugin, it not adds the related css to the head of index.html.

I have tried with 

``` javascript
bower install --save FlipClock
grunt bowerInstall
```

the FlipClock.js is added, but the flipclock.css is not added.

**Comment by sindresorhus** [comment]
It only adds what's specified in the `main` field in the package's bower.json: https://github.com/objectivehtml/FlipClock/blob/316157e3e1f461aff8f40192c443d3e81eb300f5/bower.json#L10 Ask the author to include the CSS file too.

**Comment by Tropicalista** [comment]
yes, I've committed a change to the creator...Thanks
