### ISSUE TITLE
Phantom js warning abort my grunt command using generator-webapp

### ISSUE THREAD

**Issue by BenevidesLecontes** [yeoman/generator-webapp_DEPRECATED#428]
I'm trying to do grunt on my project but i can't and my dist folder is not created (see my output)

Running "autoprefixer:dist" (autoprefixer) task
File .tmp/styles/bootstrap.css created.
File .tmp/styles/main.css created.

Running "connect:test" (connect) task
Started connect web server on http://localhost:9001

Running "mocha:all" (mocha) task
Testing: http://localhost:9001/index.html

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

Aborted due to warnings.

**Comment by Rayman** [comment]
I think you need to do a `bower install` in your /tests directory.

**Comment by BenevidesLecontes** [comment]
Thanks resolved successful
