### ISSUE TITLE
Grunt Uglifying Fatal error: Unexpected character ''

### ISSUE THREAD

**Issue by resting** [yeoman/generator-webapp_DEPRECATED#429]
I'm having this error in both my webapp and a fresh install too.
This happens when I do a `grunt --force`.
I have asked the same question here: http://stackoverflow.com/questions/25385838/grunt-uglifying-fatal-error-unexpected-character

The --force was used to bypass these errors:

```
    app/scripts/main.js
      line 4   col 3   Expected 'var' to have an indentation at 5 instead at 3.
      line 5   col 3   Expected 'var' to have an indentation at 5 instead at 3.
      line 7   col 3   Expected '$' to have an indentation at 5 instead at 3.
      line 9   col 3   Expected 'var' to have an indentation at 5 instead at 3.
      line 10  col 7   Expected 'render' to have an indentation at 9 instead at 7.
      line 13  col 7   Expected '}' to have an indentation at 9 instead at 7.
      line 14  col 3   Expected '}' to have an indentation at 5 instead at 3.
      line 9   col 11  'skrollr' is not defined.
      line 4   col 15  'winWidth' is defined but never used.
      line 9   col 8   's' is defined but never used.
      line 10  col 28  'data' is defined but never used.

    ✖ 11 problems
```

Any idea what could be wrong?

**Comment by silvenon** [comment]
Those are JSHint errors. To fix them:
- reindent your JavaScript files to use 2 spaces instead of 4
- define `skrollr` as a global via comments (I think `/* global skrollr */` will do)
- the rest of the errors are pretty self-explanatory, you're defining those variables, but are not using them

**Comment by eddiemonge** [comment]
closing because its not a bug in the generator and an answer was given. also open on so

**Comment by resting** [comment]
@silvenon I think you misunderstood me. The real error I couldn't get through is this.

```
Running "modernizr:dist" (modernizr) task

Enabled Extras
>> shiv
>> load
>> cssclasses

Looking for Modernizr references

in dist/styles/main.css
>> svg

Downloading source files
cache modernizr-latest.js
cache modernizr.load.1.5.4.js

>> Generating a custom Modernizr build
>> Uglifying
Fatal error: Unexpected character ''
```

I should had shown this error instead. The JS errors were insignificant to me so I bypassed it with `--force`.

This error can be replicated easily by running `yo webapp` then `grunt`. I'm running webapp generator 0.4.9.

**Comment by eddiemonge** [comment]
try `npm install -g generator-webapp@0.5.0-2` then and see if that works

**Comment by resting** [comment]
@eddiemonge It still fails with the same error. 
Just another note. On a fresh install, I have to manually do a `bower install` in the test folder before `grunt` will run. 
Otherwise there's a warning:

```
Running "mocha:all" (mocha) task
Testing: http://localhost:9001/index.html

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.
```

Related to https://github.com/yeoman/generator-webapp/issues/348

**Comment by eddiemonge** [comment]
thats a bug with https://github.com/yeoman/generator-mocha/issues/25

Your issue isn't a problem with the generator since it looks like you have added code. Can you paste the project repo or show the code somewhere?

**Comment by resting** [comment]
@eddiemonge I did the test on a fresh install too. 
All I did was this:
1.  `yo webapp`
2.  Select all packages
3. `bower install` in test folder
4.  `grunt`

**Comment by eddiemonge** [comment]
``` bash
npm install -g generator-webapp@0.5.0-2
yo webapp # with all options/packages selected
cd test && bower install
cd ..
grunt
```

No errors for me. Can you post the code in the .tmp folder somewhere?

**Comment by resting** [comment]
I have a couple of files in that folder. Is there any one in particular?
- concat
  - scripts
    - main.js
    - vendor
      - modernizr.js
    - vendor.js
  - styles
    - main.css
    - vendor.css
- styles
  - main.css
  - main.css.map

**Comment by eddiemonge** [comment]
the concat/scripts ones

**Comment by resting** [comment]
Ok, here's the scripts: http://pastebin.com/J9Gd7XxL

**Comment by resting** [comment]
I think Modernizr is the culprit. Did another `yo webapp` without Modernizr and `grunt` completes without errors. 

Not sure if `grunt` is loading from cached files.

```
Downloading source files
cache modernizr-latest.js
cache modernizr.load.1.5.4.js
```

Is there anyway to clear its cache somethings?

**Comment by eddiemonge** [comment]
`bower cache clean`

**Comment by resting** [comment]
Thanks. But the problem still exists after clearing cache.
Not sure why its happening to me only.

**Comment by silvenon** [comment]
Can you go to your Gruntfile and paste just the `modernizr` task here?

**Comment by resting** [comment]
Sure, here you go.

```
    // Generates a custom Modernizr build that includes only the tests you
    // reference in your app
    modernizr: {
      dist: {
        devFile: 'bower_components/modernizr/modernizr.js',
        outputFile: '<%= config.dist %>/scripts/vendor/modernizr.js',
        files: {
          src: [
            '<%= config.dist %>/scripts/{,*/}*.js',
            '<%= config.dist %>/styles/{,*/}*.css',
            '!<%= config.dist %>/scripts/vendor/*'
          ]
        },
        uglify: true
      }
    },
```

**Comment by silvenon** [comment]
Everything is fine, damn :P This sounds like a job for [pair programming](http://www.pairprogramwith.me/). Let me know which method works the best for you and hit me on my email. (I highly suggest [tmate](http://tmate.io/) if you're on OS X.)

**Comment by resting** [comment]
Wow. Hm..ok..I'll check out tmate.
So we need to set a time I guess we need to set a time tomorrow?
I'm in GMT+8 zone and its now 6.21pm.

**Comment by silvenon** [comment]
We can decide that via email, you can find my address on my profile. Then I'll post a summary here of what happened.

**Comment by silvenon** [comment]
After some pair programming, we came to the conclusion that this wasn't an issue with this generator, it's an issue with grunt-modernizr. At the step where grunt-modernizr was supposed to go through the files and generate the custom build, it generated a scrambled file which crashed every text editor in its path.

@resting do post the link to the issue here when you create it for grunt-modernizr.

**Comment by resting** [comment]
Ok, here's the link https://github.com/Modernizr/grunt-modernizr/issues/96
