### ISSUE TITLE
Command that generates a folder with all the files needed to publish, 

### ISSUE THREAD

**Issue by Gonzalo2683** [yeoman/generator-webapp_DEPRECATED#430]
Greetings, I'm using webbapp not long ago using (bootstrap-sass). 

I've installed several plugins through bower, and in some cases the paths to the css or js files are written alone in the index.html. All good so far. All point to a bower_components files / directory. 

The main.scss file is compiled into a temporary folder. Is there any command that generates a folder with all the files needed to publish? 

Any command to package all files ?. 

I have tried to do it manually, but when I do fontawesome icons are not displayed in firefox, but if they do run from grunt serve.

**Comment by sindresorhus** [comment]
You use `$ grunt` to build your project for distribution.

Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Do paste a link to your StackOverflow question here though :)
