### ISSUE TITLE
Option for 2-space indent scaffolding

### ISSUE THREAD

**Issue by ain** [yeoman/generator-webapp_DEPRECATED#432]
If running on 2 space indentation standard for all of JavaScript in the project, `Gruntfile.js` has 4 spaces for it, always. Would be nice if it could be configured through a parameter, e.g. `--indent=2`.

**Comment by silvenon** [comment]
Gruntfile **does** use 2 space indentation. Which version are you using?

**Comment by ain** [comment]
Must be the latest, just installed with npm install -g generator-webapp and
then scaffolded with yo webapp, minutes before posting here. Node version
also updated today to v0.10.31.

**Comment by silvenon** [comment]
Oh, that's right, the latest version does use 4 spaces, but as you can see in 5dfc893c99ac67331ce341041826922a9d5b2da4, we fixed that on master so the next version will have those changes.

**Comment by ain** [comment]
:+1:

**Comment by silvenon** [comment]
[v0.5.0](https://github.com/yeoman/generator-webapp/releases/tag/v0.5.0) released!
