### ISSUE TITLE
imagemin missing?

### ISSUE THREAD

**Issue by SeeThruHead** [yeoman/generator-webapp_DEPRECATED#438]
Just tried to scaffold out a new project and grunt build no longer works

Loading "imagemin.js" tasks...ERROR

> > Error: Cannot find module 'imagemin-pngquant'

Running "concurrent:dist" (concurrent) task
    Warning: Loading "imagemin.js" tasks...ERROR
    >> Error: Cannot find module 'imagemin-pngquant'
    Warning: Task "imagemin" not found. Use --force to continue.
    Error: Task "imagemin" not found.
        at Task.run (/Users/STH/Projects/i/node_modules/grunt/lib/util/task.js:179:28)
        at /Users/STH/Projects/i/node_modules/grunt/lib/grunt.js:161:39
        at Array.forEach (native)
        at Object.grunt.tasks (/Users/STH/Projects/i/node_modules/grunt/lib/grunt.js:161:9)
        at Object.module.exports [as cli](/Users/STH/Projects/i/node_modules/grunt/lib/grunt/cli.js:38:9)
        at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)

```
Aborted due to warnings.
```

**Comment by SeeThruHead** [comment]
I cleared my dir and tried to run yo webapp again and this is what I'm getting:

grunt-contrib-imagemin@0.8.0 ../node_modules/grunt-contrib-imagemin
├── pretty-bytes@0.1.0
├── async@0.7.0
├── chalk@0.5.0 (escape-string-regexp@1.0.1, supports-color@0.2.0, ansi-styles@1.1.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── imagemin@0.4.7 (get-stdin@0.1.0, stat-mode@0.2.0, ware@0.3.0, rimraf@2.2.8, nopt@3.0.1, image-type@0.1.4, tempfile@0.1.3, fs-extra@0.10.0, imagemin-svgo@0.1.0, imagemin-optipng@0.1.0, imagemin-jpegtran@0.1.0)
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:81:16)
npm ERR!     at save (/usr/local/lib/node_modules/npm/lib/install.js:345:12)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install.js:110:7
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install.js:202:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/STH/Projects/i/test
npm ERR! node -v v0.10.30
npm ERR! npm -v 2.0.0-beta.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/STH/Projects/i/test/npm-debug.log
npm ERR! not ok code 0

**Comment by silvenon** [comment]
https://github.com/yeoman/generator-webapp/issues/431#issuecomment-53258271

**Comment by SeeThruHead** [comment]
Thanks for the help. npm update -g doesn't do anything for me.

is there a list of npm versions somewhere because I can't find it. and how can i roll back to the stable version ?

**Comment by silvenon** [comment]
I think `npm install -g npm@1.4.24` should do it, though I'm a bit fuzzy on how to exactly downgrade a globally installed package. Check with `npm -v` if it worked.

**Comment by SeeThruHead** [comment]
Ok thank you so much! Everything is working now. Can you point me in the direction of where you found the version numbers for npm? After 20 minutes of googling I couldn't find a single version number other than the beta, and nothing like changelogs.

**Comment by silvenon** [comment]
Great! There's a lot of places you can find that out, for example on the [releases page](https://github.com/npm/npm/releases) on GitHub.
