### ISSUE TITLE
Compass not watching for changes within subdirectories of 'styles'

### ISSUE THREAD

**Issue by jhummel** [yeoman/generator-webapp_DEPRECATED#44]
It seems that the watch task only runs when changes are made to files that are directly in the styles directory. If you create files within new directories, changes to those files will not trigger a recompile or the reload task. I believe adding an extra '*' to the compass files glob in the Gruntfile.js would solve this.

```
compass: {
    files: ['<%= yeoman.app %>/styles/{,**/}*.{scss,sass}'],
    tasks: ['compass']
},
```

**Comment by sindresorhus** [comment]
See comment in Gruntfile: https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L8-L12
