### ISSUE TITLE
webapp generator not running under npm 2.0 beta

### ISSUE THREAD

**Issue by briangershon** [yeoman/generator-webapp_DEPRECATED#440]
I upgraded to latest node (0.10.31) via homebrew and ended up with npm 2.0 beta.

When I went to run `yo webapp` I noticed errors like "grunt" peer dependencies not being met, when the version of grunt was actually correct.

Then I discovered I was using the beta after noticing that npm 1.4.3 was specifically mentioned by Yeoman in the install instructions.

After I downgraded npm to 1.4.5 the generator worked fine.

Here were the steps I went through to get npm 1.4.x installed: https://gist.github.com/briangershon/36824075ee64f1ddd2d6

**Comment by kevva** [comment]
It's a known issue. We had many people creating issues about this the latest days. beta === unstable.
