### ISSUE TITLE
compass integration problems

### ISSUE THREAD

**Issue by Darmikon** [yeoman/generator-webapp_DEPRECATED#442]
https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/compass.md

I made exactly to this instruction

Warning: Errno::ENOENT on line 441 of C: No such file or directory = X:/apaserver/project/=bower_components

Aborted due to warnings

**Comment by silvenon** [comment]
At which point did this error appear? On `grunt serve`? Did you start with a clean project?

**Comment by Darvile** [comment]
Same problem here when I run grunt serve, it is aborted due to warnings on compass task.

It says: Warning: Running "compass:server" (compass) task
    Error: invalid option: --import-path=bower_components

Any help is appreciated!!

Thx

**Comment by eddiemonge** [comment]
Did you try running compass directly to see what it does?

**Comment by Darvile** [comment]
Hi guys I fixed this problem updating the compass version.
