### ISSUE TITLE
Grunt Serve Fails post new scaffolding

### ISSUE THREAD

**Issue by jcolemorrison** [yeoman/generator-webapp_DEPRECATED#445]
Just updated the latest version of Yeoman and generator-webapp.  When I do a `yo webapp` alongside sass and bootstrap, and proceed to `grunt serve` I get the following error:

```
Warning: OptionParser::InvalidOption: invalid option: --sourcemap
Use --trace for backtrace. Use --force to continue.

Aborted due to warnings.
```

**Comment by silvenon** [comment]
Duplicate of #444. See https://github.com/yeoman/generator-webapp/issues/444#issuecomment-55191258.
