### ISSUE TITLE
PhantomJS timed out

### ISSUE THREAD

**Issue by mig-25** [yeoman/generator-webapp_DEPRECATED#446]
After runt the grunt command, it gets aborted with the following message when it starts to run the "mocha:all": (mocha) task
"Warning: PhantomJS timed out, possibly due to a missing Mocha run() call" Use --force to continue.

This is on a freshly installed webapp site. The grunt serve works as a charm though :+1:

**Comment by eddiemonge** [comment]
run `bower install` in the test directory. this is a known issue https://github.com/yeoman/generator-webapp/issues/348

**Comment by mig-25** [comment]
Thanks, that worked out :+1:
