### ISSUE TITLE
Mocha/PhantomJS is breaking the grunt build

### ISSUE THREAD

**Issue by patrickbjohnson** [yeoman/generator-webapp_DEPRECATED#448]
Using the yeoman webapp generator and while the app builds successfully, the app breaks on `grunt` or `grunt test` commands with the follow: 

```
Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Used --force, continuing.
```

When using force the grunt build goes through, but generates nothing to the page. Have no clue how to fix this. I've adjusted the versions to see if that would resolve the issue but nothing seems to fix it.

**Comment by silvenon** [comment]
Duplicate of #446 and #348. This is a known issue, we're working on it.

``` sh
$ cd test
$ bower install
```

**Comment by archersunx** [comment]
@silvenon , the problem still exists even after applying your method, here is my yo info

*! What would you like to do?: (Use arrow keys)

> Run the Angular-bootstrap generator (0.4.3)
>   Run the Webapp generator (0.5.0)
>   Run the Mocha generator (0.1.5)
>   Update your generators

**Comment by archersunx** [comment]
@silvenon , forget about it, I create a brand new project, and try your method, it works. So I may changed some configs in my old one that caused the problem
