### ISSUE TITLE
Race condition in concurrent:dist and concurrent:server, between copy:styles & sass

### ISSUE THREAD

**Issue by yang** [yeoman/generator-webapp_DEPRECATED#449]
Both try to create `.tmp/styles`, potentially resulting in Grunt failing with:

```
Warning: Unable to create directory "/.../.tmp/styles" (Error code: EEXIST). Use --force to continue.
```

This has been a long-standing bug that keeps rearing its head for us across projects.

**Comment by silvenon** [comment]
That's strange, I thought it should get overwritten without problems. Have you tried using `grunt` instead of `grunt build`, which deletes `.tmp` before building?

**Comment by yang** [comment]
It's a TOCTTOU race.  Basically, both are doing:

```
if dir doesn't exist
  mkdir
```

It's fine if they run one after the other, but if they both run at about
the same time, the interleaving of instructions will look like:

```
A: if dir doesn't exist (it doesn't)
B: if dir doesn't exist (it doesn't)
A: mkdir
B: mkdir (fail, already exists!)
```

**Comment by silvenon** [comment]
Oh, I misunderstood what the cause was.

**Comment by eddiemonge** [comment]
@yang want to test https://github.com/eddiemonge/generator-webapp/tree/449 to make sure it works for you?

**Comment by yang** [comment]
@eddiemonge Thanks for taking a stab!

Note that concurrency bugs are notoriously difficult to reproduce/test for without specialized tools, so it probably won't for me to run it a few times and say it works.

As a first pass over the code, I'm noting that there's now support for coffee as well.  This suggests to me that the problem has gotten a bit more complicated, to the point where my original title is no longer accurately describing the problem.  In particular, now the coffee and sass plugins may race as to which creates .tmp first (unless it can be guaranteed that .tmp is already created beforehand).

The present commit also seems to carry with it multiple orthogonal concerns.  Won't I still want my (non-sass) styles to be copied over as well?  A change to that particular behavior seems like something that is deliberate and would require its own separate commit, rather than snuck into the present one.

I believe a more basic solution here is to simply create the necessary directories in advance.  Alternative solutions include making each of the grunt plugins being called from here actually tolerate an interleaved mkdir (i.e. do something more equivalent to a `mkdir -p`, and not fail if the directory suddenly does exist).

**Comment by yang** [comment]
@addyosmani Not sure if you saw my feedback on that fix....
