### ISSUE TITLE
CSS hacks oldIE removed in build

### ISSUE THREAD

**Issue by miniplus** [yeoman/generator-webapp_DEPRECATED#451]
I'm currently working on a project in which I'm forced to support IE7 and am able to use bootstrap.
Because of this I had to use bootstrap 2.3 which has a couple of CSS oldIE hacks.
I also had to write of couple of custom rules myself.

I noticed that all rules that have CSS hacks get removed in the build process.
I solved this by using IE conditionals. Yet, I also had to overwrite vendor code.

I'm now trying to isolate the problem so I can **file an issue with the correct grunt task**, but can't immediately find out which grunt task could be causing this.

To my understanding usemin takes care of various minify tasks, including the CSS, right?

**Comment by sindresorhus** [comment]
Most likely in the css minification. [clean-css](https://github.com/jakubpawlowicz/clean-css) via grunt-contrib-cssmin.

**Comment by germanyt** [comment]
You can set the value of “compatibility” properties for ie7 in options.

example:
options: {compatibility: 'ie7'}
