### ISSUE TITLE
Livereload for scss is very slow.

### ISSUE THREAD

**Issue by liber-gong** [yeoman/generator-webapp_DEPRECATED#452]
Do you guys found livereload for scss file is very slow, takes about 5 seconds.
Version: 0.5.0 with bootstrap and sass.
Mac pro.

I just can't bear with yo.

**Comment by silvenon** [comment]
For comparison, what is your LiveReload speed without any styling? No Bootstrap, none of your custom styles, just a single rule. How long does it take then?

**Comment by sindresorhus** [comment]
Ruby is slow and Sass is slow, nothing we can do anything about.

If you want it to be faster, use grunt-sass which is a lot faster, but misses some Sass features. There's an option to use it when using this generator.
