### ISSUE TITLE
Sass sourcemap not displaying

### ISSUE THREAD

**Issue by djmtype** [yeoman/generator-webapp_DEPRECATED#455]
With a fresh install, running grunt serve, inspecting my page elements references main.css, rather than any of my scss partials. Although a sourcemap is being rendered each time in .tmp directory, it fails to show up in Web Inspector. :(

**Comment by djmtype** [comment]
This isn't so much a bug as it is a request. Please pass sass sourcemap to Web Inspector. 

I haven't figured this out yet in relation to generator-webapp, but the task should be added to autoprefixer?

Example from another gruntfile that handles sourcemap with success: 

```
autoprefixer: {
  multiple_files: {
    expand: true,
    flatten: true,
    src: 'sass/*.scss, sass/**/*.scss',
    dest: 'css/'
  },
  sourcemap: {
    options: {
      map: true
    },
    src: 'css/styles.css',
    dest: 'css/styles.css'
  }
}
```

**Comment by eddiemonge** [comment]
Which Sass are you using: Ruby or Node?

**Comment by morrislaptop** [comment]
Node...
