### ISSUE TITLE
keep getting yo webapp errors!!

### ISSUE THREAD

**Issue by cvsper** [yeoman/generator-webapp_DEPRECATED#457]
npm WARN package.json cvsper@ No description
npm WARN package.json cvsper@ No repository field.
npm WARN package.json cvsper@ No README data
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.0.0
npm ERR! path ../grunt-modernizr/bin/grunt-modernizr
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, symlink '../grunt-modernizr/bin/grunt-modernizr'
npm ERR!  { [Error: EACCES, symlink '../grunt-modernizr/bin/grunt-modernizr']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../grunt-modernizr/bin/grunt-modernizr' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

**Comment by cvsper** [comment]
![terminal](https://cloud.githubusercontent.com/assets/8705323/4414793/3fe3c388-451f-11e4-85c9-2c2404553cfc.png)

**Comment by sindresorhus** [comment]
npm issue, not us: https://github.com/npm/npm/issues
