### ISSUE TITLE
Grunt build changes font filename and breaks the font-face reference in my .css

### ISSUE THREAD

**Issue by vennsoh** [yeoman/generator-webapp_DEPRECATED#459]
Hi, 

I have a webfont that I am using. I placed the fonts folder in my styles directory as mentioned in the gruntfile.js ( 'styles/fonts/{,_/}_.*' ) Grunt serve is showing my fonts properly but after I built the file, it no longer works because the font filename has been prefixed with some weird gibberish characters. eg: 63b122ab.fontname.ttf instead of fontname.ttf

This might be some cache busting method?
But my .css file isn't updating the path to pick it up.

**Comment by eddiemonge** [comment]
This might be related to https://github.com/yeoman/generator-webapp/pull/441

**Comment by slackerzz** [comment]
I had the same issue, a quick workaround is to exclude fonts from the rev task:

``` javascript
rev: {
    dist: {
        files: {
            src: [
                '<%= config.dist %>/scripts/{,*/}*.js',
                '<%= config.dist %>/styles/{,*/}*.css',
                '<%= config.dist %>/images/{,*/}*.*',
                //'<%= config.dist %>/styles/fonts/{,*/}*.*',
                '<%= config.dist %>/*.{ico,png}'
            ]
        }
    }
},
```

**Comment by vennsoh** [comment]
ya, that's the only workaround for me.
uncomment the line that "rev" the fonts for the time being.

**Comment by slackerzz** [comment]
It should be fixed now https://github.com/yeoman/generator-webapp/commit/70d9997f7c1f315f322f3f9f31ec4a16fd6dc8a3
