### ISSUE TITLE
sass with compass not available

### ISSUE THREAD

**Issue by nithinM** [yeoman/generator-webapp_DEPRECATED#462]
Hi,
I can't find the option to configure project with sass with compass. It only show me sass. 

Thanks!

**Comment by silvenon** [comment]
It was removed. [Here](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/compass.md)'s the recipe to implement it.

**Comment by nithinM** [comment]
Thanks a lot silvenon :+1:
