### ISSUE TITLE
Disable CSS/JS minification/uglify in Gruntfile.js

### ISSUE THREAD

**Issue by vburlak** [yeoman/generator-webapp_DEPRECATED#463]
i'm using Yeoman webapp generator `0.5.0`.

My workflow using standart webapp gruntfile.js without any custom changes..
And now, I need to edit Grunt `build` task — where will be prevented CSS & JS minification.

Fitst what i try — it's to uncomment that:

```

    // By default, your `index.html`'s <!-- Usemin block --> will take care
    // of minification. These next options are pre-configured if you do not
    // wish to use the Usemin blocks.
    // cssmin: {
    //   dist: {
    //     files: {
    //       '<%= config.dist %>/styles/main.css': [
    //         '.tmp/styles/{,*/}*.css',
    //         '<%= config.app %>/styles/{,*/}*.css'
    //       ]
    //     }
    //   }
    // },
    // uglify: {
    //   dist: {
    //     files: {
    //       '<%= config.dist %>/scripts/scripts.js': [
    //         '<%= config.dist %>/scripts/scripts.js'
    //       ]
    //     }
    //   }
    // },
    // concat: {
    //   dist: {}
    // },


```

But uncommenting that lines & restarting `grunt build` task in console — not produce any effect. CSS & JS was minified & uglified again..

Then, I'm found that `grunt-usemin` controls `concat`, `uglify` and `cssmin` tasks..
but I'm confused, and I can not understand how can I configure grunt-usemin, for prevent, minifycation & uglification..
Any help with that?

**Comment by silvenon** [comment]
grunt-usemin has [documentation](https://github.com/yeoman/grunt-usemin#flow) on that.

**Comment by vburlak** [comment]
@silvenon thx a lot. Works great.

**Comment by vburlak** [comment]
May be useful for someone else:

For completely disable minification & uglification:
You must edit `useminPrepare` task and overwrite `grunt-usemin flow`  [defaults](https://github.com/yeoman/grunt-usemin#flow)

```
useminPrepare: {
  options: {
    dest: '<%= config.dist %>',
    flow: {
      steps: {
        js: ['concat'],
        css: ['concat']
      },
      post: {}
    }
  },
  html: '<%= config.app %>/index.html',
},
```

And delete `'cssmin'` & `'uglify'` in `build` task or just comment that lines

```
grunt.registerTask('build', [
    'clean:dist',
    'wiredep',
    'useminPrepare',
    'concurrent:dist',
    'autoprefixer',
    'concat',
    //'cssmin',
    //'uglify',
    'copy:dist',
    'modernizr',
    'rev',
    'usemin',
    //'htmlmin'
]);
```

**Comment by royeesh** [comment]
:+1: thanks! 
work like charm!

**Comment by ingedmundo** [comment]
It works!

But it is only copying my sass files without compilation :(

How can I compile, copy and not minify sass?

**Comment by dimerbox** [comment]
@vburlak thanks alot for the provided example helps alot!

**Comment by vburlak** [comment]
@dimerbox you're welcome!

**Comment by JonyGreen3** [comment]
i find a free online service to <a href="http://www.online-code.net/minify-js.html">compress js</a> and <a href="http://www.online-code.net/minify-css.html">minify css</a>, so it will reduce the size of web page.

**Comment by VitalyChe** [comment]
thanks
