### ISSUE TITLE
Accidentally store app in home directory of Linux OS.

### ISSUE THREAD

**Issue by gmetrix** [yeoman/generator-webapp_DEPRECATED#465]
Hi there my issue is that I suddenly realized that generated my web app on my home directory. Now, that I've cancelled the generator mid-job I created the appropriate directory and started the generator once again. PROBLEM: The generator is still being created in the home directory instead of my new directory....please help!!! (This issue is on a Linux OS)

**Comment by SBoudrias** [comment]
Delete the `.yo-rc.json` file in your home directory.

**Comment by gmetrix** [comment]
thank you so much!!
