### ISSUE TITLE
linux doesnt pull subgenerators

### ISSUE THREAD

**Issue by stephanfriedrich** [yeoman/generator-webapp_DEPRECATED#466]
hy, 
i tried to install your generator on a fresh linux. 
and i cant use any of your subgenerators, except :app.

you have to delete 
"files":[
    "app"
],
in your package.json.

http://stackoverflow.com/questions/22855656/yeoman-generator-does-not-include-subgenerator-after-publishing-to-npm

**Comment by silvenon** [comment]
We don't have any subgenerators in this generator :) @SBoudrias might know what's up with publishing subgenerators in general.
