### ISSUE TITLE
Error time-grunt not found

### ISSUE THREAD

**Issue by jonniespratley** [yeoman/generator-webapp_DEPRECATED#470]
Steps to reproduce.
1. Install generator-webapp#1.3.3
2. `$ yo webapp`
3. select bootstrap
4. After generation
5. `$ grunt`

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'time-grunt'
Warning: Task "default" not found. Use --force to continue.
```

**Comment by eddiemonge** [comment]
`generator-webapp#1.3.3`?

**Comment by kevva** [comment]
Think he meant `yo`.

**Comment by silvenon** [comment]
I think Eddie was wondering why @jonniespratley is installing such an old version of the generator.

**Comment by kevva** [comment]
generator-webapp#1.3.3 doesn't exist yet.

**Comment by silvenon** [comment]
Hahaha, my bad.

**Comment by sindresorhus** [comment]
Looks like the usual npm install corruption. Upgrade to latest npm version and reinstall.
