### ISSUE TITLE
Invalid sass returns a seg fault:11.

### ISSUE THREAD

**Issue by rickymetz** [yeoman/generator-webapp_DEPRECATED#471]
Accidentally wrote some invalid sass, and the grunt serve command failed to run sass:server.
Forcing the sass server through returns a Segmentation Fault 11 error.

It would be nice if there was syntax error handling in order to make it easier to debug.

**Comment by eddiemonge** [comment]
Did you select node-sass? Either way, this should be opened in the appropriate grunt sass package as thats what handles it.
