### ISSUE TITLE
HTML inline SVG gets minified badly

### ISSUE THREAD

**Issue by diagramatics** [yeoman/generator-webapp_DEPRECATED#477]
I wonder if anybody had noticed this. I like putting SVGs inline on the HTML file and htmlmin can make some elements disappear. For example, using htmlmin with [the CodePen logo](http://blog.codepen.io/documentation/brand-assets/logos/) makes the inner box disappear in my place.

Putting `keepClosingSlash` to `true` in htmlmin's options solves it though.

**Comment by silvenon** [comment]
Thanks for reporting this :smiley: I'm not an SVG expert, but if you're certain this is the case, could you submit a PR?

**Comment by arthurvr** [comment]
True. Using SVG this makes sense. But do you guys think it makes sense for enough users to include this option by default?

Also, It's not needed for all svg users. Not sure about the amount of users where it makes sense.

**Comment by silvenon** [comment]
I'm pretty sure more and more people use SVG and if the minifier is causing it to render the wrong way, it's a small price to pay to turn the option on…

**Comment by sindresorhus** [comment]
I think this should be fixed in the HTML minifier. It shouldn't make the SVG invalid. Open an issue/PR on its repo.

**Comment by diagramatics** [comment]
Okay, I've did my own investigation and there's an issue about it already in kangax/html-minifier#285. The only workaround for now is to enable `keepClosingSlash` (and `caseSensitive` for things like viewBox I suppose). This bug only happens when you have an inline SVG, say an icon consisting of two or more self-closing elements like paths, which is why the CodePen logo with two paths breaks.

If you guys think a workaround is necessary at this point then sure, I can make a PR.

P.S: If you're wondering, the resulting DOM is — for an SVG group with three paths in it — they are parsed as a path inside a path, inside a path.

**Comment by silvenon** [comment]
Yeah, it's better to fix it there. Otherwise there is this workaround which users will now be able to find through issues.

**Comment by duncanbeevers** [comment]
@diagramatics Thanks for bringing this up over in html-minifier. I've added https://github.com/kangax/html-minifier/pull/299 to address this.

**Comment by duncanbeevers** [comment]
@diagramatics @sindresorhus `html-minifier` now has default options baked-in to preserve svgs self-closing tags and case-sensitive tag names. We haven't yet rolled a release, but once we do, you should be able to unleash the tool on your mixed html+svg documents for great justice.
