### ISSUE TITLE
NPM: EEXIST error on first npm install (first run)

### ISSUE THREAD

**Issue by bbaaxx** [yeoman/generator-webapp_DEPRECATED#478]
I'm getting this error when running the generator for the first time on an new/empty dir:

```
npm ERR! EEXIST, open '/home/bax/.npm/65daf73e-bax-npm-lodash-2-4-1-package-tgz.lock'
File exists: /home/bax/.npm/65daf73e-bax-npm-lodash-2-4-1-package-tgz.lock
Move it away, and try again. 

npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/home/bax/.nvm/v0.10.33/bin/node" "/home/bax/.nvm/v0.10.33/bin/npm" "install"
npm ERR! cwd /home/bax/Code/lab/yoang/test
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/bax/.npm/65daf73e-bax-npm-lodash-2-4-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

It will happen even after a `npm cache clear`.

Is not a blocking issue because you can can run `npm install` afterwards and the packages will install just fine but fixing it could improve user experience.

**Comment by kevva** [comment]
Update npm (`npm install -g npm@2`). If the issue persists, please open a ticket at https://github.com/npm/npm.
