### ISSUE TITLE
Revved file names are not updated in HTML and CSS

### ISSUE THREAD

**Issue by yveslaroche** [yeoman/generator-webapp_DEPRECATED#48]
The file names are revved, but the references in the HTML and CSS file are not changed. 

Terminal output of running "grunt" with Yeoman 1.0 beta4: https://gist.github.com/yveslaroche/5340878

OS: Windows 8 64-bit
Shell: Git Bash (MSYS)
Node.js: v0.10.3

**Comment by Siyfion** [comment]
Yeah, this is _really_ quite an awkward bug for Windows users. I don't particularly feel like going through and changing all the urls in every HTML file after every build! :pensive:

**Comment by sindresorhus** [comment]
@sleeper

**Comment by Siyfion** [comment]
Any news on this? Or at least can someone point me in the right direction? I'll try and have a go at fixing this if it's not too complex.

**Comment by sindresorhus** [comment]
@kevva

**Comment by kevva** [comment]
@Siyfion, sure. https://github.com/yeoman/grunt-usemin/blob/master/lib/revvedfinder.js. Most likely a problem with forward slash or backslash somewhere. I'll have a look at it too.

**Comment by kevva** [comment]
Fixed by yeoman/grunt-usemin@1caecdb.
