### ISSUE TITLE
Can't parse config file

### ISSUE THREAD

**Issue by premchandran** [yeoman/generator-webapp_DEPRECATED#482]
Can't parse config file  :jshintrc
How do i check  whether my config file is correct and what is fix for it.

**Comment by silvenon** [comment]
This question is very unclear. You're trying to say that your `.jshintrc` is invalid as a JSON file?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
