### ISSUE TITLE
Why is libsass installation a "no" by default?

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#484]
> ? Would you like to use libsass? Read up more at
> https://github.com/andrew/node-sass#node-sass: (y/N)

I'm just curious why "no" is the default answer to this question. Is there something wrong or undesirable about libsass? I find that Sass files compile _much_ more quickly with libsass installed, like a matter of a second or two, whereas if I answer "no," Sass files take 4-5 seconds to compile.

**Comment by silvenon** [comment]
Yes, I guess this makes less and less sense as libsass is very close to Sass feature-wise. I think it doesn't support looping through maps yet, though, which is my biggest turn-off.

**Comment by sindresorhus** [comment]
When the prompt was implemented libsass was unusably buggy and feature incomplete. Things are improving fast now, but it's still not up to scratch to be default. We'll probably remove the question and only use libsass in a couple of months though.

**Comment by kevva** [comment]
Thing is, there are still some installation issues with `node-sass` on some systems, and people using node 0.11 can't use it at all (not that they should expect anything else either).

**Comment by addyosmani** [comment]
Let's give it a few months for libsass (and node-sass) to stabilise. 

Over in Web Starter Kit, we've landed libsass support in master but won't be shipping it to our users in a release until sometime in Q1 2015 for similar reasons.

**Comment by arthurvr** [comment]
Agreed. We should come back on this later.

**Comment by arthurvr** [comment]
> Let's give it a few months for libsass (and node-sass) to stabilise.

<blockquote>We'll probably remove the question and only use libsass in a couple of months though.</blockquote>

<blockquote>there are still some installation issues with node-sass on some systems</blockquote>

@sindresorhus @addyosmani @kevva We're a few months later. How are things going?

**Comment by silvenon** [comment]
At this point I would replace Ruby Sass with libsass, without the extra question.

**Comment by arthurvr** [comment]
PR #513
