### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#485]
Running **sudo yo webapp** (tried it with and without sudo)
Select **Bootstrap**
Following errors occur:
### Early in the script:

npm WARN optional dep failed, continuing imagemin-svgo@1.0.2
### Error display at the end of the script:

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.11
npm ERR! path /Users/johnchobson/.npm/connect-livereload/0.4.1
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/Users/johnchobson/.npm/connect-livereload/0.4.1'
npm ERR!  { [Error: EACCES, mkdir '/Users/johnchobson/.npm/connect-livereload/0.4.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/johnchobson/.npm/connect-livereload/0.4.1',
npm ERR!   parent: 'grunt-contrib-connect' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
### Installed manually after errors above:

connect-livereload
grunt-contrib-connect
### at this point **grunt serve WILL run with errors**, installed the following manually:

grunt-svgmin
imagemin-gifsicle
imagemin-jpegtran
imagemin-optipng
imagemin-pngquant
imagemin-svgo
js-yaml
### one final error, grunt still runs

loading svgmin.js

These might be newbie errors, not sure ....

Thanks

John

**Comment by sindresorhus** [comment]
npm install support here: https://github.com/npm/npm/issues
