### ISSUE TITLE
Wrong bower components paths inside index.html file inside app directory.

### ISSUE THREAD

**Issue by krzksz** [yeoman/generator-webapp_DEPRECATED#487]
### So, the situation is as follows:

I have my own apache-based server pointing to project generated by webapp-generator directory because my projects usually contain some php. Perfectly I would like to run `grunt watch`, and than access the app directly by `localhost/app`. 

The only problem is that grunt:wiredep seems to resolve bower components css and js files paths like they're inside app folder so I get something like:

```
!-- build:css(.) styles/vendor.css -->
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/uikit/css/uikit.min.css" />
<!-- endbower -->
<!-- endbuild -->
```

Instead of:

```
!-- build:css(.) styles/vendor.css -->
<!-- bower:css -->
<link rel="stylesheet" href="../bower_components/uikit/css/uikit.min.css" />
<!-- endbower -->
<!-- endbuild -->
```

I've been struggling with this issue for quite some time now and have no idea what to try next, I've cleared bower's cache and regenerated webapp and nothing helped.
Commenting `ignorePath` line in `grunt:wiredep` seems to fix this issue but then I'm unable to build the project because of empty `vendor.css` file.

That's my Gruntfile.js: https://gist.github.com/krzksz/d818677fc65caab51cf6

Any suggestions?

**Comment by eddiemonge** [comment]
Setup an apache rule to serve files from the `bower_components` directory from the actual filesystem directory. Or just change your `.bowerrc` file to put the bower_components in your app folder if you really really really want to.

**Comment by krzksz** [comment]
Ok, so yes, moving `bower_components` to `app` folder works fine, I just had to rewrite some modernizr config inside `Gruntfile.js`. I just wanted to know if it's normal thing for bower to wire dependencies wrongly since yeoman crew decided to move `bower_components` outside `app`. If it is, then consider this issue closed :)

**Comment by eddiemonge** [comment]
no, wiredep shouldn't be doing things wrongly. i dont see a bug here so im closing it.

**Comment by silvenon** [comment]
@krzksz It's not doing it wrong, the `../` is "missing" from the path because you (and we) [ignored it](https://gist.github.com/krzksz/d818677fc65caab51cf6#file-gistfile1-js-L167). This workflow assumes you're serving `bower_components` as it is coming from the root, so either do the same with your apache-based server or move `bower_components` to `app`.

**Comment by leonelfolmer** [comment]
Just to clarify a few things here, you are correct @eddiemonge is no bug on it. @silvenon and @krzksz you guys have to build with grunt "command" **after** create a yo app and point the web server to "dist" folder.
