### ISSUE TITLE
Performance issues with browser-sync

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#489]
When I try to use this generator with browser-sync I get a huge lag of at least 1 second every time I change my sass file. Sorry if this is the wrong place to ask, but I would like to know how much time your tasks need if you use browser-sync or if this is an issue with my setup. I guess this is a general problem with so many tasks loading. https://github.com/shakyShane/grunt-browser-sync/issues/84 :cat:

**Comment by eddiemonge** [comment]
lib or ruby sass?

**Comment by ghost** [comment]
Ruby sass atm. But this doesnt really matter, the css is generated within 200ms, but Grunt always says "Completed within 1.427s". I dont know where this huge lag of a second comes from.

**Comment by sindresorhus** [comment]
That's because of Ruby Sass being painfully slow. Nothing we can do about that. When generating a project you can choose `libsass` instead, which is much faster.
