### ISSUE TITLE
autoprefixer:dist, running grunt serve, and this issue keeps occurring

### ISSUE THREAD

**Issue by YonasBerhe** [yeoman/generator-webapp_DEPRECATED#494]
yonas@yonas:~/Documents/code/vailroom/listingpage$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

> > 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "copy:styles" (copy) task
Copied 1 files

Done, without errors.


Execution Time (2014-12-30 03:19:10 UTC)
loading tasks  1.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.8s
```

Running "autoprefixer:dist" (autoprefixer) task
Warning: .tmp/styles/main.css:60:1: Unexpected } Use --force to continue.

Aborted due to warnings.

Execution Time (2014-12-30 03:19:08 UTC)
loading tasks       1.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 43%
wiredep:app        122ms  ▇▇ 3%
concurrent:server   2.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
autoprefixer:dist   53ms  ▇ 1%
Total 4s

yonas@yonas:~/Documents/code/vailroom/listingpage$

**Comment by silvenon** [comment]
Could you paste your `.tmp/styles/main.css` in a gist?

**Comment by YonasBerhe** [comment]
https://gist.github.com/YonasBerhe/b6153b0233ea911beb1a 
- I pasted the code from the CSS file.

**Comment by silvenon** [comment]
You have an extra `}` on [line 60](https://gist.github.com/YonasBerhe/b6153b0233ea911beb1a#file-main-css-L60). Can you try to find out how that happened from your source file? Also, do you use Ruby sass or libsass?

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt/issues/1270
https://github.com/yeoman/yeoman/issues/1458
