### ISSUE TITLE
Option to remove unit testing?

### ISSUE THREAD

**Issue by wonderment** [yeoman/generator-webapp_DEPRECATED#500]
Is there any way, currently, to not install the unit testing framework when running 'yo webapp'?

We can remove the npm module and clear it from package.json + Gruntfiles.js manually but I hoped there would be something more...Yeoman-like ;-)

I ask because it would not only trim up the project for those of us not using Javascript unit testing but the initial yo webapp process would move much faster.

The Bootstrap generator is great in of itself but doesn't include the nice app/dist scaffolding, etc.

Thank you.

**Comment by eddiemonge** [comment]
Its a web_app_ though. Meaning most people will be making an app that uses JS. Removing it shouldn't make much of a difference in the initial generation. I'd rather leave it in and make people manually remove it. Testing is important

**Comment by silvenon** [comment]
:+1: what @eddiemonge said.

**Comment by wonderment** [comment]
I suppose that's dependent on the definition of "webapp". It's been a while since we've run the Bootstrap generator but I would presume there isn't a need for unit testing for basic JS there, right? Yet, there doesn't seem to be a generator in place with scaffolding and Grunt tasks similar to the webapp generator project.

Either way, it appears to vary as to where it hangs on the webapp initialization: http://i.imgur.com/ZXrKySy.gif

and not specific to mocha being added.

I guess returning an empty value on the "--test-framework" option to void the suggestive unit testing is not in our future workflow. Oh, well. Thanks for responding.

**Comment by eddiemonge** [comment]
That slow part is npm installing all of the dependencies. no way around that really. removing one of two things form testing wont change it
