### ISSUE TITLE
How to disable all concatenation/uglification?

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#503]
Sorry for this potentially newb'ish question, but I was wondering how I can get `grunt build` to build/compile all Sass and CoffeeScript, but not concatenate and uglify the files. In other words, I just want compilation so I can copy the files elsewhere and have them all run client-side, but are still fully editable and legible.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
