### ISSUE TITLE
Main.scss keep reseting 

### ISSUE THREAD

**Issue by bm2ilabs** [yeoman/generator-webapp_DEPRECATED#508]
Hello guys , i had this wired issue with main.scss keep reseting after each save when i add other file to it for example "header" or such after i save the file reload and show only the original content like bootstrap import and fonts , any one had the same issue ? 

Thank you

**Comment by bm2ilabs** [comment]
Sorry my bad i keep putting the import in the bower section of main.scss

**Comment by silvenon** [comment]
Maybe I should write a note about that in the docs, must be very frustrating :smiley:
