### ISSUE TITLE
skip auto install

### ISSUE THREAD

**Issue by sononix** [yeoman/generator-webapp_DEPRECATED#51]
I would like to skip the auto install so : I tried 

<code>
sudo yo webapp --skip-install
</code>

if this is the correct syntax it does not work for me - what should it be 

using yeoman 1.0 v4

M

**Comment by passy** [comment]
Are you using the latest version of generator-webapp, too?

By the way, you shouldn't run `yo` with sudo.

**Comment by sononix** [comment]
Mhhh I had this problem before :) with the latest build where i was a generation behind on grunt, I find if I dont run sudo I have a problem having permissions in writing files :)

Im installing yo from npm so I taking it as the default install ...

here is my package 
<code>

{
  "name": "testingapp5",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-contrib-concat": "~0.1.3",
    "grunt-contrib-coffee": "~0.6.5",
    "grunt-contrib-uglify": "~0.2.0",
    "grunt-contrib-compass": "~0.1.3",
    "grunt-contrib-jshint": "~0.4.1",
    "grunt-contrib-cssmin": "~0.6.0",
    "grunt-contrib-connect": "~0.2.0",
    "grunt-contrib-clean": "~0.4.0",
    "grunt-contrib-htmlmin": "~0.1.3",
    "grunt-contrib-imagemin": "~0.1.3",
    "grunt-contrib-livereload": "~0.1.2",
    "grunt-bower-requirejs": "~0.4.1",
    "grunt-rev": "~0.1.0",
    "grunt-usemin": "~0.1.10",
    "grunt-regarde": "~0.1.1",
    "grunt-requirejs": "~0.3.5",
    "grunt-mocha": "~0.3.0",
    "grunt-open": "~0.2.0",
    "grunt-svgmin": "~0.1.0",
    "grunt-concurrent": "~0.1.0",
    "matchdep": "~0.1.1"
  },
  "engines": {
    "node": ">=0.8.0"
  }
}

</code>

**Comment by sindresorhus** [comment]
`npm cache clean && npm install -gf yo` should solve it.

**Comment by sononix** [comment]
yes sindresorhus a cache clean fixed it but sudo doesnt work - you need to be logged in as a superuser 'sudo -s' to get it to work 

the docs and or wiki need to be updated accordingly about clearing cache and also '--skip-install' not everyone will need the install to run because custom package.json files will need to be ran...

the default action in v4 is to ran the install automatically....

**Comment by sindresorhus** [comment]
> yes sindresorhus a cache clean fixed it but sudo doesnt work - you need to be logged in as a superuser 'sudo -s' to get it to work

No, if you need sudo for npm, your system is configured wrong.

> and also '--skip-install' not everyone will need the install to run because custom package.json files will need to be ran...

Readme already documents --skip-install. And I don't see why you need to skip it. Just let it run, then do you changes and run it again, and it will only install the new stuff you added.

**Comment by sononix** [comment]
Im only guessing you are using bootstrap for all your development why give the option of installing bootstrap on the start of yeoman, the option of frame work should be offload to the package file and not hard coded into the startup routine - Im using Foundation 4 and jade and to get these currently working I need to modify the package.json, component.json and the Gruntfile.js - 

I really need a generator for this and I am currently looking into figuring out how to get one up and running 

is there a cleaner way of setting up foundation 

Again --skip-install should be documented clearer in the wiki 
tks again :)
