### ISSUE TITLE
Missing closing tags after grunt build

### ISSUE THREAD

**Issue by jonahkirangi** [yeoman/generator-webapp_DEPRECATED#518]
I've spent the last few weeks building out [www.citytrotting.com](http://www.citytrotting.com) and realized that my closing `</body>` and `</html>` tags appear to be missing. They are visible in my [master branch](https://github.com/GaneshaLabs/citytrotting), but disappear in my built and deployed code. You can see the minified code in my gh-pages branch or by viewing the source on the live site.

Any idea what may be causing this? Thanks!

**Comment by sindresorhus** [comment]
They're optional and minified away by grunt-contrib-htmlmin.

In the future use StackOverflow for support questions ;)
