### ISSUE TITLE
'yo webapp' installs above current directory

### ISSUE THREAD

**Issue by jtryan** [yeoman/generator-webapp_DEPRECATED#519]
Running the command 'yo webapp' installs the application in the directory above the working directory. This is a deviation from the way the app previously worked.

**Comment by jtryan** [comment]
maybe a bug in iTerm2? The issue cleared upon restarting that app.

**Comment by silvenon** [comment]
Maybe you had a `.yo-rc.json` file that now got deleted somehow :smiley:
