### ISSUE TITLE
"yo webapp" failure

### ISSUE THREAD

**Issue by tarunbatta** [yeoman/generator-webapp_DEPRECATED#520]
"yo webapp" is failing using the following steps,

1) npm install -g generator-webapp
2) yo webapp
3) then selecting all 3 options, i.e. Bootstrap, Sass and Modernizr
4) ? Would you like to use libsass? Read up more at
https://github.com/andrew/node-sass#node-sass: (y/N) y
# Thereafter, the following is the error,

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

   create     test\bower.json
   create     test.bowerrc
   create     test\spec\test.js
   create     test\index.html
bower                           ENOENTbower                            No bower.json present
ENOENT No bower.json present
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path D:\Data\Code\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058

npm ERR! package.json ENOENT, open 'D:\Data\Code\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Data\Code\npm-debug.log
# D:\Data\Code\testYo>

Please help with the fix.

**Comment by tarunbatta** [comment]
I tried the following,
$ npm cache clean && npm uninstall -g yeoman-generator && npm install -g yeoman-generator

# but, now it gives the following error,

C:\Users\Tarun\AppData\Roaming\npm\node_modules\bower\node_modules\insight\node_modules\configstore\index.js:86
        return this.all[key];
                       ^
TypeError: Cannot read property 'optOut' of undefined
    at Object.Configstore.get (C:\Users\Tarun\AppData\Roaming\npm\node_modules\bower\node_modules\insight\node_modules\configstore\index.js:86:17)
    at Insight.Object.defineProperty.get (C:\Users\Tarun\AppData\Roaming\npm\node_modules\bower\node_modules\insight\lib\index.js:34:22)
    at Object.setup (C:\Users\Tarun\AppData\Roaming\npm\node_modules\bower\lib\util\analytics.js:48:42)
    at Object.<anonymous> (C:\Users\Tarun\AppData\Roaming\npm\node_modules\bower\bin\bower:72:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
bower                           ENOENT No bower.json present
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path D:\Data\Code\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058

npm ERR! package.json ENOENT, open 'D:\Data\Code\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Data\Code\npm-debug.log

D:\Data\Code\testYo>

**Comment by eddiemonge** [comment]
Please open this at https://github.com/yeoman/yo/issues/new although it sounds like a npm bug
