### ISSUE TITLE
Wiredep stops working when bootstrap version is upgraded.

### ISSUE THREAD

**Issue by ernestjumbe** [yeoman/generator-webapp_DEPRECATED#523]
I using the sass version of of bootstrap as the version initially with the generator is `bootstrap-sass-official#~3.2.0` after running `bower install --save bootstrap-sass-official#3.3.3` All the javascript dependencies are removed from the html files. Is there a way to upgrade the version of bootstrap without encountering tis issue?

**Comment by silvenon** [comment]
That's very odd. Are you sure installing Bootstrap is causing this? Do they get removed when you just run `grunt wiredep` manually?

**Comment by stephenplusplus** [comment]
There's quite a difference between 3.2.0 and 3.3.3:

#### [3.2.0 bower.json](https://github.com/twbs/bootstrap-sass/blob/v3.2.0/bower.json#L12)

> ``` json
>   "main": [
>     "assets/stylesheets/bootstrap.scss",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
>     "assets/javascripts/bootstrap/affix.js",
>     "assets/javascripts/bootstrap/alert.js",
>     "assets/javascripts/bootstrap/button.js",
>     "assets/javascripts/bootstrap/carousel.js",
>     "assets/javascripts/bootstrap/collapse.js",
>     "assets/javascripts/bootstrap/dropdown.js",
>     "assets/javascripts/bootstrap/tab.js",
>     "assets/javascripts/bootstrap/transition.js",
>     "assets/javascripts/bootstrap/scrollspy.js",
>     "assets/javascripts/bootstrap/modal.js",
>     "assets/javascripts/bootstrap/tooltip.js",
>     "assets/javascripts/bootstrap/popover.js"
>   ],
> ```

#### [3.3.3 bower.json](https://github.com/twbs/bootstrap-sass/blob/v3.3.3/bower.json#L12)

> ``` json
>   "main": [
>     "assets/stylesheets/_bootstrap.scss",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
>     "assets/fonts/bootstrap/glyphicons-halflings-regular.woff2",
>     "assets/javascripts/bootstrap.js"
>   ]
> ```

Were they all squashed into that one file?

**Comment by ernestjumbe** [comment]
They are removed when I run `grunt wiredep`and when I run `grunt serve`. I have tried to revert to version 3.2.0 and upgrade and I have encountered the same results. I have also update the generator and started a new project and encountered the same result.

**Comment by ernestjumbe** [comment]
I am only left with the jquery.js in the wired dependencies.

**Comment by stephenplusplus** [comment]
Can you paste the wiredep config from your Gruntfile? I scaffolded a new project choosing Bootstrap and Sass, and the `assets/javascripts/bootstrap.js` file was in wiredep's excludes array.

**Comment by ernestjumbe** [comment]
`// Automatically inject Bower components into the HTML file
    wiredep: {
      app: {
        ignorePath: /^\/|\.\.\//,
        src: ['<%= config.app %>/index.html'],
        exclude: ['bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js']
      },
      sass: {
        src: ['<%= config.app %>/styles/{,*/}*.{scss,sass}'],
        ignorePath: /(\.\.\/){1,2}bower_components\//
      }
    },`

**Comment by stephenplusplus** [comment]
So your config is excluding it from being injected. If you remove that, it should come back. As far as why it's there in the first place, I defer to our buddy @silvenon!

**Comment by ernestjumbe** [comment]
Removing the exclude line solves the issue.

**Comment by silvenon** [comment]
:beers:
