### ISSUE TITLE
Templating recipes

### ISSUE THREAD

**Issue by igormukhin** [yeoman/generator-webapp_DEPRECATED#528]
The generator lacks a good example of templating for cases like:
- simple html templating. Like  "" or "".
- value insertions into files (like version numbers). Like "$${version}" should be replaced with "2.1.1" and  "$${sitename}" with "My site"

**Comment by silvenon** [comment]
We don't want to impose any templating engine because there are so many of them, personally I don't have a favorite one either. We leave that up to the user.

But we could use some templating [recipes](https://github.com/yeoman/generator-webapp/tree/master/docs/recipes), though.

**Comment by igormukhin** [comment]
Some recipes would be nice for that! I found it sooo helpful to have such yeoman generator like this, It saved me months of finding out the best practices. If the doc would have some recipes for templating, it would be great! Because like you said, there are so many plugins for templating, so you don't know where to start.

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
