### ISSUE TITLE
Replace grunt-mocha

### ISSUE THREAD

**Issue by benhutchins** [yeoman/generator-webapp_DEPRECATED#550]
`grunt-mocha` is becoming outdated and is not actively maintained. I recommend replacing it with https://github.com/vistaprint/grunt-js-test which offers the same features plus more, and is actively maintained and supported by a large company.

**Comment by arthurvr** [comment]
Honestly, both of these tasks don't seem super high-quality. So I'd suggest to keep the current solution, as no concrete issues pop up. (Or am I wrong about that?)

**Comment by benhutchins** [comment]
`grunt-js-test` is a little better off, but you may be right. `grunt-mocha` is simply using an outdated version of PhantomJS. I also contribute to `grunt-js-test`, which used to use `grunt-mocha`, but the dependency was removed because there were so many bugs in `grunt-mocha`. Just biased a little maybe. I'm new to using Yeoman, but when I used this generator I was sad to see the bug riddled testing library come back into my life. Plus, with `grunt-js-test`, I can actually debug the unit tests quickly, get coverage reports and perform selenium testing easily. All things that `generator-webapp` currently don't setup.

**Comment by silvenon** [comment]
I also want a better plugin, especially if I know someone is maintaining it. I'll check `grunt-js-test` out one of these days.

**Comment by silvenon** [comment]
`grunt test` was failing because of `mocha.run()`, I updated to latest generator-mocha where we made it run [conditionally](https://github.com/yeoman/generator-mocha/commit/bdf2b882a75b919182df30b0d2f94d72f33e0d7b). Now it works fine.

I'll still check out `grunt-js-test`, I just wanted to get this fatal bug out of the way :smiley:

**Comment by eddiemonge** [comment]
haha, I like that grunt-js-test hasnt been touched in 2 months but grunt-mocha had some commits recently.
