### ISSUE TITLE
wrong bootstrap link

### ISSUE THREAD

**Issue by LeonardoMinati** [yeoman/generator-webapp_DEPRECATED#556]
missing the first part of the link to the bootstrap framework in th index created.

**Comment by arthurvr** [comment]
Which link exactly?

**Comment by LeonardoMinati** [comment]
in the index created by the generator, row 12, is missing a "../" to refence to the bootstrap framework...sorry but i don't know how to explain it in a better way :disappointed:

**Comment by arthurvr** [comment]
That's indented and it works for me. Are you using `grunt serve` to serve the page? Did you do any modifications to what the generator scaffolded?

**Comment by LeonardoMinati** [comment]
i started to use yo today...i just followed the get started guide but when i open the index with chrome it seems it cannot see the bootstrap framework...i have to use grunt serve to see my website?

**Comment by arthurvr** [comment]
Maybe we have to improve the tutorial, then. Which tutorial are we talking about exactly?

> i have to use grunt serve to see my website?

Yes. It [routes](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L87) to the correct Bower path. We do this for the reasons explained in [one of our blog posts](http://yeoman.io/blog/bower_components-in-project-root.html).
