### ISSUE TITLE
Disable js and css file concatenate 

### ISSUE THREAD

**Issue by nithinM** [yeoman/generator-webapp_DEPRECATED#558]
I just want to know, is that possible to build a project without concatenate and minify css and js files? If so please let me know how I do it. This is not a bug and I need help for this.

**Comment by arthurvr** [comment]
We don't really have an option for that, no. Why would you like that? I can't see any case where minifying assets wouldn't be best practise in a build step. If you really don't like it you can always just remove the necessary  parts of the Gruntfile.

**Comment by nithinM** [comment]
Yes that is good practise, But problem was backend dev team requested separated un minified version of files. Anyway I disabled the minified option, But fail to do disable concatenation. Can you please guid me how I do that. If it's possible. https://github.com/yeoman/generator-webapp/issues/463 this one help me to disable minifying option.   

Thank you!!

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
