### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp_DEPRECATED#567]
I would like to deprecate this in favor of [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp). What do we need to do in order to achieve this?

If we want to rename (do we?):
- [ ] rename this to generator-grunt-webapp
- [ ] rename generator-gulp-webapp to generator-webapp
- [ ] `npm deprecate` generator-gulp-webapp (?)

Other tasks:
- [ ] update the docs with the deprecation notice

Questions:
- do we still do critical bugfixes?
- do we accept PRs with new features?

**Comment by sindresorhus** [comment]
:+1: 

> do we still do critical bugfixes?
> do we accept PRs with new features?

As long as someone on the team is willing to review/merge/release, why not. I'm not interested however.

**Comment by eddiemonge** [comment]
I actually want to take this in a different direction. It'd be nice if this one became a real base we could build (compose) on. I'm not sure if that means stripping out the build system and let other generators add that or something else. I just know it would be nice if I could require this in generator-angular or generator-backbone (is that still around?) or even generator-gulp-webapp and this would do the base site. Then the others could add the build system or more specific "recipes".

**Comment by arthurvr** [comment]
> I actually want to take this in a different direction. It'd be nice if this one became a real base we could build (compose) on.

I like the idea but I wonder how realistic it is. Other build system require other modifications to the templates, every framework has it's own way of managing templates, other local server setups require other paths, ... That would all be things we'd need to work around.

> generator-backbone (is that still around?)

Yes, but it's unmaintained and all the things are broken. It's really sad and nobody seems willing to pick it up.

**Comment by neilhem** [comment]
Would be great combining two build tools (generator-gulp-webapp & generator-webapp) on this project giving users choice between two build systems.

**Comment by silvenon** [comment]
We already considered this in #565, but realized that we don't want to develop the Grunt version further.

**Comment by alexconlin** [comment]
do you think there should be a deprecation warning in the readme? i'm starting a new project and just found this deprecation warning so am now switching to <a href="https://github.com/yeoman/generator-gulp-webapp">generator-gulp-webapp</a>. others might want to do the same?

**Comment by silvenon** [comment]
Definitely, thanks for the suggestion.

**Comment by gaboesquivel** [comment]
To deprecate why not simply transfer it to https://github.com/deprecate, https://help.github.com/articles/transferring-a-repository/

**Comment by adrinux** [comment]
Well, its a shame this isn't mentioned front and top of the Readme yet ;)
It'd be nice to know why you've all decided to start using gulp too. What did you gain by the switch?

**Comment by silvenon** [comment]
@adrinux sorry for the inconvenience, you're totally right, I'm preparing a deprecation notice right now.

**Comment by adrinux** [comment]
No worries silvenon. I should have looked at the issues more carefully before too! Also, this prompted me to really look at gulp and realize:
- it appears to be becoming more popular than grunt
- its faster
- the 'config' files are shorter and cleaner

Which is more than enough answers for 'why' to shift to gulp.

**Comment by silvenon** [comment]
@adrinux totally, you'll pick it up very fast, it's easy to understand :wink:

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
