### ISSUE TITLE
Links to combined CSS files are not removed from the head

### ISSUE THREAD

**Issue by jsdbroughton** [yeoman/generator-webapp_DEPRECATED#57]
Multiple <link> refs to css files are successfully combined, but the links to the originals are not removed, only the primary main.css

Not a big issue, but editing files to removed these missing links is surely not the point of build.

yeoman. 1.0.0-beta4
os. ox 10.8.3
node. v0.8.23

**Comment by addyosmani** [comment]
You are of course correct. Would you happen to have a simple test project reproducing this issue that you could share with us? I'm happy to chase up the cause of this problem otherwise.

**Comment by jsdbroughton** [comment]
By virtue of the webapp version and yeoman project in general being so much improved, this doesn't appear to be a problem anymore – whatever was causing it.
