### ISSUE TITLE
Wiredep ignore path causes Modernizr to get added to the vendor.js block

### ISSUE THREAD

**Issue by devinkemper** [yeoman/generator-webapp_DEPRECATED#570]
The change made [here](https://github.com/yeoman/generator-webapp/blob/680f0c8e71057b9afe02ba19817ca6572496b494/app/templates/Gruntfile.js#L244) causes Modernizr to get added to the regular vendor.js block if you have selected the Modernizr option.

**Comment by silvenon** [comment]
Until this is released, you can just apply the fix yourself (add the slash).

**Comment by fahimfarookme** [comment]
Whats the reason to add ignorePath for wiredep? For me it works without ignorePath as well.

**Comment by silvenon** [comment]
Because otherwise `grunt wiredep` outputs a weird `../../` path, which works in development only because paths `../../` and `../.../../../../../` still mean `/` when used from root. I'm pretty sure those paths broke the build step, I can't remember. Does your build step works with them?
