### ISSUE TITLE
Webapp with Sass and Boostrap

### ISSUE THREAD

**Issue by harshamv** [yeoman/generator-webapp_DEPRECATED#571]
I am trying to generate a webapp which uses SASS and Bootstrap (SASS version) but when i run the generator it seems to download the css version of Bootstrap.

Is there any way i can make it use SaSS version of Bootstrap? Also When i want to override some settings in bootstrap should i create the replica files outside the bower directory ??

**Comment by arthurvr** [comment]
> I am trying to generate a webapp which uses SASS and Bootstrap (SASS version) but when i run the generator it seems to download the css version of Bootstrap.

Maybe it's just an installation error. Try to remove the `bower_components` folder and run `bower install` again, then check again.

**Comment by silvenon** [comment]
> Is there any way i can make it use SaSS version of Bootstrap?

Yes, `bootstrap-sass` is used when you select Sass and Bootstrap options when you run `yo webapp`. You selected them and **still** got regular Bootstrap?

> Also When i want to override some settings in bootstrap should i create the replica files outside the bower directory ??

Yeah, that's how I do it, I copy `_variables.scss` into `app/styles` and change it there.

**Comment by arthurvr** [comment]
> Also When i want to override some settings in bootstrap should i create the replica files outside the bower directory ??
> 
> > Yeah, that's how I do it, I copy _variables.scss into app/styles and change it there.

@silvenon This might be a good addition to the documentation?

**Comment by silvenon** [comment]
Good idea, but not in this generator, because it will soon be deprecated.

**Comment by harshamv** [comment]
@arthurvr in case i need to change any other mixin. do i need to copy that as well into `app/styles` folder ?

**Comment by eddiemonge** [comment]
only if its a custom mixin that you define.
