### ISSUE TITLE
Livereload too slow.

### ISSUE THREAD

**Issue by luizpaulo165** [yeoman/generator-webapp_DEPRECATED#572]
The livereload is very slow. Does anyone know how to fix?

**Comment by neilhem** [comment]
Which version of generator-webapp are you using?

**Comment by arthurvr** [comment]
If livereload is slow, that's a problem with livereload, we can't do anything about that. It's known though that with big CSS files it might get a little slow. Though "slow" is relative, how slow?

**Comment by silvenon** [comment]
With libsass CSS compilation should be under a second. I'm closing this until we get more info.
