### ISSUE TITLE
Feat: Deploy to gh-pages

### ISSUE THREAD

**Issue by DanielMSchmidt** [yeoman/generator-webapp_DEPRECATED#575]
Hi there,

First of all thanks for this great generator, I used it like a million times and every time I needed some input for an own generator it was a great reference!
So I wanted to ask if an additional prompt or flag for a `grunt deploy` tasks would be a feature you would like to see in the generator (using [grunt-gh-pages](https://github.com/tschaub/grunt-gh-pages)). I add it almost every time, so I thought maybe I am not the only one. 

If it's okay I would be honored to add a PR with this feature :)

**Comment by eddiemonge** [comment]
We have thought about it and decided not to since there are so many countless variations on deploying. there is nothing consistent or the same that would work for the majority of people. Thank you though.
