### ISSUE TITLE
[Question] Are we required to remove the dot from dotfiles or is that just a convention?

### ISSUE THREAD

**Issue by peterpme** [yeoman/generator-webapp_DEPRECATED#577]
I'm taking a look at several yeoman generators, they all seem to follow the same convention. 

Is there a reason why we do that? Is there anything stopping me from not following this convention? 

The same applies to underscored templates.

Thank you,
Peter

**Comment by sindresorhus** [comment]
We remove the dot so they're visible during development. Just our preference though. We prefix `package.json` with an underscore so npm won't mistakenly assume it's a package. No other files needs to be prefixed with an underscore.
