### ISSUE TITLE
Building a ES2015-based app fails

### ISSUE THREAD

**Issue by chiefGui** [yeoman/generator-webapp_DEPRECATED#580]
When doing `grunt` or `grunt build`, the `eslint` accuses things like this:

> app/scripts/main.js
>   1:1  error  Unexpected token let

This is "fixed" by changing the folder `eslint` is searching for do the lint, like from `<%= config.app %>/scripts/{,*/}*.js` to `<%= config.tmp %>/scripts/{,*/}*.js`. This is happening obviously because it is searching within the `app` directory, which has the non-compiled ES2015 code and eslint doesn't know much about it, unless you defined `environment: 'es6'`, but both cases leads to errors like this:

> .tmp/scripts/main.js
>     3:13  error  "Backbone" is not defined

Also uglifying is not working as well. It is attempting to do the same as eslint: doing its task from ES2015 code, which has an unknown syntax for it.

Two alternatives I found so far:
1. Uglifying manually;
2. Avoid ES2015—which this generator is proposed to handle.

By the bye, do you have any suggestions?

**Comment by bganicky** [comment]
I'm trying to figure this now as well. Babel transpilation works well when serving in development but when I'm trying to build, uglify task is working with untranspiled ES6 source and fails.

**Comment by SunburnedGoose** [comment]
Echo.  I can't get the grunt build task to complete if there is ES2015 content in my project.

**Comment by SunburnedGoose** [comment]
I'll try it out.  I made a copy:babel task and put it after the concat task atm.

**Comment by SunburnedGoose** [comment]
Works great.  Thanks!
