### ISSUE TITLE
while using sass, new css can't be injected

### ISSUE THREAD

**Issue by Caesor** [yeoman/generator-webapp_DEPRECATED#582]
when i edit a .scss file, browser can't reload new css files in .tmp folder automaticly.

**Comment by masakura** [comment]
"." and "{}" combination path settings do not work in browserSync. At least, in my environment.

I tried browerSync settings in the GruntfileJS change from  `'.tmp/styles/{,*/}*.css'` to `'.tmp/styles/*.css'`. And then it worked.

I think due to a bug in the micromatch. jonschlinkert/micromatch#38

**Comment by silvenon** [comment]
Is this a duplicate of #579?

**Comment by eddiemonge** [comment]
lets say yes

**Comment by mertenhanisch** [comment]
I am still having this problem.
I am using .sass files (not .scss) and the folder structure of my styles required me to change the 'watch' part of sass to: '<%= config.app %>/styles/{,_/,__/}_.{scss,sass}'
When I change a .sass file, grunt watch compiles it, but the livereload or injection doesn't happen. I have to manually reload the page and then the changes are there.
So I made the suggested changes of masakura above to the browserSync part in grunt - to no avail.
Any other ideas what could be wrong here?

**Comment by silvenon** [comment]
We are working on it. Related: https://github.com/BrowserSync/grunt-browser-sync/issues/117
