### ISSUE TITLE
eslint error after some js added

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-webapp_DEPRECATED#584]
Running "eslint:target" (eslint) task
Warning: Cannot read property 'ecmaFeatures' of undefined Use --force to continue.

**Comment by arthurvr** [comment]
Can you share some more details? Like what code did you add and what version of ESLint is isntalled? What version of generator-webapp are you using? I highly doubt this is an issue with our setup though. Maybe an issue with ESLint?
