### ISSUE TITLE
browserify or the yeoman way to manage own includes

### ISSUE THREAD

**Issue by geertbrit** [yeoman/generator-webapp_DEPRECATED#587]
Normally I use browserify to require any of my own dependencies. Since including browserify in the genarator-webapp build-flow is likely non-trivial, what is the perferred (yeoman way) of managing one's own dependencies?

**Comment by silvenon** [comment]
Currently Bower, but we are having a discussion about switching to something else in yeoman/yeoman#1521.

**Comment by silvenon** [comment]
If usage of Bower isn't clear from what we provided, let us know and I'll clarify.
