### ISSUE TITLE
unable to run grunt serve with the following error on win7

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-webapp_DEPRECATED#588]
Warning: PhantomJS unable to load "http://0.0.0.0:9001/index.html" URI.

**Comment by calidion** [comment]
it would be ok to change hostname from '0.0.0.0' to 'localhost'

**Comment by silvenon** [comment]
It should be serving from localhost, I don't see why it's suddenly `0.0.0.0` on Windows. Also, why is it running PhantomJS on `grunt serve`, shouldn't that be running on `grunt test`? Could you poke around the issue some more and post a stack trace?

**Comment by calidion** [comment]
sorrry, <code>grunt</code> not <code>grunt serve</code>

**Comment by eddiemonge** [comment]
Its 0.0.0.0 specifically to listen on all addresses, not just localhost, so you can test from other computers and VMs as well as your machine. When you open a browser or specify what to open on your local machine, you can change it to localhost or 127.0.0.1
