### ISSUE TITLE
grunt test error

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-webapp_DEPRECATED#589]
Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

**Comment by calidion** [comment]
solved with

``` sh
cd test
bower install
```

**Comment by silvenon** [comment]
This was fixed in d4e91bd632329fb900613151ac554b834478c03a. You are running an outdated version of the generator. Please run `npm install --global generator-webap` and try again. (If the issue persists, I'll reopen.)
