### ISSUE TITLE
JavaScript files with multiple dots are truncated in babel.

### ISSUE THREAD

**Issue by SunburnedGoose** [yeoman/generator-webapp_DEPRECATED#593]
The preference for naming conventions in my scripts folder are files with multiple dots in the name:
- themeMaker.module.js
- variables.directive.js
- ruleService.factory.js 

When these files are processed by babel, only the prefixed is retained:
- themeMaker.js
- variables.js
- ruleService.js 

This will cause a problem when loading my page with 'grunt server' as the babel processed files will not be loaded by my webpage, and instead I'm getting the ES2015 content and the error messages.

If I comment out line 147 in the Gruntfile.js and remove the ext: '.js' from the babel dist configuration, then I can keep my full file name in the grunt processed files.

**Comment by addyosmani** [comment]
I haven't been able to verify this locally, but if this is indeed the case it appears like it would be an issue upstream with grunt-babel or babel. @silvenon are you able to repro?

**Comment by SunburnedGoose** [comment]
![2015-08-23_060736](https://cloud.githubusercontent.com/assets/984608/9427965/62b503e8-495d-11e5-9086-719017c60d0b.jpg)

Just a sanity check.  I just generated a new app, added a file to the /script folder with multiple dots in the name.  The app fails when I run grunt serve.

**Comment by sindresorhus** [comment]
Working as intended (by grunt). Read the grunt docs. This can be solved with the [`extDot`](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically) option.

**Comment by SunburnedGoose** [comment]
Thanks!
