### ISSUE TITLE
Jade by default or flag?

### ISSUE THREAD

**Issue by alvaromuir** [yeoman/generator-webapp_DEPRECATED#60]
Do enough people use jade to warrant install grunt-contrib-jade by default?
Or a tleast a flag to use it?

**Comment by passy** [comment]
I'm -1 on this. I personally use `generator-webapp` + Jade and quite enjoy it. It's not really that much effort to set up, but would increase the complexity of the generator a lot. One of the reasons for this is that we have built-in support for rewiring parts of the HTML in the base generator that we couldn't use for Jade.

**Comment by sindresorhus** [comment]
Easy enough to do it manually: https://gist.github.com/kevva/5201657 (from https://github.com/yeoman/yeoman/wiki/Articles)

**Comment by alvaromuir** [comment]
I agree it's easy to do. But so is adding bootstrap. However the power of Yeoman is the (excuse the term) scaffolding. I sometime mess around and create 20 apps a weekend, tinkering. Thats 20 times I have to add jade to the Gruntfile, and install grunt-contrib-jade

Sure, I could save my own repo locally but its not necessarily up-to-date.

Well, this is what forking is for. Thanks for the feedback.

**Comment by passy** [comment]
> Well, this is what forking is for. Thanks for the feedback.

Exactly! :)

We will soon add some generators to the website. There surely will be some space for a `generator-webapp-jade`.

**Comment by sindresorhus** [comment]
Generators are meant to be used, modified and abused. Feel free to create your own that suits your needs. Should be just a few changes to the webapp generator ;)
