### ISSUE TITLE
Live reload is not working.

### ISSUE THREAD

**Issue by vennsoh** [yeoman/generator-webapp_DEPRECATED#607]
Grunt task for watching scss changes aren't working.

I have tested by running the grunt serve, changing the body background color, it isn't doing a live reload.

Gulp-webapp is working fine.

**Comment by neilhem** [comment]
make sure you have these changes: https://github.com/yeoman/generator-webapp/commit/af6b04f6d1d347aff7dd3cba74a1249789bd4e2f

**Comment by silvenon** [comment]
Those changes were released in [v1.1.0](https://github.com/yeoman/generator-webapp/releases/tag/v1.1.0). Does it work for you with that version?

**Comment by vennsoh** [comment]
Thanks team. 

This has been fixed.
