### ISSUE TITLE
File path to reference folders outside of "app" folder isn't working?

### ISSUE THREAD

**Issue by vennsoh** [yeoman/generator-webapp_DEPRECATED#608]
All my HTML/CSS/JS are within the "app" folder.

I am trying to access a folder that is outside of that.
But the file path is not working? It will only work if I place my assets within the "app" folder.

Here I attach an image. Working on Framer.js + Yeoman
![how](https://cloud.githubusercontent.com/assets/367761/10063514/fbeb89c0-62b1-11e5-9692-46b0c1323030.jpg)

Any idea what the file path should be?
I have tried all possible combinations.

Looking at this line:
myLayers = Framer.Importer.load("./../../imported/test1")

**Comment by silvenon** [comment]
See https://github.com/yeoman/generator-gulp-webapp/issues/390#issuecomment-142867937.

**Comment by eddiemonge** [comment]
This is correct. The `/app` folder is your sites files. It can't access things outside of that, just like any other web site can't.
