### ISSUE TITLE
--test-framework=jasmine still generates mocha config

### ISSUE THREAD

**Issue by baelter** [yeoman/generator-webapp_DEPRECATED#61]
It seems like the flag has no effect on the generated Gruntfile. All test config is still for mocha.

**Comment by sindresorhus** [comment]
You have to install the Jasmine generator: `npm install -g generator-jasmine`

**Comment by addyosmani** [comment]
@baelter could you confirm if the above fix worked for you?

**Comment by baelter** [comment]
@sindresorhus Verified!
