### ISSUE TITLE
To many node modules ?

### ISSUE THREAD

**Issue by loulafripouille** [yeoman/generator-webapp_DEPRECATED#610]
Hello,
When I try to use a basic generator, like angular or webapp, there are a lot of node modules that are installed : 665, exactly.

I think that it is not the normal behavior ? Any idea ?

I already tried to uninstall/reinstall npm properly (no sudo, etc). 
I'm on a OSX 10.9, with npm@3.3.3 & node@4.1.1.
And I haven't found any issues about that.

Thanks for your advices !

laudeon.

**Comment by eddiemonge** [comment]
Its normal since other modules require other modules. npm3 flattens the list so you see all modules.
