### ISSUE TITLE
Livereload and mocha

### ISSUE THREAD

**Issue by helloncanella** [yeoman/generator-webapp_DEPRECATED#611]
Always when I type `grunt test` the process closes, showing the bars of _Execution Time_

Bellow a part of the log

```
Running "browserSync:test" (browserSync) task

Running "mocha:all" (mocha) task
Testing: http://localhost:9001/index.html


  ․․

  2 passing (4ms)

>> 2 passed! (0.00s)

Done, without errors.


Execution Time (2015-09-25 21:10:56 UTC)
loading tasks               296ms  ▇▇▇ 7%
concurrent:test              2.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 53%
loading grunt-postcss       151ms  ▇▇ 3%
loading grunt-browser-sync  693ms  ▇▇▇▇▇▇▇ 16%
browserSync:test            124ms  ▇▇ 3%
loading grunt-mocha         128ms  ▇▇ 3%
mocha:all                   592ms  ▇▇▇▇▇▇ 14%
Total 4.4s
```

Of course, I can't access the `http://localhost:9001/index.html` . 

I'm not experienced with the Grunt, despite of some reading.

My question is: how to setup the the _Gruntfile_ in order to workaround the problem, and, in addition, turn on the _livereload_, when I'm in the `http://localhost:9001/index.html`

**Comment by eddiemonge** [comment]
Grunt runs the tests once and then finishes. If you want to test continuously, run mocha directly (probably have to globally install it for a cli)

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
