### ISSUE TITLE
Cannot press space to select

### ISSUE THREAD

**Issue by tienloc1** [yeoman/generator-webapp_DEPRECATED#612]
I used windows 8.1 and I cannot press space to select my choice. Please check my screenshot.

![Image of webapp](https://cloud.githubusercontent.com/assets/3436941/10119401/3fec0a64-64bf-11e5-8370-83cdca6fdc64.jpg)

Maybe is bug? Or there away to fix it? Thank so much for help!

**Comment by silvenon** [comment]
You should raise this issue on [Inquirer.js](https://github.com/SBoudrias/Inquirer.js), which is the library we use for this prompt. I'm guessing space doesn't work on Windows then, but they might know.
