### ISSUE TITLE
Additional Bower dependencies

### ISSUE THREAD

**Issue by kalimar** [yeoman/generator-webapp_DEPRECATED#616]
I believe the documentation needs to mention how to install the test dependencies (e.g. `bower install --save mocha`). 

Does that sound right? If so, I'm happy to add and make the pull request. 

Thanks

**Comment by silvenon** [comment]
It should be `--save-dev`, because it's a development dependency. Yes, feel free to add it to the docs :+1:

**Comment by eddiemonge** [comment]
Those should get installed automatically with the mocha generator
