### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp_DEPRECATED#62]
I think it could be a good selling point if we included this by default: https://github.com/nDmitry/grunt-autoprefixer

> Yeoman will also autoprefix your CSS so you don't have to.

@addyosmani @paulirish

**Comment by passy** [comment]
Not sure about that. With Compass we would have two options to achieve basically the same thing. I see the benefit of not having to use the mixins provided with Compass, but we would have to educate the users about it which I could imagine potentially confusing.

**Comment by sindresorhus** [comment]
@passy not really, autoprefixer does it better and could be used in combination with Compass. But even so, if it were up to me we wouldn't bundle Compass, as it's incredible slow and doesn't offer much else upon vanilla Sass than prefixes (which isn't automatic btw) and sprite generation (which there are dusins of in the node world too).

**Comment by paulirish** [comment]
with compass you opt into doing the right thing
with autoprefixer you get the right thing by default.

i'm keen on baking in the right thing as long as it doesnt introduce
unexpected surprises.
can't think of any now

**Comment by addyosmani** [comment]
I'm +1 on us doing this with the assumption that we're going to spend time testing it out thoroughly on our existing generators (where Compass may be used) as well as projects that already have prefixes in place, existing Compass projects and so on. I'd love for this to be baked in, but we need to be careful.

**Comment by sindresorhus** [comment]
Indeed. This sounds like a good post 1.0 thing.

**Comment by passy** [comment]
I tried it myself and I'm convinced now. It's really tremendously helpful, especially for prefixed attributes like `-webkit-transition-property: -webkit-transform`, where compass doesn't have any helpers yet, to my knowledge. I integrated it with a `generator-angular` app and could extract a PR for webapp soon.

**Comment by addyosmani** [comment]
I'd be interested in testing out a PR for webapp just to see how well it works practically. Maybe after we've wrapped up the grunt template conversions?

**Comment by passy** [comment]
Yap, those definitely have priority.

**Comment by robwierzbowski** [comment]
@passy Yep, Compass has some prefixed attribute support but no smart prefixed property-attribute matrix yet. Although it's [on the radar](https://github.com/chriseppstein/compass/pull/1227).

Compass offers a ton besides prefixing and sprites (two big ones being an easy, consistant method of extending Sass with custom Ruby functionality, and plenty of authoring mixins that don't involve prefixing).  Most of the really popular Sass extensions are actually Compass extensions as well. I don't think removing it is a good idea.

Autoprefixer looks great though, especially the caniuse integration. If there's any question of it working well alongside preprocessors it could be added as an optional prompt.

**Comment by passy** [comment]
@robwierzbowski I'd never argue against using compass' other features. Autoprefixer works great in combination with compass for me.

**Comment by addyosmani** [comment]
I thought I commented on this in another issue, but I'd love for this to land behind a prompt so that users have the option of whether to include support for it or not. It could come right after RequireJS. Thoughts?

**Comment by passy** [comment]
@addyosmani In that case it would make sense to have this for plain CSS, too. +1

**Comment by addyosmani** [comment]
+1 on that.
