### ISSUE TITLE
required module don't install automatically

### ISSUE THREAD

**Issue by abumalick** [yeoman/generator-webapp_DEPRECATED#625]
Hello, thanks for your good work !
I just created a new app
ran npm install and bower install 
All is good, but when I run grunt or grunt serve it throws an error like: 

> > Error: Cannot find module 'slash'

Then I run npm install slash and I go on : "grunt serve", it throws another error, I install another module, etc ...

I really am bored with this, I tried to auto-install dependencies with npm modules for grunt but it's not working.
Did I miss something ?
npm 2.11.3
node v0.12.7

Thanks

**Comment by sindresorhus** [comment]
This is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`. Use the [npm issue tracker](https://github.com/npm/npm/issues) for support.
