### ISSUE TITLE
My css file in the dist folder is empty

### ISSUE THREAD

**Issue by tsinat** [yeoman/generator-webapp_DEPRECATED#628]
every thing seems to work right when i run "grunt serve" in my Yoman generated webapp and I see my scss compiled in the .tmp folder, but when I run "grunt build" my css file is available in the dist folder with nothing in it.

I have got those two empty files
     main.d41d8cd9.css
     vendor.d41d8cd9.css
please refer attached my Gruntfile
[Gruntfilejs.txt](https://github.com/yeoman/generator-webapp/files/74662/Gruntfilejs.txt)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
