### ISSUE TITLE
add_import_path to fix compass warning

### ISSUE THREAD

**Issue by budi** [yeoman/generator-webapp_DEPRECATED#629]
Hello everyone,

I'm having a trouble (not that much of a bother) when trying out the generator on my vm.

I keep getting a warning like this every time I try to edit the generated `main.css`

```
File to import not found or unreadable: bootstrap-sass-official/assets/stylesheets/_bootstrap.scss.
Load paths: /home/budi/.rvm/gems/ruby-2.2.1/gems/compass-core-1.0.3/stylesheets
Compass::SpriteImporter on line 3 of app/styles/main.scss Use --trace for backtrace.
```

As you can see, I'm using sass + compass version of the bootstrap css, provided by the generator. My current workaround for this is by adding a `config.rb` file on the root folder with this line:

```
add_import_path 'bower_components'
```

I don't know if this should be considered a bug / improvement / not, but I use bower for quite some time and I keep ended up writing that line every single time :(

**Comment by silvenon** [comment]
You're using an older version of the generator which supported Compass? Or are you rolling your own support? Can we see the `Gruntfile.js`?

**Comment by budi** [comment]
It's the mint one from the generator.
Nevertheless, it's fixed.
