### ISSUE TITLE
Deprecation of generator-webapp but it was still include in Getting started instruction in Yeoman

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#630]
I found that generator-webapp is not supported and it will be moving to generator-gulp-webapp as mentioned in https://github.com/yeoman/generator-webapp/issues/567 . I'm new to Yeoman and as a beginner it is really confusing to know that generator-webapp is still included in **Getting Started** instruction in official website.

**Comment by ghost** [comment]
**Process**
<code>npm i yo -g</code>
<code>npm i generator-webapp -g</code>

**Error:**
<code>require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly</code>

**Comment by eddiemonge** [comment]
These are two separate issues. The first is this generator being deprecated. We haven't officially deprecated it yet so the getting started guide can still be used.

As for your second comment, what version of the generator are you using?

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
