### ISSUE TITLE
mocha tests being run twice.

### ISSUE THREAD

**Issue by icholy** [yeoman/generator-webapp_DEPRECATED#65]
My mocha tests are being run twice. I tried changing the mocha config in the gruntfile to have `run:false`

``` javascript
mocha: {
    all: {
        options: {
            run: false,
            urls: ['http://localhost:<%%= connect.options.port %>/index.html']
        }
    }
}
```

When I run the `test` task I get a timeout error

`Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.`

but I can fix it by [removing](https://github.com/icholy/generator-mocha/commit/657ce9512963cf00f3562ee0d32e4926bd9eee4e) the call to `mocha.run()` in the test `index.html`.

**Comment by passy** [comment]
@icholy Sorry, this issue fall of the radar. I tried this with a freshly scaffolded project and the tests are only executed once, so I assume this got fixed. If not, please post your test setup here and we'll reopen the issue.

**Comment by hulufei** [comment]
@icholy I suppose you are using grunt-mocha, I think you may change the `mocha.run()` in your test `index.html` as this:

``` javascript
// If tests run in a real browser
// Can alternatively do a check on window.PHANTOMJS
if (navigator.userAgent.indexOf('PhantomJS') < 0) {
     mocha
        // .globals(['Wombat', 'Apple']) // acceptable globals
        run();
}
```

This is the recommended config option(with `run: true` config in `options`) by grunt-mocha. It solved my problem.

I think it's worth to mention here as the mocha template generated using `mocha.run()`.
