### ISSUE TITLE
Error in "coffee:dist" (coffee) task

### ISSUE THREAD

**Issue by felipefialho** [yeoman/generator-webapp_DEPRECATED#70]
Hi,

After run the command "grunt", returns this message:

> Running "coffee:dist" (coffee) task
>   Warning: Errno::ENOENT on line ["33"] of C: No such file or directory - C:/P
> rojetos/Yeoman/app/bower_components
>    Run with --trace to see the full backtrace Use --force to continue.
> 
>    Aborted due to warnings.

But, when I'm the run with "-force", the project is successfully compiled.

How do fix the problem?

Thanks

**Comment by passy** [comment]
Please check the guidelines for [issue submission](https://github.com/yeoman/yeoman/blob/master/contributing.md#issue-submission).

**Comment by felipefialho** [comment]
Sorry,

The informations: 

OS: Windows 7

After run 

> yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js
> 
> 1.0.0-beta.5
> $PATH $NODE_PATH
> 
> [eval]:1
> 'console.log(process.platform,
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SyntaxError: Unexpected token ILLEGAL
>    at Object.<anonymous> ([eval]-wrapper:6:22)
>    at Module._compile (module.js:456:26)
>    at evalScript (node.js:532:25)
>    at startup (node.js:80:7)
>    at node.js:901:3

The informations are correct now? 

Thanks

**Comment by addyosmani** [comment]
Unable to repro. @passy were you able to?

**Comment by passy** [comment]
@addyosmani No, I've never seen this before.

**Comment by passy** [comment]
I presume this error came up because `bower` for some reason didn't run through. If this happens again, please post here, but it's most likely something not directly related to the generator.
