### ISSUE TITLE
Add grunt-neuter support?

### ISSUE THREAD

**Issue by passy** [yeoman/generator-webapp_DEPRECATED#72]
`generator-ember` recently added `grunt-neuter` to their stack: https://github.com/yeoman/generator-ember/commit/634b2f3004cfecf9c09d9b4d09e83458cb59d9e7

It looks quite handy, but is quite different to the way we currently handle concatenation. Is this something we should consider for 1.1?

**Comment by addyosmani** [comment]
It looks like https://github.com/trek/grunt-neuter hasn't been properly released yet, but we could certainly consider it for 1.1

**Comment by passy** [comment]
I think the experience with `generator-bootstrap` has shown that this isn't the best solution for the time being.
