### ISSUE TITLE
Add grunt-bower-install support

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-webapp_DEPRECATED#73]
Using Yeoman pretty regularly one task I wish we automated better was wiring up your script tags when installing/removing components with Bower. This task by @stephenplusplus achieves this https://github.com/stephenplusplus/grunt-bower-install, however at present it has to use a namespace after grunt as follows: `grunt bower-install:jquery`.

If it's possible for us to bake this in somehow so that just running `bower install jquery` simply piped through to the above, that would be amazing. We could of course simply include the task without doing this but anything to lower how verbose the commands are would be great.

@paulirish @sindresorhus @passy

**Comment by passy** [comment]
I'd love to have it as post-install script so we can just use `bower install jquery` instead of the grunt syntax. We should bug the bower guys to implement https://github.com/bower/bower/issues/249 Bountysource? :)

**Comment by addyosmani** [comment]
Bountysourcing this wouldn't be a bad idea :)

**Comment by stephenplusplus** [comment]
Post installs would be highly awesome. If anyone thinks of another solution in the meantime, I'm happy to do what it takes on my end to make it work.
