### ISSUE TITLE
Include sinon.js or similar solution to testing libs

### ISSUE THREAD

**Issue by alefteris** [yeoman/generator-webapp_DEPRECATED#76]
I think most people that will test their web apps, will need need to use test spies, stubs or mocks at some point. http://sinonjs.org/ seems to be the most popular (?) lib that helps with that. Would you please consider adding it by default?

**Comment by passy** [comment]
I actually try to avoid using sinon when possible and only add it once my own mocks get too hairy. I personally believe this would only feel bloaty if we added this by default.

**Comment by addyosmani** [comment]
:+1: I use Sinon and even recommended it in my Backbone book, but I don't believe we should be including this by default. It's easy enough to install it and configure in a local project. There is also https://github.com/supersheep/grunt-sinon-sample which might be useful if you're stuck for an example of integration.

**Comment by passy** [comment]
FWIW, I really like Sinon too for when I need it. For me it's just a sign that my code is too complicated when I need Sinon to test it.
