### ISSUE TITLE
Synchronize with usemin 2.0

### ISSUE THREAD

**Issue by sleeper** [yeoman/generator-webapp_DEPRECATED#82]
usemin 2.0 is going to change:
- some of it's options
- requirejs in blocks is no more supported

We need to synchronize with this change (today the generated `index.html` and `Gruntfile.js` have for example requirejs blocks and the configuration to handle them)

**Comment by addyosmani** [comment]
Let's try to tackle this update after the RC1 this week has been pushed. Do you happen to have the issue for where RequireJS support in blocks was dropped handy? Just curious for the reasons though I'm sure they were sound.
