### ISSUE TITLE
'grunt server' fails to start server

### ISSUE THREAD

**Issue by gauntface** [yeoman/generator-webapp_DEPRECATED#84]
Running grunt server on my machine didn't seem to work, the browser just spins trying to connect to the server but never gets there.

I put the live reload snippet to the end of the middleware and it fixed the issue. I don't know enough to understand why this works but have rough ideas, does this make to others? If so will make pull request to change the gruntfile.js template.

livereload: {
                options: {
                    middleware: function (connect) {
                        return [
                            mountFolder(connect, '.tmp'),
                            mountFolder(connect, yeomanConfig.app),
                            lrSnippet
                        ];
                    }
                }
            },

**Comment by gauntface** [comment]
It looks like live-reload isn't working with this change . . . .

**Comment by addyosmani** [comment]
cc @passy

**Comment by gauntface** [comment]
If I use the method mentioned in issue #86, adding livereload: true, I no longer need to reorganise the lrSnippet to load pages.

https://github.com/yeoman/generator-webapp/issues/86

EDIT: Spoke too soon. This seems to fix initial loading issues, but just blocks when reloading the page.

**Comment by passy** [comment]
Closing this in favor of #86.
