### ISSUE TITLE
Grunt build wont update require.js path

### ISSUE THREAD

**Issue by najamkhn** [yeoman/generator-webapp_DEPRECATED#85]
After a `grunt build` it is currently not updating the path for require.js:

``` html
<script data-main="scripts/a57429ff.main" src="bower_components/requirejs/require.js"></script>
```

Shouldn't it be like `/scripts/vendor/###.require.js`

**Comment by addyosmani** [comment]
You're correct. It should be. We'll double check that this can be reproduced.

**Comment by frosas** [comment]
``` bash
$ yo --version
1.0.0-rc.1.4
(and webapp generator version is 0.2.7)
$ yo webapp
(all default options left enabled)
...
$ grunt build
...
$ tree dist/
dist/
├── 404.html
├── bower_components
│   └── requirejs
│       └── require.js
├── favicon.ico
├── images
│   ├── 5d462625.glyphicons-halflings-white.png
│   └── 9cc6609b.glyphicons-halflings.png
├── index.html
├── robots.txt
├── scripts
│   ├── 349a65db.main.js
│   └── vendor
│       └── f7f27360.modernizr.js
└── styles
    └── f09a630f.main.css
```

**Comment by yurevichcv** [comment]
Actually, this bug is not connected only with "generator-webapp" itself, but with other generators as well. So it is more general bug.

**Comment by sindresorhus** [comment]
RequireJS support has been removed. It bloated the generator and none of us use it so we can't provide a good service for it. I'm sure the community will fork generator-webapp and make generator-webapp-rjs ;)

https://github.com/yeoman/generator-webapp/commit/f53d0d49e2f8c334494d782e6620f6c4bf36d41d
