### ISSUE TITLE
Issues with watch:livereload task

### ISSUE THREAD

**Issue by stephenplusplus** [yeoman/generator-webapp_DEPRECATED#86]
## Edit

Please check out and test against this repository:
https://github.com/stephenplusplus/yo-webapp-livereload-test

We're mostly concerned with the files that require compilation (Sass files, Coffee files), so be sure to edit the heck out of those. Try to make the task fail in anyway possible, then let me know how it goes.

---

Here's how webapp currently generates the Gruntfile:

``` js
watch: {
    options: {
        nospawn: true
    },
    coffee: {
        files: ['<%%= yeoman.app %>/scripts/{,*/}*.coffee'],
        tasks: ['coffee:dist']
    },
    coffeeTest: {
        files: ['test/spec/{,*/}*.coffee'],
        tasks: ['coffee:test']
    },
    compass: {
        files: ['<%%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server']
    },
    livereload: {
        options: {
            livereload: LIVERELOAD_PORT
        },
        files: [
            '<%%= yeoman.app %>/*.html',
            '{.tmp,<%%= yeoman.app %>}/styles/{,*/}*.css',
            '{.tmp,<%%= yeoman.app %>}/scripts/{,*/}*.js',
            '<%%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
        ]
    }
}
```

Unless I remove `nospawn: false`, any files that require compiling won't trigger a reload. Specifically, if I try to save an edit to a CoffeeScript file, it will be compiled, but the browser won't reload.

Another solution that works for me:

``` js
watch: {
    options: {
        nospawn: true,
        livereload: LIVERELOAD_PORT // set as default for all tasks, which will share the same port
    },
    coffee: {
        files: ['<%= yeoman.app %>/scripts/{,*/}*.coffee'],
        tasks: ['coffee:dist']
    },
    coffeeTest: {
        options: {
            livereload: false // not sure if this is necessary
        },
        files: ['test/spec/{,*/}*.coffee'],
        tasks: ['coffee:test']
    },
    compass: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server']
    },
    html: {
        files: ['<%= yeoman.app %>/*.html']
    },
    css: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.css']
    },
    images: {
        files: ['<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}']
    }
}
```

The `html`, `css`, and `images` tasks could be joined under a single task as well, but to avoid confusion, this seemed straight forward.

If I'm the only one experiencing the issue in the first place, this proposal isn't necessary. However, if I'm not alone, and this looks more like what we were going for in the first place, this update might be necessary across the generators.

**Comment by gauntface** [comment]
I'm having issues with the watch livereload, but this doesn't fix the issue for me :(

**Comment by passy** [comment]
I can confirm this behavior. I saw that before in the `generator-ember` PR when editing sass files or anything that required a compilation step.

**Comment by iamjohnlong** [comment]
I'm having the same issue as well. It will reload for the first three or four edits and the watch stalls out. @stephenplusplus Your solution isn't work for me. I'm editing coffeescript.

**Comment by stephenplusplus** [comment]
@iamjohnlong :( It's 100% for me, editing a Coffee file several times in a row, even including flipping back to index.html for an edit, then back to Coffee. Reloads every time.

Though I did notice there wasn't a watch for CSS files, so I've updated my first post to include that.

**Comment by addyosmani** [comment]
@stephenplusplus is it working in 100% of cases for you across all types of file that can be observed/changed? (incl. non-Coffee scripts, markup etc).

**Comment by stephenplusplus** [comment]
@addyosmani HTML, CSS, and CoffeeScript.

Has anyone tried the stock configuration with `watch: { options: { nospawn: false`?

**Comment by stephenplusplus** [comment]
With everything else default (brand new `yo webapp` with all `Y` responses), this is the cross-computer, cross-networks, works-everytime solution for me:

``` js
watch: {
    options: {
        nospawn: true,
        livereload: LIVERELOAD_PORT
    },
    coffee: {
        files: ['<%= yeoman.app %>/scripts/{,*/}*.coffee'],
        tasks: ['coffee:dist']
    },
    coffeeTest: {
        files: ['test/spec/{,*/}*.coffee'],
        tasks: ['coffee:test']
    },
    compass: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server', 'autoprefixer' ]
    },
    styles: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.css'],
        tasks: ['copy:styles', 'autoprefixer']
    },
    html: {
        files: ['<%= yeoman.app %>/*.html']
    },
    images: {
        files: ['<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}']
    },
    js: {
        files: ['<%= yeoman.app %>/scripts/{,*/}*.js']
    }
}
```

If anybody tries this specifically from a brand new scaffold, please let me know if the errors are still present, and if anything else was changed from default.

We'll figure this out!

**Comment by iamjohnlong** [comment]
Setting `nospawn: false` seems to have done the trick for me.

```
watch: {
    options: {
        nospawn: false,
        livereload: LIVERELOAD_PORT
    },
    coffee: {
        files: ['<%= yeoman.app %>/scripts/{,*/}*.coffee'],
        tasks: ['coffee:dist']
    },
    coffeeTest: {
        files: ['test/spec/{,*/}*.coffee'],
        tasks: ['coffee:test']
    },
    compass: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server']
    },
    html: {
        files: ['<%= yeoman.app %>/*.html']
    },
    css: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.css']
    },
    images: {
        files: ['<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}']
    }
},

```

**Comment by addyosmani** [comment]
So..nospawn: true works for one person and nospawn:false works for another? :) This is continuing to be tricky to solve. @iamjohnlong Could you let us know what OS you're on in case this is a factor? I'm testing my setup now. Would be great to confirm which of the two above works for @passy or @sindresorhus.

Note: if testing, please make sure you're doing so against master rather than what's on npm.

**Comment by iamjohnlong** [comment]
@addyosmani 

yeoman: 1.0.0-beta.6
node: v0.10.5
os: OSX 10.8.4

**Comment by larsonjj** [comment]
I tried both potential solutions mentioned:

<b>Solution 1</b>

<pre>
options: {
   nospawn: true,
   livereload: LIVERELOAD_PORT
},
</pre>

<b>Solution 2</b>

<pre>
options: {
   nospawn: false,
   livereload: LIVERELOAD_PORT
},
</pre>

Both seem to do the trick in terms of getting livereload working.
One caveat though is that solution 2 seems to be much slower:

<pre>
>> File "app/styles/main.scss" changed.
Running "compass:server" (compass) task
overwrite .tmp/styles/main.css 
Running "autoprefixer:dist" (autoprefixer) task
File ".tmp/styles/main.css" created.
Done, without errors.
... Reload app/styles/main.scss ...
... Reload .tmp/styles/main.css ...
<b>Completed in 2.883s</b> at Tue Jun 18 2013 16:48:42 GMT-0500 (CDT) - Waiting...
</pre>

Solution 1 seems to handle everything a bit faster:
<b> Edit:</b> Editing CoffeeScript doesn't seem to trigger the reload, it just sits there waiting...

<pre>
>> File "app/styles/main.scss" changed.
Running "compass:server" (compass) task
overwrite .tmp/styles/main.css 
Running "autoprefixer:dist" (autoprefixer) task
File ".tmp/styles/main.css" created.
Running "watch" task
... Reload app/styles/main.scss ...
<b>Completed in 1.684s</b> at Tue Jun 18 2013 16:38:22 GMT-0500 (CDT) - Waiting...
</pre>

<b>Update:</b> After some more thorough testing with both SASS and CoffeeScript, the solution for me was just this:

<pre>
options: {
   nospawn: false,
},
</pre>

Yeoman: 1.0.0-beta.6
generator-webapp: 0.2.3 (master)
Node: 0.10.11
OS: OSX 10.8.4

**Comment by addyosmani** [comment]
I'm going to play around with nospawn: true and false a little further to see which of the above is the most reliable.

**Comment by stephenplusplus** [comment]
I've created a test repository to hopefully help us track this down: https://github.com/stephenplusplus/yo-webapp-livereload-test

If the solution there doesn't work, please come back and discuss (with details of your environment) or submit a PR (there) with a solution that works.

Let's :hammer: this :bug:

**Comment by passy** [comment]
Your example works great for me. node v0.10.10 @ Ubuntu. Thanks for putting this together, @stephenplusplus.

**Comment by iamjohnlong** [comment]
Tested with @stephenplusplus  test repo.

I'm wondering if this may be a coffeescript issue. I added 

```
<!-- build:js(.tmp) scripts/coffee.js -->
<script src="scripts/hello.js"></script>
<!-- endbuild -->
```

to the html and started editing the hello.coffee file and it stops the compile and reload.

Restarted server and played with the sass.. Worked 15 edits in a row.

Switched over to hello.coffee and made a 5 edits then stopped on the 6th edit.

Switched to html and it started working again. Made a couple of edits. Works.

Switched back to coffee and it compiled and reloaded once then stopped.

Can anyone play around with coffeescript and see if they are having the same issue?

node: v0.10.5
yo: 1.0.0-beta.6
os: osx 10.8.4

**Comment by ragingwind** [comment]
I have a no problems. node: v0.10.5, yo: 1.0.0-beta.6 @ Mac OSX 10.8.4

**Comment by ragingwind** [comment]
Sorry.. miss click.

**Comment by addyosmani** [comment]
I can confirm that when working with Sass alone LiveReload appears to be a lot more stable than when working with CS, however @stephenplusplus was using CS in his earlier tests and didn't run into any issues with this at all.

**Comment by stephenplusplus** [comment]
I've made an update to the Gruntfile, setting `nospawn: false` only where necessary. If everyone can check out and test my test repository real quick, it would be most appreciated!

https://github.com/stephenplusplus/yo-webapp-livereload-test

We're mostly concerned with the files that require compilation (Sass files, Coffee files), so be sure to edit the heck out of those. Try to make the task fail in anyway possible, then let me know how it goes.

Thanks everyone!

**Comment by addyosmani** [comment]
I was testing with Stephen earlier and just wanted to chime in that I've also had 100% success with the above. If we're able to get confirmations that this works for everyone, we'll apply a fix after the weekend.

**Comment by iamjohnlong** [comment]
@stephenplusplus I'm having 100% success with this solution. :+1: 

Thank you @stephenplusplus @addyosmani

**Comment by cmalven** [comment]
@stephenplusplus @addyosmani I can confirm that this test repo worked for me and the related changes are also working in my own projects. I was never able to get LiveReload working consistently before.

**Comment by sindresorhus** [comment]
Thanks for digging into this @stephenplusplus 
So weird.

@shama any thoughts on why this workaround is required?

**Comment by shama** [comment]
`nospawn: true` means those tasks will run in the same context as the watch task. Thus if the task breaks, the watch breaks. Which is why I am a proponent for spawning tasks. It is slower but it is more reliable.

My guess is the tasks that are set to spawn (`nospawn: false`) were attempting to break the context/watch task. So setting them to spawn makes them work.

My opinion is that everything should spawn (remove all `nospawn: true` and `nospawn: false` to use the default). As it will avoid issues for _most_ people.

FWIW, I'm looking into making the watch task a daemon. Which means it will run in the same context but upon the context failing, will fork a new processes. Not sure if it will fix this issue but for now, I recommend spawning all the things.

**Comment by addyosmani** [comment]
I agree with @shama's recommendations above re:

> My opinion is that everything should spawn (remove all nospawn: true and nospawn: false to use the default). As it will avoid issues for most people.

As we've given people the chance to test over the weekend I'll apply the patch to generator-webapp accordingly.

**Comment by pixelize** [comment]
Had the same issue that the livereload was not working with scss anymore. As suggested here, changing nospaw to false worked for me (It's quite slow, there are about 2,3 seconds delay to the css being refreshed and display in my browsers that i didn't have in former version )

```
options: {
  nospawn: false
},
```

**Comment by FilipZawada** [comment]
I had a problem with `spawn: false` causing livereload not refresh on css change. Solution seen above works great even with the latest yeoman (I've modified it slightly):

```
options: {
        spawn: false,
        livereload: '<%= connect.options.livereload %>'
      },
     ...
```
