### ISSUE TITLE
Fails in Windows if .gitignore or .gitattributes exists

### ISSUE THREAD

**Issue by jonrimmer** [yeoman/generator-webapp_DEPRECATED#88]
The generator fails when run in Windows Powershell if a .gitignore or .gitattributes file already exists. The generator asks you what you want to do (overwrite, skip, etc.) and tell you to use the arrow keys to select an option, but then immediately exits back to the command prompt.

**Comment by addyosmani** [comment]
I'm pretty sure this is due to the recent update we made to the latest version of Inquirer for our prompts system. There's a thread going about it over at https://github.com/yeoman/generator/issues/293 and https://github.com/yeoman/generator/issues/291 and

**Comment by stephenplusplus** [comment]
@JonRimmer this should be resolved with the latest Inquirer release. Please update and give it another go.

**Comment by jonrimmer** [comment]
Yeah, it's fixed. Cheers!
