### ISSUE TITLE
Latest version failing to build on Windows 7 x64

### ISSUE THREAD

**Issue by tcrosen** [yeoman/generator-webapp_DEPRECATED#96]
I just installed yeoman following the quick start guide as I have done many times before on my Mac but I just encountered the following error with the `generator-webapp` using all defaults on my Windows box. Here's what happens when I run `grunt` after a successful install:

```
Warning: Errno::ENOENT on line ["33"] of C: No such file or directory - C:/Development/yo-test/app/bower_components
Run with --trace to see the full backtrace Use --force to continue.
```

And as it turns out the `bower_components` directory isn't created at all.

**Comment by tcrosen** [comment]
Just tested on OSX with the same params and worked fine.

**Comment by addyosmani** [comment]
Thanks for reporting this. Could you try an `npm cache clean` and a full re-install of Yeoman and let us know if you run into the same issue? Could you also `sudo` and let us know if you experience anything different?

**Comment by raphaelvalerio** [comment]
I just scaffolded with the latest version of yo and generator-webapp on Win 8 x64 and I did not have this problem. "app/bower_components" is created and running "grunt" is successful.

Did you update "generator-webapp" in addition to "yo"? It sounds to me very much like one of the npm modules on your box is an older build and conflicting.

**Comment by tcrosen** [comment]
It's a new box so it's a fresh install of everything, Node, NPM, Yeoman, etc.
I just cleared the npm cache as you requested and tried again, it seems the `grunt-bower-requirejs` package isn't being installed for some reason.  Here is the full grunt output:

> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?

  Running "jshint:all" (jshint) task

> > 4 files lint free.

  Running "clean:server" (clean) task

  Running "concurrent:test" (concurrent) task

> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?

  Running "connect:test" (connect) task
  Starting connect web server on localhost:9000.

  Running "mocha:all" (mocha) task
  Testing: http://localhost:9000/index.html

```
.

1 test complete (1 ms)
```

> > 1 passed! (0.00s)

  Running "clean:dist" (clean) task
  Cleaning ".tmp"...OK

  Running "useminPrepare:html" (useminPrepare) task
  Going through app/index.html to update the config
  Looking for build script HTML comment blocks

  Found a block:
          
          <script src="bower_components/modernizr/modernizr.js"></script>
          
  Updating config with the following assets:
      - app\bower_components\modernizr\modernizr.js

  Found a block:
          
          <script data-main="scripts/main" src="bower_components/requirejs/require.js"></script>
          
  Updating config with the following assets:
      - dist\scripts\main.js

  Configuration is now:

```
cssmin:
{ dist:
 { files:
    { '<%= yeoman.dist %>/styles/main.css':
       [ '.tmp/styles/{,*/}*.css',
         'app/styles/{,*/}*.css' ] } } }

concat:
{ 'dist\\scripts\\vendor\\modernizr.js': [ 'app\\bower_components\\modernizr\\modernizr.js' ],
'dist\\scripts\\main.js': [ 'dist\\scripts\\main.js' ] }

uglify:
{ 'dist\\scripts\\vendor\\modernizr.js': 'dist\\scripts\\vendor\\modernizr.js',
'dist\\scripts\\main.js': 'dist\\scripts\\main.js',
'dist\\bower_components\\requirejs\\require.js': 'app\\bower_components\\requirejs\\require.js' }

requirejs:
{ dist:
 { options:
    { baseUrl: 'app/scripts',
      optimize: 'none',
      preserveLicenseComments: false,
      useStrict: true,
      wrap: true,
      name: 'main',
      out: 'dist\\scripts\\main.js',
      mainConfigFile: 'app\\scripts\\main.js' } } }
```

  Running "concurrent:dist" (concurrent) task

> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?
> > 
> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?
> > 
> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?
> > 
> > Local Npm module "grunt-bower-requirejs" not found. Is it installed?

  Running "imagemin:dist" (imagemin) task
  ? app/images/glyphicons-halflings-white.png (already optimized)
  ? app/images/glyphicons-halflings.png (already optimized)
      Warning: Errno::ENOENT on line ["33"] of C: No such file or directory - C:/Development/Personal/yo-test/app/bower_components
      Run with --trace to see the full backtrace Use --force to continue.

```
  Aborted due to warnings.
```

I tried to install that package manually (locally & globally), re-created an app with Yeoman and still getting the same problems.  And just to be clear, I do this all the time on OSX so it has to be something to do with Windows 7.  I even tried on multiple shells (Powershell & cmd.exe).

If I make any progress I'll update here but if you have any additional commands I can try for debugging please let me know.

**Comment by tcrosen** [comment]
Here's the log _after_ I installed the `grunt-bower-requirejs` package manually:

C:\Development\Personal\yo-test> grunt
  Running "jshint:all" (jshint) task

> > 4 files lint free.

  Running "clean:server" (clean) task

  Running "concurrent:test" (concurrent) task

  Running "coffee:dist" (coffee) task

  Running "connect:test" (connect) task
  Starting connect web server on localhost:9000.

  Running "mocha:all" (mocha) task
  Testing: http://localhost:9000/index.html

```
.

1 test complete (1 ms)
```

> > 1 passed! (0.00s)

  Running "clean:dist" (clean) task
  Cleaning ".tmp"...OK

  Running "useminPrepare:html" (useminPrepare) task
  Going through app/index.html to update the config
  Looking for build script HTML comment blocks

  Found a block:
          
          <script src="bower_components/modernizr/modernizr.js"></script>
          
  Updating config with the following assets:
      - app\bower_components\modernizr\modernizr.js

  Found a block:
          
          <script data-main="scripts/main" src="bower_components/requirejs/require.js"></script>
          
  Updating config with the following assets:
      - dist\scripts\main.js

  Configuration is now:

```
cssmin:
{ dist:
 { files:
    { '<%= yeoman.dist %>/styles/main.css':
       [ '.tmp/styles/{,*/}*.css',
         'app/styles/{,*/}*.css' ] } } }

concat:
{ 'dist\\scripts\\vendor\\modernizr.js': [ 'app\\bower_components\\modernizr\\modernizr.js' ],
'dist\\scripts\\main.js': [ 'dist\\scripts\\main.js' ] }

uglify:
{ 'dist\\scripts\\vendor\\modernizr.js': 'dist\\scripts\\vendor\\modernizr.js',
'dist\\scripts\\main.js': 'dist\\scripts\\main.js',
'dist\\bower_components\\requirejs\\require.js': 'app\\bower_components\\requirejs\\require.js' }

requirejs:
{ dist:
 { options:
    { baseUrl: 'app/scripts',
      optimize: 'none',
      preserveLicenseComments: false,
      useStrict: true,
      wrap: true,
      name: 'main',
      out: 'dist\\scripts\\main.js',
      mainConfigFile: 'app\\scripts\\main.js' } } }
```

  Running "concurrent:dist" (concurrent) task

  Running "htmlmin:dist" (htmlmin) task

  Running "coffee:dist" (coffee) task

  Running "svgmin:dist" (svgmin) task

  Running "imagemin:dist" (imagemin) task
  ? app/images/glyphicons-halflings-white.png (already optimized)
  ? app/images/glyphicons-halflings.png (already optimized)
      Warning: Errno::ENOENT on line ["33"] of C: No such file or directory - C:/Development/Personal/yo-test/app/bower_components
      Run with --trace to see the full backtrace Use --force to continue.

```
  Aborted due to warnings.
```

**Comment by addyosmani** [comment]
Stupid question and I know it's been some time: can you remember if your directory structure did indeed have bower_components written to it?

**Comment by tcrosen** [comment]
Addy, you of all people should know there is no such thing as a stupid question, especially when you are providing a free service and supporting it :)

I do remember, it did not create the bower_components directory.

**Comment by theiwaz** [comment]
I am running into the same trouble with using the new yeoman. Tried it out with the angular and the webapp generator but both with the same error though instagated by different libs, with angular it's `coffee` and with the webapp it's `svgmin`. 

```
Running "svgmin:dist" (svgmin) task
    Warning: Errno::ENOENT on line ["33"] of C: No such file or directory - C:/Temp/ym/app/bower_components
Run with --trace to see the full backtrace Use --force to continue.
```

## versions
- npm 1.2.18
- node 0.10.5
- yeoman 1.0.0-rc.1.2

## dir structure after running webapp generator

```
24-07-2013  21:18                44 .bowerrc
24-07-2013  21:18               415 .editorconfig
24-07-2013  21:18                11 .gitattributes
24-07-2013  21:18                56 .gitignore
24-07-2013  21:18               411 .jshintrc
24-07-2013  21:22    <DIR>          .tmp
24-07-2013  21:20    <DIR>          app
24-07-2013  21:18               200 bower.json
24-07-2013  21:22    <DIR>          dist
24-07-2013  21:20            11.288 Gruntfile.js
24-07-2013  21:20    <DIR>          node_modules
24-07-2013  21:20               933 package.json
24-07-2013  21:20    <DIR>          test
```

Have tried it on my workstation at work and my laptop at home. Same result. 

Really annoying, really wanting to try out yeoman and have been trying a couple of times

**Comment by stephenplusplus** [comment]
Hope this isn't a silly suggestion that everyone has already tried, but I just wanted to throw it out there. Sometimes when scaffolding, there'll be an error that prevents npm install and bower install from running. Namely, the "Mocha" not found error. In any case, if you run bower install, it should clear up these errors.

**Comment by ariellephan** [comment]
Thanks @stephenplusplus ! I had this error on a newly installed Windows. Turns out I forgot to install git, which stop some package from being installed when you first scaffold the app. Ran bower install and it did clear up these errors.

**Comment by roggel2000** [comment]
I still have the same issue on Windows 8 x64. Simply running bower install doesn't do the trick for me.

What DID do the trick, was to add the following line to .bowerrc:
    `"json": "bower.json"`
So the .bowerrc file now looks like this:

```
{
    "directory": "app/bower_components",
    "json": "bower.json"
}
```

Doing a `bower install` after that got me up and running.
